### ISSUE TITLE
error during installation if owncloud is already installed

### ISSUE THREAD

**Issue by Vey** [YunoHost-Apps/nextcloud_ynh#1]
Hi,

First I'd like to thank you for your work on porting the app!

I was excited to see that someone already started the transition so I went ahead and tried to install it using web admin and it returned no error but when connecting to nextcloud a 404 error happened.

Using ssh i got:

> Attention : Job for nginx.service failed. See 'systemctl status nginx.service' and 'journalctl -xn' for details.
Succès ! Configuration de SSOwat générée avec succès
Succès ! Installation terminée
:~# systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled)
   Active: active (running) (Result: exit-code) since mar. 2016-05-24 20:48:24 CEST; 1 months 7 days ago
  Process: 8283 ExecReload=/usr/sbin/nginx -g daemon on; master_process on; -s reload (code=exited, status=1/FAILURE)
 Main PID: 1546 (nginx)
   CGroup: /system.slice/nginx.service
           ├─ 1546 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
           ├─ 7502 nginx: worker process
           ├─ 7503 nginx: worker process
           ├─ 7504 nginx: worker process
           ├─ 7505 nginx: worker process
           └─17308 nginx: worker process is shutting down

> systemd[1]: Reloading A high performance web server and a reverse proxy server.
 nginx[7336]: nginx: [emerg] duplicate location "/.well-known/caldav" in /etc/nginx/conf.d/mywebsite.eu.d/owncloud.conf:4
 systemd[1]: nginx.service: control process exited, code=exited status=1
 systemd[1]: Reload failed for A high performance web server and a reverse proxy server.
 systemd[1]: Reloading A high performance web server and a reverse proxy server.
 systemd[1]: Reloaded A high performance web server and a reverse proxy server.
 systemd[1]: Reloading A high performance web server and a reverse proxy server.
 nginx[8283]: nginx: [emerg] duplicate location "/.well-known/caldav" in /etc/nginx/conf.d/mywebsite.eu.d/owncloud.conf:4
 systemd[1]: nginx.service: control process exited, code=exited status=1
 systemd[1]: Reload failed for A high performance web server and a reverse proxy server.
:~# journalctl -xn
-- Logs begin at mer. 2016-06-22 22:10:01 CEST, end at ven. 2016-07-01 16:16:02 CEST. --
 slapd[3145]: <= mdb_equality_candidates: (uniqueMember) not indexed
 slapd[3145]: <= mdb_equality_candidates: (uniqueMember) not indexed
 slapd[3145]: <= mdb_equality_candidates: (uniqueMember) not indexed
 slapd[3145]: <= mdb_equality_candidates: (uniqueMember) not indexed
 CRON[8306]: pam_unix(cron:session): session closed for user owncloud
 sshd[8367]: Connection closed by 120.25.230.254 [preauth]
 CRON[8305]: pam_unix(cron:session): session closed for user nextcloud
 CRON[8370]: pam_unix(cron:session): session opened for user root by (uid=0)
 CRON[8371]: (root) CMD (/usr/local/rtm/bin/rtm 14 > /dev/null 2> /dev/null)
 CRON[8370]: pam_unix(cron:session): session closed for user root

Then I deleted owncloud and now nextcloud is working.

I'm available If you need any additionnal tests or informations

**Comment by jeromelebleu** [comment]
Hi! Thanks for reporting this bug.

Reading the log, we see:
```
nginx[8283]: nginx: [emerg] duplicate location "/.well-known/caldav" in /etc/nginx/conf.d/mywebsite.eu.d/owncloud.conf:4
```

So, this is only related to the `.well-known` path which is already served by ownCloud app... I should find a better way to enforce this detection.

**Comment by jeromelebleu** [comment]
Could you paste the whole app installation output when you have ownCloud installed please?

**Comment by Vey** [comment]
The output I pasted was all i had and guessed it was set to silent install or something.

Regarding owncloud update. I had the previous update but not the latest. cause I didn't want to mess with the install and figured that trying nextcloud wouldn't hurt.

I try to wipe everything and start again the process of installing owncloud and then installing nextcloud

**Comment by Vey** [comment]
I get an erro when trying to reinstall:
> Impossible de récupérer les fichiers sources
unable to download https://github.com/YunoHost-apps/owncloud_ynh/archive/85dff2bf2ac12e6ef38c0f9f67cf144755e5449f.zip

**Comment by jeromelebleu** [comment]
> The output I pasted was all i had and guessed it was set to silent install or something.

Oops, you're right, sorry, you have to pass `--verbose` to have the full output...

> I get an erro when trying to reinstall

Maybe a network issue since I've no problem here to download this file. Could you try again please?

**Comment by Vey** [comment]
I couldn't make it to work through admin interface. maybe it comes from the temp file being not deleted yet or whatnot.

Meanwhile, using ssh: https://paste.yunohost.org/egejoqotop.diff

**Comment by jeromelebleu** [comment]
Sorry for the late answer... Could you paste the output of `nginx -t` and `yunohost app list --installed` please?

**Comment by Vey** [comment]
Hi,

Back then, I upgraded and it worked. So you got that going for you, which is nice :)

Meanwhile I proceeded to test all others yunohost apps and desinstalled them. So there may be some ghost behaviour but it didn't seem so.

I had to redo the procedure. So owncloud is installed again and tried to install nextcloud and got the same result: owncloud working and 404 page on /nextcloud
Output is: https://paste.yunohost.org/igiwenonov.diff

Note that, from the beginning, I had Baikal installed before installing owncloud etc so it might be a source of conflicts.

Let me know if you need addional informations or testing

**Comment by jeromelebleu** [comment]
Oh, thanks, I think I found why the following line is not working:

```
curl -s -o /dev/null -w '%{http_code}' https://example.org/.well-known/caldav
```

It always returned `000` in each output you give instead of `301` or `302` HTTP status code. The first reason is because of the certificate which is probably not known by curl - can be fixed with `-k` parameter. But it will generally redirect to another page because of the SSO... So, the check is not strength enough.

**Comment by jeromelebleu** [comment]
It should be fixed with https://github.com/YunoHost-Apps/nextcloud_ynh/commit/cc21dc5fa3c951c181653a9487bd7e8c151cbfc6, could try again please and confirm?

**Comment by Vey** [comment]
Uninstalled Nextcloud and reinstalled and It worked !

Note that although owncloud files have been successfully erased during previous uninstall process, it is not the case with nextcloud.

As it is not related, do you mark the issue as resolved or is it something that can only be done on my side?

**Comment by jeromelebleu** [comment]
> Uninstalled Nextcloud and reinstalled and It worked !

Nice, glad to know! I'll close this issue so.
