### ISSUE TITLE
Can't log out from Nextcloud

### ISSUE THREAD

**Issue by Kcchouette** [YunoHost-Apps/nextcloud_ynh#106]
Same as #83 (I copy paste the issue, as it is exactly same and reproduced)

For version **13.0.1**

- Bug 1:
I log in Yunohost through SSO, I click on Nextcloud icon and arrive in the File section of Nextcloud.
I click on log out from the top right menu section of Nextcloud.
Nextcloud reload and I come back to the Files section of Nextcloud.
It seems the log out option of Nextcloud is broken.

 - Bug 2:
I log in Yunohost through SSO, I click on Nextcloud icon and arrive in the File section of Nextcloud.
I go back to the SSO welcome page (page with all apps icons), I click on log out. I am out of Yunohost.
I enter the direct link to Nextcloud (such as www.myyunohost.org/nextcloud) and I am automatically log in Nextcloud.
And now I can log out Nextcloud from from the top right menu section of Nextcloud (I am not brought back to the file section of Nextcloud, like in Bug 1 situation).
I seems the SSO log out does not disconnect Nextcloud.

- Other situation: If I log in Nextcloud through direct link (such as www.myyunohost.org/nextcloud), and entering ID /password on the Nextcloud welcome page, then I can log out from the top right menu section of Nextcloud.

**Comment by croulibri** [comment]
me too :-(

**Comment by Kcchouette** [comment]
It's ok for me @JimboJoe

**Comment by JimboJoe** [comment]
Has any of you two got the chance to test the PR...?

**Comment by croulibri** [comment]
Has the PR been merged ?
The 2 bugs are still present on my Yunohost / Nextcloud

**Comment by JimboJoe** [comment]
The fix has been released in testing [here](https://forum.yunohost.org/t/official-app-nextcloud/4104/62).

**Comment by JimboJoe** [comment]
The latest stable release includes a fix for this :wink:
