### ISSUE TITLE
In case of error updating from v12 to v13.0.1, stay in maintenance mode

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/nextcloud_ynh#108]
Updating from the last v12 Nextcloud version package to the v13.

As the /tmp was full, the installation stopped with a "PGP error (...) NODATA (...)" (weird but no connected with the installation). The reason was the size of the uncompressed nextcloud v13 package bigger than my /tmp.
Then, the nextcloud instance stayed unreachable, displaying a message " this instance is under maintenance(...)", until a new installation try success.

In case of error, we should keep our installation available.

**Comment by maniackcrudelis** [comment]
In case of error during the upgrade, your instance is supposed to be restored the way it was before the upgrade.
Could you provide a whole log to see what happens after the error with /tmp ?

**Comment by klorydryk** [comment]
what log file could be usefull?

**Comment by maniackcrudelis** [comment]
The log of your upgrade.
You can still find a log in /var/log/yunohost/yunohsot-cli.log

But you will have to keep only the interesting part.

**Comment by alexAubin** [comment]
Closing because lack of feedback / outdated ... (feel free to reopen if needed)
