### ISSUE TITLE
Check if there is enough space in /tmp before attempting upgrade

### ISSUE THREAD

**Issue by roukydesbois** [YunoHost-Apps/nextcloud_ynh#109]
Hello,
I am running Yunohost on a Olimex board. By default when you install Armbian, a separate partition of 500M is created for /tmp. So, when I tried to upgrade Nextcloud, the upgrade failed because there was not enough space on /tmp to download and/or extract the archive containing Nextcloud. The nextcloud database was then removed because the upgrade failed.
So I think it would be useful to add a check before the upgrade to see if there is enough space on /tmp, halting the upgrade if it is not big enough.

**Comment by JimboJoe** [comment]
Fixed by https://github.com/YunoHost-Apps/nextcloud_ynh/pull/127
