### ISSUE TITLE
Missing dependencies on Stretch

### ISSUE THREAD

**Issue by genma** [YunoHost-Apps/nextcloud_ynh#112]
As post in French on https://forum.yunohost.org/t/beta-testing-phase-for-yunohost-3-0-on-debian- stretch/4798/53
Nextcloud not working on Yunohost 3.0 (on debian stretch).

**Comment by genma** [comment]
Solved !!! apcu extension is missing after migration.
Need to do 
apt-get install php7.0-apcu -y
service nginx restart
And Nextcloud works !!!!

**Comment by alexAubin** [comment]
That should nevertheless be integrated in the app if that's really needed, so the issue is only fixed for you :sweat_smile:  :wink:

**Comment by JimboJoe** [comment]
Fix PR opened: https://github.com/YunoHost-Apps/nextcloud_ynh/pull/116
