### ISSUE TITLE
Is it possible to manage groupfolders ?

### ISSUE THREAD

**Issue by LeLieuMultiple** [YunoHost-Apps/nextcloud_ynh#118]
I finished installing nextcloud_ynh on Raspberry Pi. Is the group folder feature available ?
https://apps.nextcloud.com/apps/groupfolders
I didn't find it inside the GUI.

**Comment by maniackcrudelis** [comment]
This feature is an addon for nextcloud, you can add it from the Applications page of your nextcloud.
