### ISSUE TITLE
Why the home directory don't get deleted?

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/nextcloud_ynh#128]
Hi
I removed the Nextcloud. Nectcloud got deleted but the home folder /home/yunohost.app/nextcloud was not removed while the remove script ran. Is this done for a reason? If the app home folder is huge the admin will never know and it will keep on eating space on server.

**Comment by maniackcrudelis** [comment]
Because you don't want to loose all your personal data just because you remove Nextcloud.
A warning could be print to inform the admin though.

**Comment by anmol26s** [comment]
Yes that would be a good idea to send an email to admin about this. I really want to know the solution for this because another app Peertube uses videos and the apps home folder grows more rapidly if there are large videos. And backup of the data while upgrade can take long time and an error in the script can delete all the videos. The case is similar to Nextcloud.

**Comment by maniackcrudelis** [comment]
I'm not sure to understand the issue here.
What is the "solution" you're looking for ?

**Comment by anmol26s** [comment]
That if the app like Peertube deletes the home folder under yunohost.app while remove script runs, then how to prevent the removing of the yunohost.app home folder of the app when there would be an error in upgrade and restore script together. And not removing this folder will have no benefit for the admin as the video will be kept in random names and are useless for the users or admin, which is not  the case of Nextcloud(as the Nextcloud data will be useful for admin and users), but kind of similar if the admin don't know that the Nextclould has been removed but its app folder under Yunohost.app is still there. 

I think better solution would be to send an email to admin that home folder is still there under yunohost.app and that admin will require to remove it manually after the remove script runs for Nextcloud and all such apps having large data under yunohost.app.

**Comment by maniackcrudelis** [comment]
It's probably the better solution we could have for now.
You can use this experimental helper, https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/send_readme_to_admin/send_readme_to_admin to perform that job.

**Comment by anmol26s** [comment]
Thank for the solution.
