### ISSUE TITLE
nextcloud is leaking specific php configuration globally

### ISSUE THREAD

**Issue by julienmalik** [YunoHost-Apps/nextcloud_ynh#138]
The content of conf/php-fpm.ini is installed to fpm/conf.d making the options available to all fpm pools.
The correct way to set php options for a specific pool is to set them in the pool.d/{{app}}.conf file

I noticed this after a stretch migration, where the specific files in conf.d from php5 are not copied over to the equivalent php7 dir. Thus nextcloud complained about unoptimized php settings after the migration (in settings/Administration/Basic Settings/Security & setup warnings).

Manually adding :
```
php_value[opcache.enable]=1
php_value[opcache.enable_cli]=1
php_value[opcache.interned_strings_buffer]=8
php_value[opcache.max_accelerated_files]=10000
php_value[opcache.memory_consumption]=128
php_value[opcache.save_comments]=1
php_value[opcache.revalidate_freq]=1
```
at the end of `/etc/php/7.0/fpm/pool.d/nextcloud.conf` fixes the warnings

**Comment by maniackcrudelis** [comment]
Indeed, I just made some tests with the plugin WordPress phpinfo() and you're right, using a specific ini file doesn't work as expected !
Thanks to have found that out, I'm going to fix that in all our apps.

**Comment by Gofannon** [comment]
@maniackcrudelis, could you, if you can and you remember, explain the tests you made and what to look after? (before and after and which variable/whatever)
I can create a php page with `phpinfo()` like this http://php.net/manual/en/function.phpinfo.php

Or maybe upgrading an official app with the testing version is enough to validate ?

**Comment by maniackcrudelis** [comment]
What do you want to do exactly ?

**Comment by Gofannon** [comment]
My goal is to help validating the modification (PR) on the application Dokuwiki.

To do so, I would like to test the `testing` version of the app and I asked myself:
> "What should I check on the version to see if the modification is successful? Maybe that @maniackcrudelis knows what to look after because he proposed a fix to the issue? So he had to find the issue and know how to check"

This is the reason behind my previous message. I need to know what to look after and where to find it. As it is related to php settings, I searched for a way for show the variables before and after the PR and found `phpinfo()` thanks to your previous post

> Indeed, I just made some tests with the plugin WordPress phpinfo() and you're right, using a specific ini file doesn't work as expected !

Your post also made me think that you knew what settings to look after.


Is my explanation about my goal and my thought process better?

**Comment by maniackcrudelis** [comment]
As julienmalik has explained, if you set a variable, whatever you want, in conf.d, this setting will be enable for all apps using php.
Instead, if you set it in pool.d, the setting will be only for this app.

So to test it, you can install dokuwiki and either wordpress with a plugin or directly a phpinfo() script. And check if your secondary app have the settings set for dokuwiki.
Here, it would be `upload_max_filesize 30M` and `post_max_size 30M`
