### ISSUE TITLE
Nextcloud 11.0.1 (security fixes)

### ISSUE THREAD

**Issue by genma** [YunoHost-Apps/nextcloud_ynh#14]
Nextcloud 11.0.1 with security fixes is released https://nextcloud.com/blog/nextcloud-bugfix-and-security-updates/

**Comment by maniackcrudelis** [comment]
Thanks genma, I waiting for some objections before merge the 2 PR relative to the upgrade process.
And then will add this upgrade.

**Comment by maniackcrudelis** [comment]
Ok, so the merge of the 2 PR has not really so simple.
And I breaked the install script...

So this commit, https://github.com/YunoHost-Apps/nextcloud_ynh/commit/9bca6ceb3be22a1b2fef83f9d82163fe0f957ce6, repairs my bullshit.

But, tomorrow I'll perform some others tests on different cases of upgrade.
I'll inform on this issue when all are checked.

**Comment by maniackcrudelis** [comment]
And, luckily I perform some tests today ...
So, the package is finally fixed and improved.

You can upgrade your nextcloud, it'll be upgrade to 11.0.1
