### ISSUE TITLE
Blank page after upgrade

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/nextcloud_ynh#142]
Hello,

After upgrading to the lastest version, I have a blank page sometimes when I'm using Nextcloud on files view.
For instance, the main page when I logging is blank (except the blue header and the left column : I can't see any file).
If I look somewhere else, for instance in /myfolder I can see the files. But in /myfolder/myotherfolder I can't.

Do you know where I can look to get more informations on this issue ?

**Comment by JimboJoe** [comment]
Proposing to merge this issue for now as there were no news recently. Don't hesitate to reopen it if the propose still occurs/occurs again.
