### ISSUE TITLE
Nextcloud 14.0 Released

### ISSUE THREAD

**Issue by siliconninja** [YunoHost-Apps/nextcloud_ynh#145]
Just letting you know that Nextcloud 14.0 has been out for a few months (latest version 14.0.4).
https://nextcloud.com/blog/nextcloud-14-now-available-with-video-verification-signaltelegram-2fa-support-improved-collaboration-and-gdpr-compliance/
I haven't seen many changes other than a branch `nextcloud14` being created and `testing` being slightly updated with a few changes. What are your plans for this change? (I'm not asking for ETAs, I'm just curious about how you are handling this change). Unfortunately, I don't have time to contribute code to this right now.

**Comment by JimboJoe** [comment]
Hi,
Times have been busy for a few of us, but thanks for the reminder, work is ongoing [here](https://github.com/YunoHost-Apps/nextcloud_ynh/pull/146)!

**Comment by siliconninja** [comment]
No problem! Since discussion for Nextcloud 14 can now be moved to the pull request, I'm closing this issue.
