### ISSUE TITLE
Update from OC 9.x -> NC 11.x fails.

### ISSUE THREAD

**Issue by jdbean** [YunoHost-Apps/nextcloud_ynh#15]
Update from YNH official owncloud install as instructed in readme file fails (and nukes owncloud in the process). Owncloud/nextcloud does not support upgrades spanning more than one major version number.

The introduction of introduction of nextcloud 11.x to the installer in this repo blocks upgrade path from yunohost official owncloud app,

Please provide interim OC 9.x -> NC 10.x alternative.

**Comment by maniackcrudelis** [comment]
Hello

We know this, a PR wait to be pushed for this problem.
See here https://github.com/YunoHost-Apps/nextcloud_ynh/pull/13

Is your owncloud really dead ? The restore script doesn't worked correctly?

I try to merge this 2 PR today.

**Comment by jdbean** [comment]
Hi,

Thanks so much. Glad to know that a fix is in process.

I've already reverted to a full system backup so I can't say about the owncloud install.

**Comment by maniackcrudelis** [comment]
Hello jdbean,

if you don't already did, you can migrate your owncloud. It'll migrate to nextcloud 11.0.1

**Comment by jdbean** [comment]
Haven't had much of a chance to test but the upgrade appears to have been successful. Thanks!
