### ISSUE TITLE
backup before update

### ISSUE THREAD

**Issue by cabbes** [YunoHost-Apps/nextcloud_ynh#16]
I have a big problem with the updage of this package.
Before update Nextcloud, il make a backup... a backup of ALL ITS DATA.... while my datas are on external folder (local type)
Is it possible to backup only nextcloud files (/var/www/nextcloud) ?

**Comment by maniackcrudelis** [comment]
Hello cabbes

Except regression, the backup do not copy the data for prevent this situation.
https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/backup#L24-L32

But, maybe the upgrade use the old backup script.

Let me do some test to check this ;)

**Comment by maniackcrudelis** [comment]
As i thought, it's the old backup script that used in upgrade. So to prevent this failure, the backup during upgrade is now not possible before the 11.0.1 version of nextcloud...

**Comment by gpsqueeek** [comment]
I do not know if it is linked or not, but I have trouble upgrading from 11.0.0 to 11.0.1 (running Yunohost 2.5.4). If upgrading with the command line, (not working from the web admin interface and  no log) I get the following messages :
yunohost app upgrade nextcloud
Warning: The backup's archive name already exists
Warning: Backup failed, the upgrade process was aborted.
Error: Unable to upgrade nextcloud
Error: No app to upgrade
The second line suggests I enter the "if" on line 24 in the upgrade script ; so I tried using the following command :
cat /var/www/nextcloud/version.php | grep OC_VersionString | cut -d\' -f2
and the result is 11.0.0, which seems correct, but I do not know why we would enter the "if" in this case as it is not strictly superior to 11.0.1
Anything I can try to help ?

**Comment by maniackcrudelis** [comment]
This upgrade script begin to tire me...

So, if you can retry the upgrade in CLI with the --verbose argument. And post into a pastebin the result. Like that I can look the execution of your upgrade.

**Comment by gpsqueeek** [comment]
Here you go...
http://paste.yunohost.org/yiwabewobe.diff
I hope this helps... Keep up the good work, don't hesitate to ask for more tests ;-)

**Comment by maniackcrudelis** [comment]
Ok...

It's my fault, I forgot to change the targeted commit in the official list of apps.
I knew that this system will finish to make me a joke...

Sorry.

**Comment by gpsqueeek** [comment]
Pas besoin d'être désolé, tu fais un super boulot ! Comme on dit, hein, y'a que ceux qui font rien qui font pas de c***neries ^^ (dit le mec qui n'a jamais rien commité nulle part même s'il y pense de plus en plus fort)

**Comment by maniackcrudelis** [comment]
Merci gpsqueeek :)

C'est pas dramatique si tu contribues pas, mais tu sais qu'il y a plein de moyen de contribuer si tu le souhaites.
On t'accueillera à bras ouverts :)

**Comment by gpsqueeek** [comment]
Oh oui je sais bien, après c'est plus une question de caser plus de 24h par jour sans oublier mes gênes de marmotte huhuhu

**Comment by JimboJoe** [comment]
Targeted commit in the official app list has been updated when upgrading Nextcloud 11.0.2.
