### ISSUE TITLE
Install properly keeweb?

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/nextcloud_ynh#161]
Hello,

Keeweb for nextcloud has been updated and can be installed again now, as explain here https://github.com/jhass/nextcloud-keeweb

However, it needs Mimetype detection to be done (also explain in the same page).
Is "www-data" the correct user to use in case nextcloud has been install on yunohost?
Would it be the correct command to do?
`sudo -u www-data php occ files:scan --all`
or should it bee adapted for nextcloud on yunohost? Change the user for something else than www-data?
And where should we do this command? It is said to run it at the root directory of Nextcloud on the server?
What would be the correct cd command to do to reach the "root directory of Nextcloud on the server" before running the scan command?
`cd /what/would/be/the/correct/path`

Thank you for your help?
Any one have tried it so far?

**Comment by Thatoo** [comment]
I have updated my question to make it clearer.
Thank you in advance for any guidance.

**Comment by rds13** [comment]
Hy,
I did use this occ command not long ago but you have to adapt it to

> sudo -u nextcloud php /var/www/nextcloud/occ files:scan --all

This command can be run from anywhere.

**Comment by Thatoo** [comment]
I've checked it and it works.

So, for whoever wants to install keeweb on nextcloud nowadays, he/she should do : 
```
cd /var/www/nextcloud/apps
sudo wget https://github.com/jhass/nextcloud-keeweb/releases/download/v0.5.0/keeweb-0.5.0.tar.gz
sudo tar xvf keeweb-0.5.0.tar.gz
sudo rm keeweb-0.5.0.tar.gz
sudo chown nextcloud:nextcloud -R keeweb
```
Then go into nextcloud and activate the app keeweb

Than back to terminal : 
`sudo nano /var/www/nextcloud/config/mimetypemapping.json`
add
```
{
  "kdbx": ["application/x-kdbx"]
}
```
CTL+x then yes then enter
and finally
```
sudo chown nextcloud:nextcloud mimetypemapping.json
sudo -u nextcloud php /var/www/nextcloud/occ files:scan --all
```
Enjoy keeweb!
