### ISSUE TITLE
/etc/cron.d/nextcloud may not exists and this breaks backup

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/nextcloud_ynh#167]
c.f. https://paste.yunohost.org/raw/bipinopaye

```
2019-02-24 00:13:02,505: DEBUG - 1691 + ynh_backup /etc/cron.d/nextcloud
[...]
2019-02-24 00:13:02,495: WARNING - 1687 Source path '/etc/cron.d/nextcloud' does not exist
```

**Comment by JimboJoe** [comment]
Super weird because it seems to be always created in [install](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/install#L229-L230) and [upgrade](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/upgrade#L295-L296)...

**Comment by alexAubin** [comment]
Meh yea I was thinking about an old instance but if it was added during the upgrade at the time it was introduced, shouldnt be any issue :/

**Comment by JimboJoe** [comment]
It happened again [here](https://forum.yunohost.org/t/nextcloud-erreur-502-et-mise-a-jour-impossible-apres-migration-yunohost-3-4-2-4/7204/15?u=jimbojoe)...
We could put up a dirty fix in the backup script, but that's not satisfying... Any other opinion on this @YunoHost-Apps/apps-group ?

**Comment by maniackcrudelis** [comment]
I recently introduce an option to ynh_backup for that kind of error
https://github.com/YunoHost/yunohost/blob/stretch-stable/data/helpers.d/filesystem#L19

**Comment by JimboJoe** [comment]
Yes, but what are relevant use cases? Here there is a problem somewhere that makes that file disappear... is there any other potential problem that could be hidden behind this...?

**Comment by maniackcrudelis** [comment]
Indeed, there's probably something else behind, or the user has removed the file himself.
But in any case, does that error should prevent an upgrade of the app ?

**Comment by alexAubin** [comment]
Similar issue here : https://forum.yunohost.org/t/probleme-mise-a-jour-nexcloud-depuis-passage-sous-strech/7501

with logrotate file this time

```
2019-03-27 17:01:01,320: DEBUG - 12656 + ynh_backup /etc/logrotate.d/nextcloud
2019-03-27 17:01:01,321: WARNING - 12657 Source path '/etc/logrotate.d/nextcloud' does not exist
[...]
2019-03-27 17:01:01,324: WARNING - 12659   nextcloud's script has encountered an error. Its execution was cancelled.
```

**Comment by tituspijean** [comment]
No news, good news, let's close.
