### ISSUE TITLE
using PHP7 instead of PHP5

### ISSUE THREAD

**Issue by jodumont** [YunoHost-Apps/nextcloud_ynh#173]
An easy way to improve the performance is
using PHP 7.x instead of [PHP 5](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/conf/nginx.conf#L70)

1. PHP5 is dead; officially not supported anymore
2. Last time Nextcloud mentioned PHP 5 was in the version [13](https://docs.nextcloud.com/server/13/admin_manual/installation/system_requirements.html)

**Comment by JimboJoe** [comment]
YunoHost has been providing PHP7 instead of PHP5 since version 3.0 (Debian Stretch). Some explicit mentions to php5 still remain in some apps, but a mechanism had been introduce in YunoHost to ensure compatibility with these apps (force use of PHP7).
