### ISSUE TITLE
NC Colabora office app fails to open documents

### ISSUE THREAD

**Issue by mikelpzm** [YunoHost-Apps/nextcloud_ynh#177]
When install the Colabora app and try to open a document, the following error is shown:

FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot declare class GuzzleHttp\Handler\CurlFactory, because the name is already in use in /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 15" while reading

**Comment by decentral1se** [comment]
Perhaps you can also ask for help over at:

> https://github.com/YunoHost-Apps/collabora_ynh/issues
