### ISSUE TITLE
Adding contacts doesn't work in chrome

### ISSUE THREAD

**Issue by AcolyteGeometry** [YunoHost-Apps/nextcloud_ynh#183]
In the NextCloud CardDAV (Contacts) adding new contacts is not working in chrome. I have confirmed that it is working in evolution, but when attempting in chrome I click on the button to add contact and nothing happens.

**Comment by JimboJoe** [comment]
Is the problem still occurring? Did you get to try with another browser?

**Comment by alexAubin** [comment]
Closing because super old issue, lack of feedback
