### ISSUE TITLE
Fresh Install: "not enough disk space"

### ISSUE THREAD

**Issue by aslmx** [YunoHost-Apps/nextcloud_ynh#187]
hi there,

i just tried yunohost again after having abandoned my old install some time ago. Looks even better now.

Of course i tried nextcloud again! While it was almost painless last time... this time i have the following issue after a pretty much straight forward fresh install:

I can not upload files via the web interface!

neither the file chooser nor the drag&drop will let me upload files.

I can create folders. I Can create text files via the WebUI. I can even sync with the desktop client and sync my files up... 

Just the webui upload won't work.

I fixed the nginx php.ini path problem already. One thing which remains in the Settings overview is this:

  | Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) at Unknown#0
-- | --

Not sure if this is related. I tried to enable OPCache but i didn't succeed. 

Not sure what config files you might want to check... 

I uncommented these lines in the pool.d/nextcloud.conf file (php-fpm)
`
; Pass environment variables like LD_LIBRARY_PATH. All $VARIABLEs are taken from
; the current environment.
; Default Value: clean env
env[HOSTNAME] = $HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp
`

cat /etc/nginx/conf.d/cloud.mydomain.tld.conf 

`
server {
    listen 80;
    listen [::]:80;
    server_name cloud.mydomain.tld;

    access_by_lua_file /usr/share/ssowat/access.lua;

    include /etc/nginx/conf.d/cloud.mydomain.tld.d/*.conf;

    location /yunohost/admin {
        return 301 https://$http_host$request_uri;
    }

    location /.well-known/autoconfig/mail/ {
        alias /var/www/.well-known/cloud.mydomain.tld/autoconfig/mail/;
    }

    access_log /var/log/nginx/cloud.mydomain.tld-access.log;
    error_log /var/log/nginx/cloud.mydomain.tld-error.log;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name cloud.mydomain.tld;

    ssl_certificate /etc/yunohost/certs/cloud.mydomain.tld/crt.pem;
    ssl_certificate_key /etc/yunohost/certs/cloud.mydomain.tld/key.pem;
    ssl_session_timeout 5m;
    ssl_session_cache shared:SSL:50m;

    # As suggested by Mozilla : https://wiki.mozilla.org/Security/Server_Side_TLS and https://en.wikipedia.org/wiki/Curve25519
    ssl_ecdh_curve secp521r1:secp384r1:prime256v1;
    ssl_prefer_server_ciphers on;

    # Ciphers with intermediate compatibility
    # https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=nginx-1.6.2&openssl=1.0.1t&hsts=yes&profile=intermediate
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';

    # Ciphers with modern compatibility
    # https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=nginx-1.6.2&openssl=1.0.1t&hsts=yes&profile=modern
    # Uncomment the following to use modern ciphers, but remove compatibility with some old clients (android < 5.0, Internet Explorer < 10, ...)
    #ssl_protocols TLSv1.2;
    #ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';

    # Uncomment the following directive after DH generation
    # > openssl dhparam -out /etc/ssl/private/dh2048.pem -outform PEM -2 2048
    #ssl_dhparam /etc/ssl/private/dh2048.pem;

    # Follows the Web Security Directives from the Mozilla Dev Lab and the Mozilla Obervatory + Partners
    # https://wiki.mozilla.org/Security/Guidelines/Web_Security
    # https://observatory.mozilla.org/ 
    more_set_headers "Strict-Transport-Security : max-age=63072000; includeSubDomains; preload"; 
    more_set_headers "Content-Security-Policy : upgrade-insecure-requests";
    more_set_headers "Content-Security-Policy-Report-Only : default-src https: data: 'unsafe-inline' 'unsafe-eval'";
    more_set_headers "X-Content-Type-Options : nosniff";
    more_set_headers "X-XSS-Protection : 1; mode=block";
    more_set_headers "X-Download-Options : noopen";
    more_set_headers "X-Permitted-Cross-Domain-Policies : none";
    more_set_headers "X-Frame-Options : SAMEORIGIN";

    
    # OCSP settings
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate /etc/yunohost/certs/cloud.mydomain.tld/crt.pem;
    resolver 127.0.0.1 127.0.1.1 valid=300s;
    resolver_timeout 5s;

    fastcgi_param PATH_INFO $fastcgi_path_info;    

    access_by_lua_file /usr/share/ssowat/access.lua;

    include /etc/nginx/conf.d/cloud.mydomain.tld.d/*.conf;

    include /etc/nginx/conf.d/yunohost_admin.conf.inc;
    include /etc/nginx/conf.d/yunohost_api.conf.inc;

    access_log /var/log/nginx/cloud.mydomain.tld-access.log;
    error_log /var/log/nginx/cloud.mydomain.tld-error.log;
}

`

**Comment by aslmx** [comment]
This seems to be fixed by https://github.com/YunoHost-Apps/nextcloud_ynh/pull/188

You can run

sudo yunohost app upgrade nextcloud -u https://github.com/YunoHost-Apps/nextcloud_ynh/tree/fix_various_warnings --debug

Thanks!

**Comment by kay0u** [comment]
Thank your for your issue report and your feedback! I leave this issue open until the merge of #188

**Comment by zamentur** [comment]
I close because it has been merged and released...
