### ISSUE TITLE
Install from backup doesn't work

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/nextcloud_ynh#190]
Nextcloud 15.0.5.
After a fresh Yunohost 3.4.2.4, I tried to install a complete backup I made a few days before (on the same Yunohost version).
Other applications worked fine after backup re-install (IHateMoney, Wallabag, Rainloop, PhpMyAdmin), but even without any install error, Nextcloud was unable to work, and displayed:
"Internal Server Error
The server encountered an internal error and was unable to complete your request"
I tried many times. Same result.

The way I successed: fresh nextcloud installation, then upload the database from the backup to PhpMyAdmin, and the files to "/home/yunohost.app/nextcloud/data". (even if I still have a "private key" error)

**Comment by JimboJoe** [comment]
I had a try this morning (removing `/home/yunohost.app/nextcloud` after removing Nextcloud) and couldn't reproduce that issue... Any useful log on your side...?

**Comment by klorydryk** [comment]
Ok, I'll give a try on a VM as soon as possible
