### ISSUE TITLE
Environment variables access in PHP: PHP warning

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/nextcloud_ynh#191]
Nextcloud 15.0.5
Yunohost 3.4.2.4
"In the Admin view, I get a warning about PHP unable to access to env values:
PHP ne semble pas être configuré de manière à récupérer les valeurs des variables d’environnement. Le test de la commande getenv("PATH") retourne seulement une réponse vide. Veuillez consulter la documentation d'installation ↗pour savoir comment configurer PHP sur votre serveur, en particulier en cas d'utilisation de php-fpm."

If I remember, this kind of test were disabled in the previous packages of nextcloud_ynh, isn't it?

**Comment by kay0u** [comment]
Fixed by #188 (waiting to be merged)
