### ISSUE TITLE
Upgrade fails (13.x to 15.x)

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/nextcloud_ynh#197]
Upgrade from 13.x to the latest master version fails.

Upgrade to 14.x works. Then an upgrade to 15.x works. But the last one fails (15.0.5 I think), with this error:

>  DEBUG + find /home/yunohost.app/nextcloud/data/ -type f -print0                                                                       
 DEBUG + xargs -0 chmod 0640                                                                                                           
 DEBUG + ynh_exit_properly                                                                                                             
 WARNING chmod: opérande manquant après « 0640 »                                                                                       
 DEBUG + local exit_code=123                                                                                                           
 WARNING Saisissez « chmod --help » pour plus d'informations.
 DEBUG + '[' 123 -eq 0 ']'
 WARNING !!
 DEBUG + trap '' EXIT
 WARNING   nextcloud's script has encountered an error. Its execution was cancelled.

I tried with 15.0.7, same result.

And unfortunately I can't only upgrade to 14.x first, then try the other upgrade (it would already be an improvement).

**Comment by lapineige** [comment]
:up:

I tried on 2 different servers (ARM and x86), same result :(

**Comment by JimboJoe** [comment]
Hello,
I'm not sure to understand everything.
You state that the upgrade from 13 to 14 works, and then you say "And unfortunately I can't only upgrade to 14.x first, then try the other upgrade (it would already be an improvement).", what do you mean?

Could you please share the complete upgrade logs of each upgrade so that we could look further into it?

**Comment by lapineige** [comment]
I mean I can't do the whole upgrade process (13>14>15.0>15.x).
So I'm stuck in version 13.
Only 13>14 works fine. But I can't upgrade to 14.x only (while waiting for this issue to be solved).

Here is the log: https://privatebin.net/?7f99d345db4f5ca9#Ort9TmnRrYairIt2xsGXqJ/gWijCQEBMLyAk+MJc49A=

**Comment by JimboJoe** [comment]
Sorry, I still don't understand why upgrading to 14.x is not acceptable :blush: 

By the way, the log is incomplete (we only see the end of restoration); could you please share with `yunohost log` command?

**Comment by lapineige** [comment]
> Sorry, I still don't understand why upgrading to 14.x is not acceptable 😊

I would like to do it, but I can't ^^
The upgrade process doesn't allow me to stop at 14.
Maybe I should for this repo and make a branch for 14.

**Comment by lapineige** [comment]
Here is the issue:  `UnexpectedValueException: The files of the app "user_external" were not correctly replaced before running the update`

I'll try to disable the app first.

**Comment by JimboJoe** [comment]
Yep, you could clone the repo and checkout at version 14.
For your problem, see an analogous problem on the forum [here](https://forum.yunohost.org/t/update-de-nextcloud-impossible/7357/7)... so yes, disabling that app could help!

**Comment by lapineige** [comment]
Upgraded successfully to 15.0.0… then it fails with 15.0.5 fails with "Corrupt source" :(

> wget -nv -O app.tar.bz2 https://download.nextcloud.com/server/releases/nextcloud-15.0.5.tar.bz2
DEBUG - + local 'out=failed: Connection timed out.
WARNING - Corrupt source
DEBUG - failed: Network is unreachable.


I'll try again.

**Comment by lapineige** [comment]
And it's done !
I'm in 15.0.5.3 🎉 🙂
