### ISSUE TITLE
Social app - webfinger 403 access forbidden by rule

### ISSUE THREAD

**Issue by mediaformat** [YunoHost-Apps/nextcloud_ynh#198]
After installing the Social (ActivityPub) app, testing the webfinger, I am getting `403 Forbidden` 
`https://client.webfinger.net/lookup?resource=test%40nuage.example.com`

The NextCloud debug logs show that access forbidden by a rule :
`[error] 19566#19566: *13185 access forbidden by rule, server: nuage.example.com, request: "GET /.well-known/webfinger?resource=acct%3Atest%40nuage.example.com HTTP/1.1", host: "nuage.example.com"`

I've tried resetting the app: `occ social:reset`, `maintenance:update:htaccess`

Other info:
YunoHost is setup on host.example.com, and I've installed NextCloud on nuage.example.com

The redirect in nextcloud is the standard rule:
`  RewriteRule ^\.well-known/webfinger /public.php?service=webfinger [QSA,L]`

Maybe related: 
There is a `/` missing in the path : `htmlindex.php`
`[error] 19566#19566: *11261 open() "/usr/share/nginx/htmlindex.php/ynhtheme/custom_portal.js" failed (2: No such file or directory), server: nuage.example.com, request: "GET /ynhtheme/custom_portal.js HTTP/2.0", host: "nuage.example.com"`

**Comment by JimboJoe** [comment]
As YunoHost uses nginx, the `.htaccess` you refer to is not used (used by Apache, as far as I know).
So you need to check the nginx configuration file, which is `/etc/nginx/conf.d/yourdomain.d/nextcloud.conf` (it's overwritten at each app upgrade, though).

**Comment by lapineige** [comment]
In this file, I added `    # rewrite ^/.well-known/webfinger /public.php?service=webfinger last;` as indicated here, but I still don't see any effect.
(by the way, where is this `.well-known` file located ?

**Comment by mediaformat** [comment]
ok, yes I had an inkling it was nginx related, thanks for that path!

I uncommented the host-meta lines and added the webfinger redirect:
```
# The following 2 rules are only needed for the user_webfinger app.
# Uncomment it if you're planning to use this app.
  rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
  rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;
  rewrite ^/.well-known/webfinger /public.php?service=webfinger last; 
```

Still getting the access forbidden by rule error
`2019/05/06 20:21:08 [error] 1157#1157: *1547 access forbidden by rule, server: nuage.example.com, request: "GET /.well-known/webfinger?resource=acct%3Atest%40nuage.example.com HTTP/1.1", host: "nuage.example.com"`

If I access the url directly (no redirect), it works:
`nuage.example.com/public.php?service=webfinger&resource=acct%3Atest%40nuage.example.com`

**Comment by lapineige** [comment]
Same for me.

**Comment by JimboJoe** [comment]
Did you try to add a location/return 301 analogously to .well-known locations at the very beginning of the nginx conf? It seems to me that that locations starting with a "." are denied afterwards in the configuration file.

**Comment by lapineige** [comment]
Ok I found the issue.

Right now I have this : 
```
location = /.well-known/webfinger {
  return 301 https://$server_name/public.php?service=webfinger
}
```


But the correct URL is : `https://domain.tld/public.php?service=webfinger&resource=acct%3Apseudo%40domain.tld`

So I need to redirect to `https://domain.tld/public.php?service=webfinger` and rewrite the `?resource=acct%3Apseudo%40domain.tld` to `&resource=acct%3Apseudo%40domain.tld` and add this at end of the URL.

**Comment by lapineige** [comment]
Ok I found the solution: 
```
location = /.well-known/webfinger {
  rewrite ^ https://$server_name/public.php?service=webfinger&$1 last; # $1 will use the first parameter (?resource=…)
}
```

**Comment by mediaformat** [comment]
> Ok I found the solution:
>  $1 will use the first parameter (?resource=…)
OMG, of course!
Thank you
