### ISSUE TITLE
Upgrade is failing 

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/nextcloud_ynh#199]
Upgrade to last master version fails with this log:
>DEBUG + sudo -u nextcloud php occ --no-interaction --no-ansi files_external:option 12 enable_sharing true
 DEBUG + ynh_multimedia_addaccess nextcloud
 DEBUG + local user_name=nextcloud
 DEBUG + groupadd -f multimedia
 DEBUG + usermod -a -G multimedia nextcloud
 DEBUG + chown -R nextcloud: /var/www/nextcloud /home/yunohost.app/nextcloud/data
 DEBUG + xargs -0 chmod 0644
 DEBUG + find /var/www/nextcloud/ -type f -print0
 DEBUG + xargs -0 chmod 0755
 DEBUG + find /var/www/nextcloud/ -type d -print0
 DEBUG + find /home/yunohost.app/nextcloud/data/ -type f -print0
 DEBUG + xargs -0 chmod 0640
 DEBUG + ynh_exit_properly
 WARNING chmod: opérande manquant après « 0640 »
 DEBUG + local exit_code=123
 WARNING Saisissez « chmod --help » pour plus d'informations.
 DEBUG + '[' 123 -eq 0 ']'
 WARNING !!
 DEBUG + trap '' EXIT
 WARNING   nextcloud's script has encountered an error. Its execution was cancelled.
 DEBUG + set +eu
 WARNING !!
 DEBUG + echo -e '!!\n  nextcloud'\''s script has encountered an error. Its execution was cancelled.\n!!'
 WARNING Upgrade failed.

**Comment by JimboJoe** [comment]
Does the directory `/home/yunohost.app/nextcloud/data/` exist and is it empty...?

**Comment by lapineige** [comment]
Inded. I changed the data repository. Should I delete this one ?

**Comment by JimboJoe** [comment]
I suppose you changed the data directory in Nextcloud configuration. If so, the YunoHost package isn't adapted to that, and can only work if you use a link from the `/home/yunohost.app/nextcloud` directory to your custom directory (which I personnally do)... unless you make a PR :wink:

**Comment by lapineige** [comment]
Thanks a lot, that solved the issue :)
