### ISSUE TITLE
v 10.0.0

### ISSUE THREAD

**Issue by MarcusMoeller** [YunoHost-Apps/nextcloud_ynh#2]
Are you planning to upgrade the App to v 10.0.0?

**Comment by jeromelebleu** [comment]
For sure, as soon as I will have some free time to do it and make some tests! ;)

**Comment by jeromelebleu** [comment]
Done with https://github.com/YunoHost-Apps/nextcloud_ynh/commit/780d925e269cdc37ef4ab564ef1272e9c3c5f8ac, feel free to try it and give feedbacks, thanks!

**Comment by MarcusMoeller** [comment]
Thanks a lot. The only issue I have noticed is a 'Failed to perform action' error when trying to disable usage statistics.
![action](https://cloud.githubusercontent.com/assets/1267594/18053153/600839dc-6dfe-11e6-99b9-8071f6d0c962.png)

**Comment by jeromelebleu** [comment]
Yes, I've got the same issue but I didn't investigate. I'll have a look and open a new ticket as needed. Thanks for your feedbacks!
