### ISSUE TITLE
How does the SSO works ?

### ISSUE THREAD

**Issue by artonge** [YunoHost-Apps/nextcloud_ynh#202]
Hi,

I actually have no problem with this package.

I am trying replicate the SSO you've put into place for nextcloud but I can't understand how it is working.

There is this line in the nextcloud nginx config: `fastcgi_param REMOTE_USER $sso_remote_user;` that seems to do the job, but it does not work for me. Is there some nextcloud configuration variable that I should set ?

Thanks for your help.

**Comment by artonge** [comment]
Up,

Nobody really knows ?

**Comment by JimboJoe** [comment]
Hello,
At some point in the past, I investigated in Nextcloud source code to understand how/why SSO was working... but I never succeeded... :sweat_smile:

**Comment by artonge** [comment]
Damn magic !

I'll try to add some documentation on this repo if I ever find out.

Thanks for answering !

**Comment by artonge** [comment]
So, I finally had time to sit down ad investigate.

This package support SSO through HTTP Basic Auth setted by SSOwat. This means that [this `REMOTE_USER`](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/ff7590c44e029b14104beea6cc343742955eaba2/conf/nginx.conf#L73)  header is not useful.

The authentication is made at [this line](https://github.com/nextcloud/server/blob/22de685f546474890ff43bc7d68754afe9fbd6f1/lib/base.php#L1034) in the nextcloud code.

The credentials are setted [here](https://github.com/YunoHost/SSOwat/blob/0c55f38fda529c02ae3f350142619a09d646b593/helpers.lua#L395) by SSOwat

**Comment by JimboJoe** [comment]
Wow, thanks a lot for your work and precise answer! :heart_eyes:
