### ISSUE TITLE
Upgrade to Nextcloud 18

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/nextcloud_ynh#205]
Unfortunately, it requires PHP 7.1, which isn't the default version in current Debian... Shall we install this additional PHP version or wait for Buster porting...? :thinking:

**Comment by maniackcrudelis** [comment]
I'm not sure the experimental helper is stable enough yet.
And actually, I'm not using that helper myself, so I really don't know.

**Comment by bhdouglass** [comment]
Any update on this? I see a work in progress PR for upgrading to nextcloud 16. I want to try out the new nextcloud text editor but it doesn't seem to be available for v15.

**Comment by JimboJoe** [comment]
As stated in the PR, it's on hold due to the requirement of PHP 7.1, whereas PHP 7.0 is the default version in Debian Stretch. As a note, PHP version will be upgraded in Debian Buster, so the Nextcloud upgrade will be possible after the migration of YunoHost to Debian Buster.

**Comment by lapineige** [comment]
So if I understand well, Nextcloud 16 and newer versions are not coming to Yunohost until Debian Buster is out and supported (which means a quite long time). Correct ?

If we don't have a viable solution for php7.1, that would be merged to master (and then available for all), is it conceivable that a special branch is created, which adds php 7.1 supports (as other apps do, like Pixelfed for instance) for users that would like to upgrade anyway (at their own risks) ?

**Comment by JimboJoe** [comment]
Well, contributions are always welcome :wink:

**Comment by lapineige** [comment]
I'm absolutely not able to do it ^^  (@yalh76 ? :)

I'm wondering if such a solution could be implemented.

**Comment by yalh76** [comment]
@lapineige
If you have never tried you can’t say you are not able to do it.

So, read a lot, ask us if you have questions, and try it... it will be easy as you have an already packaged pass: nextcloud_ynh and another one using the php helper: pixelfed_ynh

Go and help yourself ;)

**Comment by bhdouglass** [comment]
Thanks for the info! Is there a place where I can follow/help the migration to debian buster? Also, have you considered running nextcloud in a docker container? Then it wouldn't matter which version of php ships with the system.

**Comment by lapineige** [comment]
I can rephrase it: I don't have the time to learn how to do it (properly) :(

**Comment by nath5394** [comment]
> Is there a place where I can follow/help the migration to debian buster? 

Here you can follow work, bugs, needs and progress about debian buster upgrade for Yunohost : https://github.com/YunoHost/issues/issues/1255 - poke @bhdouglass 

@lapineige  Ok, it is not a problem. I am in the same situation as you, so I wait. Maybe I'll try to help on the buster issue. If I can find time. 

Thanks to all yunohost contributors 👍

**Comment by lapineige** [comment]
>  I am in the same situation as you, so I wait.

Well, the only thing I can do is trying to find and propose another way to do it in the mean time - and Buster support is unlikely to happens soon, many Nextcloud version will be out until that moment.
But yeah, I can't do anything else :/

**Comment by supermamie** [comment]
Not a really interesting message, but still : NextCloud 17 is out :-)

**Comment by ahstro** [comment]
Anyone working on this, or Nextcloud 17? 😇

**Comment by jsonoctopus** [comment]
Nextcloud 15 will reach EOL 2019-12-19
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule
Would security bugs be backported after that day, or how did this project deal with similar situations in the past ? (Thanks a lot for Nextcloud in YunoHost, great to have it as a multimedia bridge for e.g. Ampache)

**Comment by lapineige** [comment]
For Nextcloud 17 : https://github.com/YunoHost-Apps/nextcloud_ynh/pull/229

I don't know how this works for Nextcloud (and I can't find any clear piece of information after a quick search… 🤔), but if that means no more security updates, I'd vote for at least a major announcement and testing phase (putting Nextcloud 17 in testing, or its own branch, I let you judge what's better) for people, even if Debian Buster is not supported yet.
Dealing with potential php issues of volunteers (knowing the risks to stay in NC 15 / try this version) seems better to me than leaving a package with security flaws, without any other option for all users.
(and it will help improving the package and maybe Yunohost, I guess ?)
And it takes time to merge a testing into the master, so the sooner…

By the way, I've already an Yunohost server running php 7.0, 7.2 and 7.3 without any apparent problems, since a few months.

**Comment by jsonoctopus** [comment]
> By the way, I've already an Yunohost server running php 7.0, 7.2 and 7.3 
> without any apparent problems, since a few months.

Here I noticed I have 7.3 as well as 7.0 
# /etc/apt/sources.list.d/sury.list 
deb https://packages.sury.org/php/ stretch main
Looking at the pool.d of php-fpm 7.3 the flarum app pulled it in. 
https://github.com/YunoHost-Apps/flarum_ynh

**Comment by alexAubin** [comment]
> a package with security flaws

There's a difference between "reaching end of life" and "being spontaneously full of dozens of critical security flaws nobody heard about before" ...

**Comment by lapineige** [comment]
That's right, but we would take the risk, and not be able to react (quickly) if something is discovered…

**Comment by MathieuDebit** [comment]
> By the way, I've already an Yunohost server running php 7.0, 7.2 and 7.3 without any apparent problems, since a few months.

@lapineige how did you manage to do that? Did you simply run the installation from https://github.com/YunoHost-Apps/nextcloud_ynh/pull/229/files ? Or do you have to install php 7.3 before?
Thank you 🙏

**Comment by lapineige** [comment]
I have Pixelfed installed, which installed php 7.3. I don't know for 7.2, maybe it was an anterior version of Pixelfed ? (ping @yalh76 ?)

**Comment by MathieuDebit** [comment]
Okay so there are already other YH apps that install a different version of PHP without issues.

It could be nice that someone write a sort of tutorial for this kind of experimental upgrades, for learning purpose and documentation, and allow any advanced user to better understand how YH and its apps works under the hood.

I'm really interested to try to install Nextcloud 17 but I'm not sure where to start and what kind of risks I could be exposed to...

Thanks anyway to all the contributors!

**Comment by lapineige** [comment]
Let's be cautious, I'm not sure there is no issues with those multiple php versions… My Pixelfed regular have some issues, that might be linked.

**Comment by ahstro** [comment]
There's a helper for installing different PHP versions called [ynh_install_php](https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_install_php/ynh_install_php), it's the one [being used](https://github.com/YunoHost-Apps/pixelfed_ynh/blob/a0d55b30030299ba63f039811690d1680a08423b/scripts/install#L65) in `pixelfed_ynh`.

**Comment by ashledombos** [comment]
For the fun, I installed a docker based Nextcloud 17 in a ynh server installed in a LXC container (non privileged, of course). Working well, especially since the redirect app simplifies the work I had to do with Træfik before :)

**Comment by Xananax** [comment]
@ashledombos I'd like to do that! I have three questions, if you have time to answer, or to point to resources:

1. How do you hook into the LDAP system?
2. How do you add a url (i.e, cloud.domain) without messing up with yunohost? Is there a way to use yunohost as a reverse proxy?
3. Do you use yunohost's Letsencrypt facilities, or do you handle SSL independently?

**Comment by nathanael-h** [comment]
> 2. How do you add a url (i.e, cloud.domain) without messing up with yunohost? Is there a way to use yunohost as a reverse proxy?

This is possible with this app : https://github.com/YunoHost-Apps/redirect_ynh ;)

**Comment by Xananax** [comment]
Oh excellent, thanks!

In the meantime, I've poked a bit at how the LDAP works, and it seems the important settings to make apps work with it are:
 
- ldap_base: `dc=yunohost,dc=org`
- ldap_base_groups: `ou=groups,dc=yunohost,dc=org`
- ldap_base_users: `ou=users,dc=yunohost,dc=org`
- ldap_cache_ttl: `600`
- ldap_configuration_active: `1`
- ldap_display_name: `displayname`
- ldap_email_attr: `mail`
- ldap_expert_username_attr: `uid`
- ldap_group_display_name: `cn`
- ldap_group_filter: `objectClass=posixGroup`
- ldap_group_filter_mode: `0`
- ldap_groupfilter_objectclass: `posixGroup`
- ldap_host: `localhost`
- ldap_login_filter: `(&(|(objectclass=posixAccount))(uid=%uid))`
- ldap_login_filter_mode: `0`
- ldap_port: `389`
- ldap_quota_attr: `userquota`
- ldap_tls: `0`
- ldap_user_display_name: `cn`
- ldap_user_filter_mode: `0`
- ldap_userfilter_objectclass: `posixAccount`
- ldap_userlist_filter: `objectclass=posixAccount`

(found in the [config.json](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/testing/conf/config.json))

Additionally, these attributes from the wordpress plugin might be interesting for other apps:

- LDAP Version: `3`
- first name: `givenname`
- Last name: `sn`
- website: `wwwhomepage`

As for SSL, I guess as long as the domain is registered with yunohost, the letsencrypt bot should take care of it.

I'll take this for a spin soon.

**Comment by gnouts** [comment]
Hi,
I just saw master is now at v18. How did you handle the PHP nightmare ? 
I'm a bit nervous about that upgrade ^^

**Comment by lapineige** [comment]
I can't really anwser for PHP, sorry.
For the rest, I upgraded 2 servers (an x86 VPS and a Raspberry Pi) without any issue.
If you're unsure about it (it's understandable :), or just as a good practice: make some backups (critical apps and system and maybe all apps), and download them to your computer/another server/whatever-but-a-different-computer. Then if something very bad happens (if Yunohost automatic backup fails to restore, …), you will have a save backup.
Also you can wait a few days/weeks for other people to upgrade and maybe reports issues (let's hope everything will be fine :), and for a fix if needed.

---

Solved by https://github.com/YunoHost-Apps/nextcloud_ynh/pull/260, I guess we can close this issue ?
