### ISSUE TITLE
Zend OPcache error : does it work ?

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/nextcloud_ynh#209]
I noticed this in the logs:
`Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) at Unknown#0`

Which appears very frequently.

But `/etc/php/7.0/fpm/pool.d/nextcloud.conf` enable the OPcache… what's going on ?

**Comment by gueulderack** [comment]
To avoid this, you can comment the line `php_value[opcache.enable]=1` in the file `/etc/php/7.0/fpm/pool.d/nextcloud.conf`

**Comment by lapineige** [comment]
But it will remove the cache ?

**Comment by gueulderack** [comment]
No, it is already enable elsewhere (I don't remember where).

**Comment by JimboJoe** [comment]
Last time I tried, it showed as not activated in Nextcloud administration panel... That's why I'm a little puzzled about these warnings... :thinking:

**Comment by gueulderack** [comment]
I did it this morning on my instance. Since that, I didn't have any warning or error message in my logs.

**Comment by JimboJoe** [comment]
Did you check the Nextcloud administration panel?

**Comment by gueulderack** [comment]
yes. And I have nothing.

**Comment by isAAAc** [comment]
@lapineige : was the error coming using sync with thunderbird ?

**Comment by lapineige** [comment]
No, I'm not syncing it (but I was in the past, for the calendar).
