### ISSUE TITLE
Installation Fail

### ISSUE THREAD

**Issue by raphgilles** [YunoHost-Apps/nextcloud_ynh#210]
Hello,

I can't install Nextcloud on my server. I don't know why :
https://paste.yunohost.org/raw/ricuguwuyu

Thank you !

**Comment by MothGirlMusic** [comment]
The error is clear..
```
2019-05-31 17:24:15,444: DEBUG - PHP module zip not installed.
2019-05-31 17:24:15,444: WARNING - Unable to install Nextcloud
```
but i'm having the same error on my system as well. php7.3-zip is infact installed on my yunohost which is uptodate and all.. bu i still have this exact same error.

**Comment by maniackcrudelis** [comment]
php-zip is part of the dependencies. But wasn't installed anyway.
What's gives you `ls -alh /etc/alternatives/php` ?

**Comment by MothGirlMusic** [comment]
i just figured it out. php-zip WAS installed. however, this installation wants php7.0-zip and php7.3-zip was installed. whoever wrote the script did so a bit vaguely.

**Comment by MothGirlMusic** [comment]
being very clear, running this command, rebooting, and trying again to reinstall worked.
```
apt install php7.0-zip
```
and I don't know why it uses a different PHP than the system. [i'm using a new install of YunoHost with only WordPress and WeeKan installed.. which are both "official" apps so I doubt they'd be the ones causing PHP weirdness. but please correct me if I'm wrong. but it could also be maybe one gets installed and then another is in the newest updates or something. my install iso is a few months old and I don't know any of the changelogs.] having tested this out on my dev server i keep fresh, I can say the same issue persists on my heavily used and modified production system as well.. and the same "cure" is what fixes it... now I'm happily running NextCloud without issue. hopefully, this is clear and helpful for anyone else having the same issue.

**Comment by maniackcrudelis** [comment]
> whoever wrote the script did so a bit vaguely.

The script implies that the default php version is 7.0
So that my question,
What's gives you `ls -alh /etc/alternatives/php` ?

**Comment by MothGirlMusic** [comment]
root@mothnet:~# ls -alh /etc/alternatives/php
lrwxrwxrwx 1 root root 15 Mar 24 13:22 /etc/alternatives/php -> /usr/bin/php7.0

**Comment by maniackcrudelis** [comment]
Hum... Your install of php7.0-zip may have fixed your php default version.
Can you try `dpkg-query -W php-zip`

The problem is that many apps were (and still are) installing php version other than 7.0 and broke YunoHost. Even when the app is removed.

**Comment by MothGirlMusic** [comment]
```
root@mothnet:~# dpkg-query -W php-zip
php-zip	1:7.0+49
```
i guess maybe it did fix it. good to know for other people. or even just php7.0-zip in the script just to "automatically fix it for others" since it seems to not be the first or last time somone's had this issue by looking at the open issues on here

**Comment by raphgilles** [comment]
Ok. That was just php-zip. I missed the line. Thank you ! 😅
