### ISSUE TITLE
php-zip was missing (solution + question)

### ISSUE THREAD

**Issue by jodumont** [YunoHost-Apps/nextcloud_ynh#211]
For an obscur reason 

I was unable to install nextcloud because php-zip was missing (even if it is declare in the [common file](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/testing/scripts/_common.sh#L6))

```
2019-06-15 07:37:10,952: DEBUG - PHP module zip not installed.
2019-06-15 07:37:10,952: WARNING - Unable to install Nextcloud
```

I was able to fix this by installing php7.0-zip

on my system php-zip refered to php7.3-zip
which is refered in /etc/apt/sources.list.d/php7.list
which based on date was declared by kimai2

_the weird part is I tried to install nextcloud before kimai without success but I might had another issue which I didnt dig in._

1. Question, do my solution is future proof or I must remove Kimai and php7.list  than reinstall nextcloud ?

2. Should I open an issue to Kimai app and ask to lower down the priority of php7.list ?

**Comment by maniackcrudelis** [comment]
Open an issue on kimai package repo to ask to handle properly php versions.
We now have helpers to do that properly and not messed up people servers.
