### ISSUE TITLE
Clients can't find carddav and caldav service after last update

### ISSUE THREAD

**Issue by tuxmouraille** [YunoHost-Apps/nextcloud_ynh#215]
Hello,
After the last Nextcloud's update any of my carddav/caldav client can find services.

I tried on Android with Caldav Sync/Card Sync, OpenSync (fork of DavDroid) and DavDroid, on Thunderbird with TBSync.

Nextcloud is the only carddav/caldav provider on my server.
I diffed my nextcloud nginx configuration file and the file in the repository, and this lines wasn't in my file.

location = /.well-known/carddav {
  return 301 https://$server_name__PATH__/remote.php/dav;
}
location = /.well-known/caldav {
  return 301 https://$server_name__PATH__/remote.php/dav;
}

After added this lines, TBSync can again find services, but not my Android clients.

I made a test with a demo instance from nextcloud website with OpenSync and it works. The demo was a 16.

Is there a solution without reinstallation Nextcloud?

Regards

**Comment by tuxmouraille** [comment]
I tried with OpenSync et Caldav Sync without using SSL for the server URL, and now it works.
But, not for the Android Nextcloud client.

I found in the logs of OpenSync and Caldav Sync, errors about SSL hand check. 

I thing there is problems with the Nextcloud configuration with SSL on my instance.

**Comment by tuxmouraille** [comment]
Hello, 
It is not really solved but I know why I had my problems. There is two things.

First, the last update of Nextcloud removed the lines above for cal/carddav well-known on /etc/nginx/conf.d/domain.tld.d/nextcloud.conf

location = /.well-known/carddav {
return 301 https://$server_name__PATH__/remote.php/dav;
}
location = /.well-known/caldav {
return 301 https://$server_name__PATH__/remote.php/dav;
}


Second, one of the last update of Yunohost remove support for SSL handshake with Android devices before Android 5, mine is 4.2.2.


Solutions:
1) I had the missing lines, then I can again connect to Nextcloud from recent DAV client, here TabSync
2) I configured my Android's Cal/CardDAV client (OpenSync) to use only http. But I can't use Nextcloud client because it forces https.

Regards

**Comment by zamentur** [comment]
Those lines about cardav are in current and future nginx config.

About the point 2, maybe there is a yunohost settings to force the use of a old https cypher.

I close this because not relevant with this package.
