### ISSUE TITLE
login logout one way only ?

### ISSUE THREAD

**Issue by EBII** [YunoHost-Apps/nextcloud_ynh#222]
Hello great job thanks

i install nextcloud on yunh 
after logout on admin interface or user interface We still auth in nextcloud 
and we can logout in nextcloud !
if we stay user login (se deconecter) in nextcloud stay connected to all 

so login in portal ok for both sso and nextcloud but need to logout portal and after logout nexcloud to be logged out nextcloud 

regards

**Comment by zamentur** [comment]
Duplicated of https://github.com/YunoHost-Apps/nextcloud_ynh/issues/19
