### ISSUE TITLE
Unable to upgrade due to fail2ban

### ISSUE THREAD

**Issue by gnouts** [YunoHost-Apps/nextcloud_ynh#226]
I was under version 15.0.7 and run an app upgrade.

Nextcloud failed to upgrade to 15.0.11, due to fail2ban :
```
fail2ban-client[29346]: ERROR  NOK: ('database disk image is malformed',)
...
usr/share/yunohost/helpers.d/logging: ligne 90: args_array : variable en lecture seule
```
Full log here : https://paste.yunohost.org/raw/otewahakar

Now Nextcloud tells me I'm under version 15.0.10 (wtf?)

---
Also, I had a notification message on nextcloud telling me that some of my shared links were deleted. Though everything seems ok. And this issue only affects version prior to 15.
https://nextcloud.com/security/advisory/?id=NC-SA-2019-003

**Comment by chiajlingvoj** [comment]
I have a similar issue, although Nextcloud says it's updated to 15.0.11 (from within Nextcloud itself)

**Comment by gnouts** [comment]
FTR, I had a similar issue during a synapse upgrade months ago (which I forgot, duh). Dumping and restoring fail2ban database seems to be the proper fix.
Though I don't know what caused this issue... :/ 
(fr) https://forum.yunohost.org/t/maj-synapse-0-99-en-echec/7411/8
(en) https://support.plesk.com/hc/en-us/articles/213370689
