### ISSUE TITLE
social app - domain confusion

### ISSUE THREAD

**Issue by mediaformat** [YunoHost-Apps/nextcloud_ynh#227]
I've installed Yunohost at app.example.com, and nextcloud at cloud.example.com
I created user@cloud.example.com but in the social app the user shows up as user@app.example.com
Not sure why, or how to fix!

**Comment by pintman** [comment]
I have the same problem. I would suggest to use the adress user@nexctcloud.example.com instead of user@yunohost.example.com for fediverse profile. Other apps like friendica or mastodon can do the same.

I would further consider this a bug since the social extension of nextcloud is currently not working in the current setup.

**Comment by mediaformat** [comment]
@pintman To get the social app working the nginx .conf file must be modified (it's overwritten at each app upgrade, though).
Look here
`/etc/nginx/conf.d/yourdomain.d/nextcloud.conf `

Add this:
```
location = /.well-known/webfinger {
  rewrite ^ https://$server_name/public.php?service=webfinger&$1 last; 
}
```
#198

**Comment by mediaformat** [comment]
Looking over this again, I wonder if `$server_name` is referring to the yunohost URL instead of the Nextcloud URL?

**Comment by mediaformat** [comment]
after running `occ social:reset`
There is a prompt to configure the base address of the cloud, it was incorrectly set to yunohost.example.com

**Comment by mediaformat** [comment]
I tried a fresh install on a new domain, and the problem seems to have been solved.
https://github.com/nextcloud/social/issues/995

**Comment by mediaformat** [comment]
Reminder, after updating Nextcloud.

Reset NGINX:
```
location = /.well-known/webfinger {
  rewrite ^ https://$server_name/public.php?service=webfinger&$1 last; 
}
```
Reset social app address:
`~# sudo -u nextcloud /var/www/nextcloud/occ config:app:set --value 'example.net' social social_address`

**Comment by Thatoo** [comment]
Is this still true or the

`  location = /.well-known/webfinger     { return 301 /index.php$uri; }`

is fine?

After updating nextcloud, should we still reset social app address:
`~# sudo -u nextcloud /var/www/nextcloud/occ config:app:set --value 'example.net' social social_address`
