### ISSUE TITLE
Upgrade from 11.0.1 to 11.0.2

### ISSUE THREAD

**Issue by solarus0** [YunoHost-Apps/nextcloud_ynh#23]
Hello there.

I’ve installed Nextcloud on my Yunohost instance. The installed version is the 11.0.1.
Now that the 11.0.2 is out, there is no update avaible in the Yunohost Admin.

Is there a way to update without deleting and reinstalling the application ?
Thanks for your help.

**Comment by JimboJoe** [comment]
Hello @solarus0, the 11.0.2 update will be available via the Yunohost Admin in 2 days. Hence you won't have to reinstall the application.

**Comment by solarus0** [comment]
That’s perfect. Thank you.

**Comment by JimboJoe** [comment]
11.0.2 package just published.
