### ISSUE TITLE
Nginx-php security fix

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/nextcloud_ynh#236]
"Urgent security issue in NGINX/php-fpm"
https://nextcloud.com/blog/urgent-security-issue-in-nginx-php-fpm/

The nginx configuration file needs to be updated ASAP.

**Comment by frju365** [comment]
Well, normally the best would be to upgrade to buster and add a security alert on the forum to every packager and perhaps every users.

**Comment by lapineige** [comment]
Stretch is likely to have an update with a security fix too (it's still maintained).


+1 for the security alert, for the users at least.

**Comment by fflorent** [comment]
Can it lower security risks to move nextcloud URL to protected URLs in /etc/ssowat/conf.json by chance? I mean as a quick fix until a proper one is provided by Debian in oldstable.

**Comment by alexAubin** [comment]
Yeah I think it can be a workaround, as the request will be going through SSOwat before reaching PHP-fpm

**Comment by fflorent** [comment]
Thanks!

**Comment by lapineige** [comment]
#237
