### ISSUE TITLE
This content failed to load

### ISSUE THREAD

**Issue by sy6sy2** [YunoHost-Apps/nextcloud_ynh#242]
Hi,
My nextcloud install not works after a fresh reinstall.
When I go to my nextcloud home page I get a` This content failed to load.` pop up then the page refresh automatically every 5 seconds.

Nextcloud is installed on a root subdomain.

Thank you.

Edit: Install debug log https://paste.yunohost.org/cokumiruba.sql

**Comment by SylvainCecchetto** [comment]
I was able to identify the problem, by installing Nextcloud not on a root path everything is ok.
