### ISSUE TITLE
next cloud going to index.php/index.php instead of directly to index.php…somethings messed up

### ISSUE THREAD

**Issue by Mrs-Feathers** [YunoHost-Apps/nextcloud_ynh#244]
hey. when i go to cloud.mothnet.xyz it goes to cloud.mothnet.xyz/index.php/index.php/login for some weird reason. the page is broken.. and i have to take away the extra index.php for it to show the real login. beyond that, logging in goes to double index.php which breaks i... even fixing it it shows the GUI but says it has an error and need to reload and does so over and over. its completely unusable but i dont know how or why its doubling he index.php

**Comment by MothGirlMusic** [comment]
https://cloud.mothnet.xyz/ to see what i mean

**Comment by alexAubin** [comment]
Closing because super old issue, no idea what version of YunoHost / Nextcloud this is ..
