### ISSUE TITLE
Nextcloud  15.0.12~ynh1 broke yunohost !!!

### ISSUE THREAD

**Issue by thsfo** [YunoHost-Apps/nextcloud_ynh#245]
Install no soucy : https://paste.yunohost.org/raw/baginigoci
webinterface: ok
few second later:  server down...https://paste.yunohost.org/exesesuluc.vbs
uninstall nextcloud:  server back

**Comment by JimboJoe** [comment]
What do you mean by "server down"? What were the symptoms? Were services not running any more?
What do you want to point out in your second log file?

**Comment by thsfo** [comment]
Don't know why, it works fine now. I used the last nextcloud client... maybe older wasn't compatible ? 
Sorry for this issue.
