### ISSUE TITLE
Attempting to upgrade to version 15.0.13 fails

### ISSUE THREAD

**Issue by csolisr** [YunoHost-Apps/nextcloud_ynh#251]
When attempting to upgrade Nextcloud to the latest Yunohost version (15.0.13), the installation fails with no discernible error on its standard form. When running with `--debug` enabled, however, the following error is displayed:

    Doctrine\DBAL\Schema\SchemaException: The column 'uid_lower' on table 'oc_users' already exists.

Attempting to remove that SQL column in `oc_users` (as per [here](https://github.com/nextcloud/server/issues/13614)) let me continue the installation, but then a similar error happened with the table `oc_authtoken`, several times:

    Doctrine\DBAL\Schema\SchemaException: The column 'public_key' on table 'oc_authtoken' already exists.
    Doctrine\DBAL\Schema\SchemaException: The column 'private_key' on table 'oc_authtoken' already exists.

And so on and so forth. In the end I attempted to just truncate the `oc_authtoken` table entirely (since I didn't have time to run the upgrade process several times in a row, each attempt taking almost 5 minutes each), but that made the whole upgrade fail (and the current installation stopped working too), so I had to revert the table structure back to its original form. Is there any way to run the upgrade script in such a way that it ignores already existing columns in tables, so it can finish at all?

**Comment by csolisr** [comment]
So, I did what I had to and ran the upgrade once and over again, modifying column per column until the upgrade was finally successful. To any other people that end up in this situation, just go to phpMyAdmin, open the `nextcloud` database, and check the tables `oc_users`, `oc_authtoken` and `oc_share` dropping the following columns only:

````
ALTER TABLE `oc_users` DROP `uid_lower`;
ALTER TABLE `oc_authtoken` DROP `private_key`;
ALTER TABLE `oc_authtoken` DROP `public_key`;
ALTER TABLE `oc_authtoken` DROP `version`;
ALTER TABLE `oc_authtoken` DROP `password_invalid`;
ALTER TABLE `oc_share` DROP `note`;
ALTER TABLE `oc_share` DROP `hide_download`;
ALTER TABLE `oc_share` DROP `label`;
````

**Comment by tituspijean** [comment]
Closing, as the issue is stale and hopefully solved. Feel free to reopen if needed.
