### ISSUE TITLE
Update to Nextcloud 18

### ISSUE THREAD

**Issue by planecore** [YunoHost-Apps/nextcloud_ynh#252]
Nextcloud 18 is out with a lot of new features, while this package is not even on 16.
When will you update to version 18?

**Comment by JimboJoe** [comment]
Please read [here](https://github.com/YunoHost-Apps/nextcloud_ynh/issues/205#issuecomment-506472798).
The strategy at the moment is to wait for YunoHost migration to Debian Buster.

**Comment by zamentur** [comment]
I close this ticket and rename the other one
