### ISSUE TITLE
Update to testing/18.0.2 : OnlyOffice HealthcheckRequest on check error

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/nextcloud_ynh#265]
I updated an installation to branch testing/v18.0.2.
Installed Community Document Server (0.1.5)
Installed OnlyOffice (4.1.4)
Parameter are filled with : https://xxxxx.xxx/nextcloud/apps/documentserver_community/
CPU : Intel Core i7

Edition of document failed with a pop-up, and log say:
_HealthcheckRequest on check error: cURL error 28: Connection timed out after 60000 milliseconds_

Is there something to change in the network configuration?

**Comment by lapineige** [comment]
I've a slightly different problem, but at the same step: https://github.com/YunoHost-Apps/nextcloud_ynh/pull/260#issuecomment-601866617

**Comment by klorydryk** [comment]
Ok. So no news about it.
I update first message with CPU info.

**Comment by dmogle** [comment]
I'm having trouble with the Document Server as well. I've installed the document server app and the onlyoffice app, both seem to install just fine (no errors). I can create new office docs from the Nextcloud add file/folder menu. When I create a new office file (or try to edit an existing office file) I think I'm getting the same error as @lapineige (in English): "ONLYOFFICE cannot be reached. Please contact admin". I've gone through as many logs as I can, the only thing I can find is a 302 error in the nginx logs:

`xxx.xxx.xxx.xxx - me [29/Mar/2020:20:38:23 +0000] "GET /nextcloud/apps/documentserver_community/web-apps/apps/api/documents/api.js HTTP/2.0" 302 640 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"`

Not sure if it's the same problem, but seemed better to add on to this issue than to create a new one for now.

**Comment by lapineige** [comment]
Upstream bug : https://github.com/nextcloud/documentserver_community/issues/102

**Comment by lapineige** [comment]
#287

**Comment by yekibud** [comment]
Hm, maybe not?  The comments on that upstream bug are about docker + nas/unraid.  How about just upgrading to 18.04?  Works for me on my non-Yunohost instance.

**Comment by mr-gosh** [comment]
I had the same problem here - escpicially it worked in the beginning and stopped working in the last update of the documenserver_community package.

But - what I now recognized is that the URL of the document server was integrated via "http" and not via "https" - which lead to the error during forcing of redirecting everything to https in my traefik config.

So entering the https://... URL did the trick. Perhaps something like this could be integrated in the health check?

**Comment by yekibud** [comment]
@mr-gosh The document server is using `https` on my setup (YNH 3.7.1.1, NC 8.0.4/daily) and I'm still having this issue.

**Comment by yekibud** [comment]
Yay, figured this out for me.  Needed to add `index.php/` after the `nextcloud` path in the ONLYOFFICE document server setting, e.g. https://<myyunohostdomain>/nextcloud/**index.php**/apps/documentserver_community/

**Comment by klorydryk** [comment]
It works adding index.php in the path, thanks!

**Comment by lapineige** [comment]
That's great, thanks for the tip :tada: 
Let's close then ? :)

**Comment by klorydryk** [comment]
Shouldn't we close it when a fix will be provided in the configuration? Or can't we do anything in the ynh package?

**Comment by lapineige** [comment]
Well, if I understand well, there is nothing to fix, it's just the URL recommended in the official guide that is different with Yunohost ?

I documented that here: https://github.com/YunoHost-Apps/nextcloud_ynh/pull/278#issuecomment-615831533

**Comment by klorydryk** [comment]
But the url is automatically filled. You say we know that it doesn't work by default, and user should update the url by himself?

**Comment by lapineige** [comment]
It wasn't automatically filled for me :sweat_smile:
I'm not sure we can do anything about it on our side, and if it's Yunohost specific it won't be fixed in an upstream version.

**Comment by klorydryk** [comment]
Ok

**Comment by dmogle** [comment]
I'm not sure I could do it myself, but couldn't an nginx rule be written that would either redirect or rewrite `nextcloud/apps/documentserver_community/` to `nextcloud/index.php/apps/documentserver_community/`? It's a bit of kludge, but it would get the expected behavior working out of the box.

**Comment by lapineige** [comment]
I don't think it's a good idea, as it can change in the future and break stuff, and gives some unexpected behavior.
I'd more in favor of advertising this in the readme and in the forum, maybe in the documentation too. Then people searching for a way to configure it would be able to find it rather easily.
