### ISSUE TITLE
Upgrade to Nextcloud 18.0.3

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/nextcloud_ynh#267]
I know 18.0.2 just hit the stable branch, but 18.0.3 is already there with what seems like a security fix :
https://nextcloud.com/blog/update-18-0-3-and-17-0-5-out-update-soon/

Thanks a lot to all of you bringing us Nextcloud :heart:

**Comment by hermann-san** [comment]
How about setting up a bounty in order to support timely update releases?
https://www.bountysource.com/

**Comment by maniackcrudelis** [comment]
https://github.com/YunoHost-Apps/nextcloud_ynh/pull/274/commits/1f41e28254e293beb1d7a800370eeb852bafbf9e

**Comment by hermann-san** [comment]
@maniackcrudelis  thanks for your response, but unfortunately I don't know what it means.   My current installation is 18.0.2 (installed 10 days ago) and Yunohost doesn't have an upgrade available to 18.0.3, when I search for upgrades. 
Does it mean that JimboJoe is still working on the upgrade?

**Comment by maniackcrudelis** [comment]
The upgrade to 18.0.3 is currently in testing https://github.com/YunoHost-Apps/nextcloud_ynh/pull/272

**Comment by kay0u** [comment]
Fixed
