### ISSUE TITLE
Upgrade stuck at backing up the app

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/nextcloud_ynh#270]
Hello,

I tried to upgrade my nextcloud app, but i'm stuck at the step "backing-up the app (may take a while)" since more than one hour. Is "a while" supposed to be so long ?

**Comment by JimboJoe** [comment]
Depending on your hardware and your total amount of data: yes.

**Comment by stemy2** [comment]
> Depending on your hardware and your total amount of data: yes.

Actually, it wasn't. The backup finally failed so heavily that upgrade of the other apps have been cancelled too. [The install log](https://paste.yunohost.org/raw/zigusizoru)

**Comment by maniackcrudelis** [comment]
l 724
> Disk full

**Comment by stemy2** [comment]
Indeed, you were right.
