### ISSUE TITLE
Upgrade failed from v15 to v18.0.2

### ISSUE THREAD

**Issue by sant-sh** [YunoHost-Apps/nextcloud_ynh#275]
When I tried the upgrade on yunohost 3.6.x its falling to get the packages from source (sury.org)

Error: `2020-03-29 12:47:47,835: WARNING - E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.0/php7.0-common_7.0.33-26+0~20200320.33+debian9~1.gbp746b8e_armhf.deb  GnuTLS recv error (-110): The TLS connection was non-properly terminated.
2020-03-29 12:47:47,837: DEBUG - + ynh_die '--message=Unable to install dependencies'
2020-03-29 12:47:47,838: WARNING - E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
2020-03-29 12:47:47,839: DEBUG - + local legacy_args=mc`

Here is the full log:
https://paste.yunohost.org/cesexefeci.bash

Even rollback was failed and now I cant even use older version
<img width="425" alt="Screenshot 2020-03-29 at 5 39 16 PM" src="https://user-images.githubusercontent.com/9120889/77848854-55d9ad80-71e5-11ea-9068-9ef675daffd7.png">

**Comment by maniackcrudelis** [comment]
Did you retry a second time ?

**Comment by sant-sh** [comment]
@maniackcrudelis 
yeah after restart upgrade went smooth :)
