### ISSUE TITLE
Probleme email server NEXTCLOUD 18

### ISSUE THREAD

**Issue by yoyomimo** [YunoHost-Apps/nextcloud_ynh#276]
Hello I can't have accesss to the mail with NextCloud, but it's workwell with Sogo.

This is nexcloud log:

[mail] Error: Exception: Argument 3 passed to OCA\Mail\Controller\FoldersController::sync() must be of the type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 170 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\FoldersController {}, "sync")
1. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "sync", OC\AppFramework\ ... {}, {accountId: "7", ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "7", ... "})
3. /var/www/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {accountId: "7", ... "})
4. /var/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/mail/api/ ... c")
5. /var/www/nextcloud/index.php line 38
   OC::handleRequest()

GET /nc/apps/mail/api/accounts/7/folders/SU5CT1g%3D/sync?syncToken=VTEsVjE1ODU0ODQyOTQsSDE%3D
from 90.91.152.131 by test at 2020-03-29T14:14:22+00:00

**Comment by JimboJoe** [comment]
Hi,
That's working fine for me with an external IMAP account.
As it's most probably related to the mail app itself, you'd better head to https://github.com/nextcloud/mail

**Comment by yoyomimo** [comment]
I tried manually and it didn't work,

What do you want from me? What style of.log I need to share on the link you
sended to me?

**Comment by yoyomimo** [comment]
I want this stuff to be automatically for the other of my group

**Comment by JimboJoe** [comment]
I was advising you to raise a ticket directly on the bug tracker of the mail app [here](https://github.com/nextcloud/mail/issues).

**Comment by yoyomimo** [comment]
Thank you

**Comment by yoyomimo** [comment]
> 
> 
> I was advising you to raise a ticket directly on the bug tracker of the mail app [here](https://github.com/nextcloud/mail/issues).

I don't now because, when use only on domain it's work. :)

**Comment by yoyomimo** [comment]
Sorri DOUble: Go there: https://github.com/nextcloud/mail/issues/2847
