### ISSUE TITLE
Can't use "occ" commands

### ISSUE THREAD

**Issue by krisu5** [YunoHost-Apps/nextcloud_ynh#277]
Error about PHP version.

```
root@krisu:/home/admin# sudo -u nextcloud php /var/www/nextcloud/occ
This version of Nextcloud requires at least PHP 7.2<br/>You are currently running 7.0.33-26+0~20200320.33+debian9~1.gbp746b8e. Please update your PHP version.
```

Everything is up to date according the Yunohost's update checker.

**Comment by maniackcrudelis** [comment]
`sudo -u nextcloud php7.3 /var/www/nextcloud/occ`

**Comment by krisu5** [comment]
Okay, that works. Thanks!

**Comment by mediaformat** [comment]
I seem to recall this working before, perhaps its since the upgrade to buster

`sudo -u nextcloud php7.3 /var/www/netxcloud/occ social:reset`

> Sorry, user admin is not allowed to execute '/usr/bin/php7.3 occ social:reset' as nextcloud on example.com

**Comment by kay0u** [comment]
Run this as root should works:

`sudo -u nextcloud php7.3 /var/www/nextcloud/occ social:reset`
