### ISSUE TITLE
Can't upgrade from nextcloud 13

### ISSUE THREAD

**Issue by zamentur** [YunoHost-Apps/nextcloud_ynh#281]
testing with 18.0.2~ynh1

The issue is under nextcloud 15 PHP7.3 is not supported.

**Comment by zamentur** [comment]
Fixed by https://github.com/YunoHost-Apps/nextcloud_ynh/pull/282

**Comment by kay0u** [comment]
Fixed by https://github.com/YunoHost-Apps/nextcloud_ynh/pull/310
