### ISSUE TITLE
[buster] Python: key error during install 

### ISSUE THREAD

**Issue by adidal** [YunoHost-Apps/nextcloud_ynh#285]
Hello there, 

When attempting to install Nextcloud to the latest Yunohost-Unstable On Debian Buster, the installation fails with an error related to a missing key. It ran on a fresh install on a brand new VPS.

Here are the logs :  

[Yunohost Diagnostics](https://paste.yunohost.org/raw/ukugipowok)
[Nextcloud Installation logs](https://paste.yunohost.org/raw/wucewizida)

I used the following curl/install link to setup my whole instance : 
`curl https://raw.githubusercontent.com/YunoHost/install_script/buster-unstable/install_yunohost | bash`

**Comment by nin0-0** [comment]
https://paste.yunohost.org/raw/juqehasuge

Still this issue, I guess

**Comment by JimboJoe** [comment]
The PR has already been made by @maniackcrudelis here: https://github.com/YunoHost-Apps/nextcloud_ynh/pull/292 :wink:

**Comment by kay0u** [comment]
Fixed by https://github.com/YunoHost-Apps/nextcloud_ynh/pull/310
