### ISSUE TITLE
Does "Federated-Cloud-Sharing" work?

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/nextcloud_ynh#288]
I set up two yunohost nextcoud servers and try to share files by "Federated-Cloud-Sharing".

Somehow it does not work, or do i miss something?

I made all settings in the admin section... 
I can share a file to an user on a federated-Cloud
Under "Activity" the user on the federated-Cloud gets the messeage that a new file is shared like:

"You received a new remote share IMG_xyz.jpg from user@https://cloud.domain.tld/ "

but for the user it is not possible to see or open the file...
The file is also not listed under    
> Files > Shares >Shared with you 
> Files > Shares >Pending shares 

Do I miss something or is this a bug?

**Comment by lapineige** [comment]
I successfully did it in the past between 2 Nextcloud installed via Yunohost. So it's doable (I mean, it doesn't seem like a yunohost config issue), but I did not test between a Yunohost Nextcloud server and a classical one.

Did you accept the share in the notification ?

**Comment by rocky-III** [comment]
I just see:

"You received a new remote share IMG_xyz.jpg from user@https://cloud.domain.tld/ "

how can I accept the share?

**Comment by rocky-III** [comment]
under    /settings/user/sharing

the option 

"Accept user and groub shares by default"

is and was opt in

**Comment by lapineige** [comment]
> how can I accept the share?

It is supposed to show 2 buttons: Accept and Decline.

But maybe this option:
>"Accept user and groub shares by default"

Remove these buttons as it is supposed to be accepted.

I've no clue, sorry.

**Comment by rocky-III** [comment]
YES IT DOES WORK...
and your were right... a remode share has to accepted in order to see the file...
you have to click on the clock simbol which you finde an the right top corner

**Comment by lapineige** [comment]
Indeed. I'm sorry, I didn't explain it well enough.
