### ISSUE TITLE
Web Admin still shows php7.0 logs

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/nextcloud_ynh#290]
In the web admin, the logs still show php7.0 logs and not php7.3.

**Comment by alexAubin** [comment]
Can you elaborate which page of the webadmin exactly ?

**Comment by lapineige** [comment]
If I remember well: Apps -> Nextcloud -> Logs, something like that.

**Comment by alexAubin** [comment]
@lapineige : if you refer to the "Debug information about this app" at the bottom of the app page, it's really irrelevant and going to be removed in 3.8, no need to care about this page

**Comment by lapineige** [comment]
That's it. Ok, so let's close :)
