### ISSUE TITLE
Sources Download timeout

### ISSUE THREAD

**Issue by madmaxlamenace** [YunoHost-Apps/nextcloud_ynh#293]
I'm trying to make an update of nextcloud form 15.x to 18.0.3 and i have a suggestion is to download first all sources before update.... just because at now the script is downloading nextcloud sources at 25kb/s and it's not my connection because youtube works properly and when i test with wget sources it's very slow.
Ask for application process modification.

Get all sources first before upgrade.

Maybe be get all sources first before upgrade on all ynh_apps ?

**Comment by tituspijean** [comment]
Closing, as the issue is stale and hopefully solved. Feel free to reopen if needed.
