### ISSUE TITLE
The update from Nextcloud 18.0.2~ynh1 to 18.0.4~ynh1 failed and broke my Nextcloud installation

### ISSUE THREAD

**Issue by ci15399** [YunoHost-Apps/nextcloud_ynh#304]
The error was this: 
Error: Class 'OC\Security\CSP\ContentSecurityPolicyNonceManager' not found in /var/www/nextcloud/lib/private/Server.php:1151 

You can find the full log at  https://paste.yunohost.org/raw/nizulabawo 
I uninstalled the application and restored a previus backup 
Im running Debian 9.12 x86_64

Thanks

**Comment by tomdereub** [comment]
Hi,
It doesn't seem to be the same issue, tell me if it's better to open a new issue.
Update failed for me, and the restore failed too, so it has deleted nextcloud. I don't manage to restore, with this error:
`rm: impossible de supprimer '/var/www/nextcloud': Périphérique ou ressource occupé`
I actually can't delete /var/www/nextcloud.

Full log of upgrade : https://paste.yunohost.org/raw/ditayogaku

**Comment by alexAubin** [comment]
Closing because 4 years old and unlikely that we can reproduce it
