### ISSUE TITLE
It is unclear whether or not we can deactivate automatic `BACKUP_CORE_ONLY` while upgrading the app (and if we can, how)

### ISSUE THREAD

**Issue by pepeciseaux** [YunoHost-Apps/nextcloud_ynh#308]
In the [doc I found](https://yunohost.org/#/backup), precisely in French section named « _Configuration spécifique à certaines apps_ », I only learned about manual backups. And the page is about Ynh in general, not NC app specifically.

So I think it would be nice to say somewhere:
- how to do full backups of NC (is command line the only way?);
- whether it is possible to do so automatically when upgrading (and how);
- how to know _before_ upgrading whether automatic `BACKUP_CORE_ONLY` is activated or not.

Such info could be added for example in https://github.com/YunoHost/doc/blob/master/app_nextcloud.md I suppose.

Notes:
- This issue report comes aside with #307.
- I am totally new to reporting issues (initially I searched for a "support" forum but could not find one). So I am very open to criticism/advice on how to do it better.

**Comment by Jaxom99** [comment]
just in case (as nobody answered yet), the support category in the forum is there for you ;) https://forum.yunohost.org/. Your questions should be answered in the doc you pointed out, maybe an issue should be opened in that repo as well ? ?

**Comment by pepeciseaux** [comment]
Oh, I did not notice that Yunohost documentation had a specific repo. It makes senses to post this issue there, and to close this one.
