### ISSUE TITLE
internal Server Error

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/nextcloud_ynh#313]
after a reninall to NC 18.04. i can´t reacht the new installation anymore...
I get a page where it sais that there is a internal Sever Error and i should look into the logs...

here i see something like this:

`2020/06/16 13:49:42 [error] 23200#23200: *1844 open() "/usr/share/nginx/htmlindex.php/apps/files/undefined/img/notifications-new.svg" failed (2: No such file or directory), client: xx.xxx.xx.xx, server: cloud.domain.tld, request: "GET /apps/files/undefined/img/notifications-new.svg HTTP/2.0", host: "cloud.domain.tld,"`

if i try to creat in YH a new user I get this:

`PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_pdo_sqlite.dll' - /usr/lib/php/20151012/php_pdo_sqlite.dll: cannot open shared object file: No such file or directory in Unknown on line 0`

What does this mean?
Thanks for help

**Comment by rocky-III** [comment]
get the same error with 18.0.5~ynh1   :-(

![nc](https://user-images.githubusercontent.com/6730765/87736747-42c10c80-c7d9-11ea-94e8-40655c3e5340.jpg)

**Comment by kay0u** [comment]
Hi, and thank you for your report!

Do you have any interesting logs here `/home/yunohost.app/nextcloud/data/nextcloud.log`, when the server crash?

Can I have the results of this command:
```
sudo cat /var/www/nextcloud/config/config.php | grep dbtype
```

**Comment by rocky-III** [comment]
Hi kay0u,
thanks for your help!

```
root@my:~# sudo cat /var/www/nextcloud/config/config.php | grep dbtype                            
  'dbtype' => 'mysql',                                                                            
root@my:~#  
```                                                                                      

under /home/yunohost.app/nextcloud/data/nextcloud.log 
I see this: https://paste.yunohost.org/raw/peyihiriqi

**Comment by kay0u** [comment]
I can't see any problem from here.

Do you still have the error message or have you restored nextcloud to a working backup?

If you have this error, you can try this:
```
cd /var/www/nextcloud
sudo -u nextcloud php7.3 occ maintenance:repair
sudo systemctl restart php7.3-fpm
```

If it still doesn't work, can you install php7.3-sqlite and see if it solves the problem?

**Comment by rocky-III** [comment]
Thanks but this did not help.

so I installed php7.3-sqlite with
sudo apt-get install php7.3-sqlite
sudo service nginx restart

<?php phpinfo(); ?> sais under "Additional .ini files parsed " that

/etc/php/7.0/fpm/conf.d/20-pdo_sqlite.ini   is running

also that 

PHP Version 7.0.33-29+0~20200514.36+debian9~1.gbp126f6f    is running... 

is this corect?

**Comment by rocky-III** [comment]
in Jun i tried a reinstall of NC 18.04 after I had a morgen installation... since than I get this internal Sever Error message

**Comment by rocky-III** [comment]
`?php phpinfo(); ? `sais also:

PDO Driver for SQLite 3.x | enabled
-- | --
SQLite Library | 3.16.2

**Comment by kay0u** [comment]
Nextcloud use php7.3, not php7.0 (or php which should be php7.0 on stretch)

> ` ?php phpinfo(); ?` sais under "Additional .ini files parsed " that
> 
> /etc/php/7.0/fpm/conf.d/20-pdo_sqlite.ini is running
> 
> also that
> 
> `PHP Version 7.0.33-29+0~20200514.36+debian9~1.gbp126f6f` is running...
> 
> is this corect?

**Comment by jsonoctopus** [comment]
> `PHP Version 7.0.33-29+0~20200514.36+debian9~1.gbp126f6f` is running...
> 
> is this corect?

If you have more apps installed with Yunohost this is possible.
Some apps started to use newer php7 versions while others don't.

**Comment by rocky-III** [comment]
OK thanks

**Comment by rocky-III** [comment]
I get this Error Message after I try to login

**Comment by jsonoctopus** [comment]
> if i try to creat in YH a new user I get this:
> 
> `PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012
> /php_pdo_sqlite.dll' - /usr/lib/php/20151012/php_pdo_sqlite.dll: cannot open 
> shared object file: No such file or directory in Unknown on line 0`

That is peculiar. I have Nextcloud install with Yunohost but no sqlite in use, and the php modules in /usr/lib/php/ have dot so file extension, not dot dll
Dot dll I would expect on a Windows computer, or maybe with Linux and Mono C#.

**Comment by jsonoctopus** [comment]
> under /home/yunohost.app/nextcloud/data/nextcloud.log
> I see this: https://paste.yunohost.org/raw/peyihiriqi

- > "Exception":"RedisException","Message":"Connection refused"

Can you check with Yunohost admin the "services" section and see whether Redis and others is running fine ?

**Comment by rocky-III** [comment]
Ohh yes 
the services
`redis-server`
and
` rspamd`
faild  and I can´t start them... 
what could I try?

**Comment by rocky-III** [comment]
this are the logs: https://paste.yunohost.org/raw/ejevozarap

**Comment by kay0u** [comment]
```
cat /var/log/redis/redis-server.log
```

should give you more information :-)

**Comment by rocky-III** [comment]
```
root@my:~# cat /var/log/redis/redis-server.log                                                    
root@my:~# 
```                                                                                       
the file /var/log/redis/redis-server.log   is empty

**Comment by kay0u** [comment]
```
sudo journalctl -u redis
```
then?

**Comment by rocky-III** [comment]
```
root@my:~# sudo journalctl -u redis                                                               
-- No entries --                                                                                  
root@my:~#    
```

**Comment by rocky-III** [comment]
Does this make sence? 
```
root@my:~# systemctl start redis-server.service                                                   
Job for redis-server.service failed because the control process exited with error code.           
See "systemctl status redis-server.service" and "journalctl -xe" for details.                     
root@my:~# systemctl status redis-server.service                                                  
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)     
   Active: failed (Result: exit-code) since Fri 2020-07-17 13:59:59 UTC; 18s ago
     Docs: http://redis.io/documentation,                                                         
           man:redis-server(1)                                                                    
  Process: 32247 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exited, status=1/FAIL
  Process: 32244 ExecStartPre=/bin/run-parts --verbose /etc/redis/redis-server.pre-up.d (code=exit
                                                                                                  
Jul 17 13:59:59 my.xyz.tld systemd[1]: redis-server.service: Unit entered failed state.        
Jul 17 13:59:59 my.xyz.tld systemd[1]: redis-server.service: Failed with result 'exit-code'.   
Jul 17 13:59:59 my.xyz.tld systemd[1]: redis-server.service: Service hold-off time over, schedu
Jul 17 13:59:59 my.xyz.tld systemd[1]: Stopped Advanced key-value store.                       
Jul 17 13:59:59 my.xyz.tld systemd[1]: redis-server.service: Start request repeated too quickly
Jul 17 13:59:59 my.xyz.tld systemd[1]: Failed to start Advanced key-value store.
Jul 17 13:59:59 my.xyz.tld systemd[1]: redis-server.service: Unit entered failed state.        
Jul 17 13:59:59 my.xyz.tld systemd[1]: redis-server.service: Failed with result 'exit-code'.   
lines 1-16/16 (END)
root@my:~# journalctl -xe                                                                         
Jul 17 13:59:59 my.xyz.tld systemd[1]: redis-server.service: Failed with result 'exit-code'.
Jul 17 14:00:01 my.xyz.tld CRON[32253]: pam_unix(cron:session): session opened for user root by
Jul 17 14:00:01 my.xyz.tld CRON[32256]: (root) CMD (/usr/lib/armbian/armbian-truncate-logs)    
Jul 17 14:00:01 my.xyz.tld CRON[32252]: pam_unix(cron:session): session opened for user hubzill
Jul 17 14:00:01 my.xyz.tld CRON[32254]: pam_unix(cron:session): session opened for user nextclo
Jul 17 14:00:01 my.xyz.tld CRON[32258]: (hubzilla) CMD (cd /var/www/hubzilla; /usr/bin/php Zotl
Jul 17 14:00:01 my.xyz.tld CRON[32257]: (nextcloud) CMD (/usr/bin/php7.3 -f /var/www/nextcloud/
Jul 17 14:00:01 my.xyz.tld CRON[32253]: pam_unix(cron:session): session closed for user root   
Jul 17 14:00:04 my.xyz.tld CRON[32252]: pam_unix(cron:session): session closed for user hubzill
Jul 17 14:00:10 my.xyz.tld CRON[32254]: pam_unix(cron:session): session closed for user nextclo
Jul 17 14:00:12 my.xyz.tld postfix/smtpd[32283]: warning: hostname zg-0708a-151.stretchoid.com 
Jul 17 14:00:12 my.xyz.tld postfix/smtpd[32283]: connect from unknown[192.241.227.154]         
Jul 17 14:00:13 my.xyz.tld postfix/smtpd[32283]: warning: connect to Milter service inet:localh
Jul 17 14:00:13 my.xyz.tld postfix/smtpd[32283]: disconnect from unknown[192.241.227.154] ehlo=
Jul 17 14:00:58 my.xyz.tld wpa_supplicant[1380]: wlan0: Failed to initiate sched scan          
Jul 17 14:01:17 my.xyz.tld login[32414]: pam_unix(login:session): session opened for user root 
Jul 17 14:01:17 my.xyz.tld systemd[1]: Started Session 16964 of user root.                     
-- Subject: Unit session-16964.scope has finished start-up                                        
-- Defined-By: systemd                                                                            
-- Support: https://www.debian.org/support                                                        
--                                                                                                
-- Unit session-16964.scope has finished starting up.                                             
--                                                                                                
-- The start-up result is done.                                                                   
Jul 17 14:01:17 my.xyz.tld systemd-logind[718]: New session 16964 of user root.                
-- Subject: A new session 16964 has been created for user root                                    
-- Defined-By: systemd                                                                            
-- Support: https://www.debian.org/support                                                        
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat                      
--                                                                                                
-- A new session with the ID 16964 has been created for the user root.                            
--                                                                                                
-- The leading process of the session is 32414.                                                   
Jul 17 14:01:17 my.xyz.tld login[32553]: ROOT LOGIN  on '/dev/pts/1' from '127.0.0.1'          
lines 1670-1703/1703 (END)
```

**Comment by rocky-III** [comment]
Does this make sence to you?
https://paste.yunohost.org/raw/efuxenotun

**Comment by jsonoctopus** [comment]
> the file /var/log/redis/redis-server.log is empty

Can you comment out the Redis section in the Nextcloud config for the moment ?
In  /var/www/nextcloud/config/config.php

make it like this :
<
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'integrity.check.disabled' => true,
  'filelocking.enabled' => true,
//  'memcache.locking' => '\\OC\\Memcache\\Redis',
//  'redis' =>
//  array (
//    'host' => 'localhost',
//    'port' => '6379',
//    'timeout' => '0.0',
//    'password' => '',
//  ),
  'hashing_default_password' => true,
);
>

**Comment by rocky-III** [comment]
Coooool - YES
login does work after comment out the Redis section :-)

Now how can I fix Redis or can I leave it like this?

**Comment by kay0u** [comment]
Into the file `/etc/redis/redis.conf`, I have the line `logfile /var/log/redis/redis-server.log` can you confirm that you have the same one?

**Comment by rocky-III** [comment]
Yes this line does exist

**Comment by boistordu** [comment]
I'm going to create a new issue with link to this one because this is slightly related but with the newer update 18.0.7 and also the new update from nginx under buster. https://github.com/YunoHost-Apps/nextcloud_ynh/issues/329

**Comment by tituspijean** [comment]
Closing, as the issue is stale and hopefully solved. Feel free to reopen if needed.
