### ISSUE TITLE
Install fails in rpi4b buster 64bit

### ISSUE THREAD

**Issue by Yajo** [YunoHost-Apps/nextcloud_ynh#314]
I have a Raspberry Pi 4B with Raspberry Pi OS buster 64 bits (beta).

Installing nextcloud fails, I attach logs: https://paste.yunohost.org/raw/ubolafaris

**Comment by alexAubin** [comment]
Hmyup it's expected for now ... but the testing branch should now work in Buster

Can you try the install with : 

```
sudo yunohost app install https://github.com/YunoHost-Apps/nextcloud_ynh/tree/testing
```

**Comment by Yajo** [comment]
Thanks, that worked without problem.

**Comment by kay0u** [comment]
Fixed by https://github.com/YunoHost-Apps/nextcloud_ynh/pull/310
