### ISSUE TITLE
Connecting the NC server to the Desktop and Mobile apps

### ISSUE THREAD

**Issue by luckydays** [YunoHost-Apps/nextcloud_ynh#316]
Hey guys!

Really enjoying YunoHost and its flexibility here.

Do you know - how one actually could set the Nextcloud YunoHost's app in the Nextcloud Desktop App properly? 
https://mydomain.com/nextcloud doesn't work, since it got redirected to YunoHost's SSO - https://mydomain.com/yunohost/sso/ Therefore the Desktop app, for instance, then says:

![image](https://user-images.githubusercontent.com/10942891/85229568-b21a2b00-b3ea-11ea-89b4-2a48eaa2c83c.png)

**Comment by kay0u** [comment]
Hi!

With your browser, if you are not logged in with the SSO, can you reach the https://mydomain.com/nextcloud page?

If not, you should put your app in public with the permission system (add the group `visitors` to nextcloud permission).

**Comment by luckydays** [comment]
@kay0u That's awesome. Appeared to be some quick & easy.
Thank you very much for your time and care.
All the best wishes!
