### ISSUE TITLE
Spinning wheel on top of "files"

### ISSUE THREAD

**Issue by SirFerdek** [YunoHost-Apps/nextcloud_ynh#318]
See: https://help.nextcloud.com/t/spinning-wheel-on-top-of-files/81335/6

Reason: Nginx swaps out response with 404 error code which contains data to an empty 404 response.

Solution:
Delete one line in nextcloud nginx config file:

```
  # Errors pages
  error_page 403 /nextcloud/core/templates/403.php;
  # error_page 404 /nextcloud/core/templates/404.php;
```

After that, there will be data returned with 404 making the spinner disappear:
`{"ocs":{"meta":{"status":"failure","statuscode":404,"message":null},"data":{"message":"No workspace file found","folder":{"permissions":31}}}}`

**Yunohost 4.0 beta**

**Comment by jacen05** [comment]
Same thing on Yunohost 3.8.
The solution provided works as well, thanks.
