### ISSUE TITLE
Nextcloud Running outdated PHP

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/nextcloud_ynh#330]
Trying to use the OCC command and enable the facerecognition app:

```
root@DOMAIN:/var/www/nextcloud# sudo -u www-data php occ
This version of Nextcloud requires at least PHP 7.2<br/>You are currently running 7.0.33-30+0~20200807.37+debian10~1.gbp047872. Please update your PHP version.root@DOMAIN:/var/www/nextcloud# sudo -u www-data php occ face:setup
This version of Nextcloud requires at least PHP 7.2<br/>You are currently running 7.0.33-30+0~20200807.37+debian10~1.gbp047872. Please update your PHP version.root@DOMAIN:/var/www/nextcloud#
```

the ynh_app_version in /var/www for nextcloud is 7.3 however 🤔

**Comment by alexAubin** [comment]
Just replace "php" with "php7.3" in your command

**Comment by brimwats** [comment]
> Just replace "php" with "php7.3" in your command

Thanks for that!

I had this issue in another package as well, seems that I needed to tell my server to use 7.3 instead.

Do you know if sudo update-alternatives --set php /usr/bin/php7.3 makes it "stick" to 7.3?

Thanks o

**Comment by alexAubin** [comment]
Yup, using update-alternatives is the right way to go

That should automatically be done by the system once the php 7.0 packages disappear entirely, I believe, but on setups migrated from stretch there are some remaining dependencies (though they should go away after upgrading all php apps i believe)

**Comment by brimwats** [comment]
> Yup, using update-alternatives is the right way to go
> 
> That should automatically be done by the system once the php 7.0 packages disappear entirely, I believe, but on setups migrated from stretch there are some remaining dependencies (though they should go away after upgrading all php apps i believe)

thanks!

for some reason my server has PHP all the way back to 5! I wonder if I got that installed by accident. Should I remove 5.6?

**Comment by alexAubin** [comment]
Hmmmyeah you can try to run some "apt remove php5-whatever" and see what apt tells about it ... just be careful not to savagely hit "yes" too fast and read carefully what it says

**Comment by brimwats** [comment]
ahh it seems harmless, just mods:

root@DOMAIN:/etc/php# cd 5.6
root@DOMAIN:/etc/php/5.6# ls
mods-available
root@DOMAIN:/etc/php/5.6# cd mods-available/
root@DOMAIN:/etc/php/5.6/mods-available# ls
apcu.ini  igbinary.ini  imagick.ini  redis.ini  smbclient.ini

thanks for the heads up
