### ISSUE TITLE
Element (Riotchat) doesn't work

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/nextcloud_ynh#331]
Everything is explained in this thread : https://github.com/gary-kim/riotchat/issues/26

Installations works without problem, but when we go to the app, nothing appears.

Someone who tried to dig the issue said : 

> So, the issue seems to be that when loading Riot, the requests for the static resources are being redirected to the login page by Yunohost. I don't know why that is but it seems like it's happening to quite a few of the requests. I think this would be an upstream issue in Yunohost. Gonna try debugging a little further.

**Comment by kay0u** [comment]
Hi, this PR should explain the problem, and propose a solution: https://github.com/YunoHost-Apps/nextcloud_ynh/pull/332

**Comment by Thatoo** [comment]
A solution has been given to solve a problem that seemed to me to be similar (error with keeweb in nextcloud) The solution is here https://github.com/YunoHost-Apps/nextcloud_ynh/issues/317#issuecomment-702596438

However, even with this solution, Element is not working. So the problem is different, it might be indeed the one pointed by @kay0u . Did someone try to disable pretty url and tested Element in Nextcloud? Is it working?

**Comment by kay0u** [comment]
Should be fixed now
