### ISSUE TITLE
Upgrade to NC19 Fails

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/nextcloud_ynh#335]
Here are the logs: https://paste.yunohost.org/raw/irateyuyic

**Comment by Vitriia** [comment]
Hi
You need to disable OCR app and remove his folder (rm -rf /var/www/nextcloud/apps/ocr)

**Comment by brimwats** [comment]
you're absolutely right! great catch and I can confirm that this fixes the bug
