### ISSUE TITLE
cannot run occ as nextcloud user

### ISSUE THREAD

**Issue by sharicov** [YunoHost-Apps/nextcloud_ynh#336]
Command:
admin@sharicov:/var/www/nextcloud $ sudo -u nextcloud php7.3 occ -V
Output
Sorry, user admin is not allowed to execute '/usr/bin/php7.3 occ -V' as nextcloud on sharicov...

**Comment by Thovi98** [comment]
Your are logged as admin, you have to be root. 
Try again, but with root :
`sudo -i`
`sudo -u nextcloud php7.3 /var/www/nextcloud/occ -V`

**Comment by sharicov** [comment]
Worked. thank you very much! Solved
