### ISSUE TITLE
Failed to upgrade to NC20

### ISSUE THREAD

**Issue by Thovi98** [YunoHost-Apps/nextcloud_ynh#347]
Thank you for the update !
But I tried twice, and it didn’t success. Hope this logs will help diagnosticate the issue : https://paste.yunohost.org/raw/utacubusak

**Comment by Thovi98** [comment]
Okay I could update !
I had to uninstall mail and news apps and installation worked perfectly.

I’ve reinstalled both apps and everything works fine :D

**Comment by kay0u** [comment]
It was indeed the solution here, thank you for your test and your feedback!

I'm closing this issue, do not hesitate to reopen it if needed
