### ISSUE TITLE
update faild

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/nextcloud_ynh#349]
update faild..
please have a look at the log

https://paste.yunohost.org/raw/epamadenit

thanks for help

**Comment by kay0u** [comment]
It looks like redis is down on your server:

What returns these commands?

```
sudo systemctl status redis

sudo systemctl status redis-server.service
```

**Comment by rocky-III** [comment]
```
$ sudo systemctl status redis                                                                                        
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)                                  
   Active: failed (Result: exit-code) since Tue 2020-11-10 16:04:52 UTC; 1 day 17h ago
     Docs: http://redis.io/documentation,                                                                                      
           man:redis-server(1)                                                                                                 
                                                                                                                               
Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.                             
admin@my:~$ sudo systemctl status redis-server.service
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)                                  
   Active: failed (Result: exit-code) since Tue 2020-11-10 16:04:52 UTC; 1 day 17h ago
     Docs: http://redis.io/documentation,                                                                                      
           man:redis-server(1)                                                                                                 
                                                                                                                               
Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.                             

```

Thanks for help

**Comment by kay0u** [comment]
For both services:

> Active: failed

Can you try to restart them with:

```
sudo systemctl restart redis-server

sudo systemctl restart redis
```

**Comment by rocky-III** [comment]
Thanks

`dmin@my:~$ sudo systemctl restart redis-server
Failed to restart redis-serversudo.service: Unit redis-serversudo.service not found.                                           
Failed to restart systemctl.service: Unit systemctl.service not found.                                                         
Failed to restart restart.service: Unit restart.service not found.                                                             
Job for redis-server.service failed because the control process exited with error code.                                        
See "systemctl status redis-server.service" and "journalctl -xe" for details.                                                  
admin@my:~$ sudo systemctl restart redis                                                                                       
Job for redis-server.service failed because the control process exited with error code.                                        
See "systemctl status redis-server.service" and "journalctl -xe" for details.                                                  
admin@my:~$ sudo systemctl restart redis                                                                                       
Job for redis-server.service failed because the control process exited with error code.                                        
See "systemctl status redis-server.service" and "journalctl -xe" for details.                                                  
admin@my:~$ sudo systemctl restart redis                                                                                       
Job for redis-server.service failed because the control process exited with error code.                                        
See "systemctl status redis-server.service" and "journalctl -xe" for details.                                                  
admin@my:~$ journalctl -xe                                                                                                     
Hint: You are currently not seeing messages from other users and the system.                                                   
      Users in the 'systemd-journal' group can see all messages. Pass -q to                                                    
      turn off this notice.                                                                                                    
No journal files were opened due to insufficient permissions.                                                                  
admin@my:~$ sudo journalctl -xe                                                                                                
Nov 12 09:45:26 my.domian.de systemd[1]: redis-server.service: Scheduled restart job, restart counter is at 5.
-- Subject: Automatic restarting of a unit has been scheduled                                                                  
-- Defined-By: systemd                                                                                                         
-- Support: https://www.debian.org/support                                                                                     
--                                                                                                                             
-- Automatic restarting of the unit redis-server.service has been scheduled, as the result for                                 
-- the configured Restart= setting for the unit.                                                                               
Nov 12 09:45:26 my.domian.de systemd[1]: Stopped Advanced key-value store.                                                    
-- Subject: A stop job for unit redis-server.service has finished                                                              
-- Defined-By: systemd                                                                                                         
-- Support: https://www.debian.org/support                                                                                     
--                                                                                                                             
-- A stop job for unit redis-server.service has finished.                                                                      
--                                                                                                                             
-- The job identifier is 33481 and the job result is done.                                                                     
Nov 12 09:45:26 my.domian.de systemd[1]: redis-server.service: Start request repeated too quickly.                            
Nov 12 09:45:26 my.domian.de systemd[1]: redis-server.service: Failed with result 'exit-code'.                                
-- Subject: Unit failed                                                                                                        
-- Defined-By: systemd                                                                                                         
-- Support: https://www.debian.org/support                                                                                     
--                                                                                                                             
-- The unit redis-server.service has entered the 'failed' state with result 'exit-code'.                                       
Nov 12 09:45:26 my.domian.de systemd[1]: Failed to start Advanced key-value store.
-- Subject: A start job for unit redis-server.service has failed                                                               
-- Defined-By: systemd                                                                                                         
-- Support: https://www.debian.org/support                                                                                     
--                                                                                                                             
-- A start job for unit redis-server.service has finished with a failure.                                                      
--                                                                                                                             
-- The job identifier is 33481 and the job result is failed.                                                                   
Nov 12 09:46:35 my.domian.de slapd[10096]: slap_global_control: unrecognized control: 1.3.6.1.4.1.4203.666.5.16
Nov 12 09:46:35 my.domian.de sudo[15696]:    admin : TTY=pts/1 ; PWD=/home/admin ; USER=root ; COMMAND=/bin/journalctl -xe    
Nov 12 09:46:35 my.domian.de sudo[15696]: pam_unix(sudo:session): session opened for user root by admin(uid=0)                
lines 2246-2278/2278 (END)

`

**Comment by kay0u** [comment]
```
sudo systemctl list-units --failed
```

And

```
sudo tail -n 100 /var/log/redis/redis-server.log
```

**Comment by rocky-III** [comment]
```
admin@my:~$ sudo systemctl list-units --failed
  UNIT                 LOAD   ACTIVE SUB    DESCRIPTION                
● redis-server.service loaded failed failed Advanced key-value store   
● rspamd.service       loaded failed failed rapid spam filtering system
                                                                                                                               
LOAD   = Reflects whether the unit definition was properly loaded.                                                             
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.                                                     
SUB    = The low-level unit activation state, values depend on unit type.                                                      
                                                                                                                               
2 loaded units listed. Pass --all to see loaded but inactive units, too.                                                       
To show all installed unit files use 'systemctl list-unit-files'.                                                              
admin@my:~$ sudo tail -n 100 /var/log/redis/redis-server.log
admin@my:~$ 
```

**Comment by kay0u** [comment]
Hmm, can you come to the irc support please, it will be way easier to investigate why redis is down

**Comment by kay0u** [comment]
After deeper investigations, the directory `/var/log/redis/` and file `redis-server.log` didn't have the right permissions, so we did something like this:

`sudo chown -R redis: /var/log/redis`
then
`sudo systemctl restart redis`

**Comment by kay0u** [comment]
Closing! Feel free to reopen this issue

**Comment by rocky-III** [comment]
thanks - update did work now  :-)
