### ISSUE TITLE
Recent error "413 Entity too large" / "An unknown error has occurred"

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/nextcloud_ynh#359]
For a few weeks now, on one on my Yunohost nextcloud server, I can't upload files bigger than 1M. But I still can create directories, and send little files. And there is a lot of space on the disk.
Computer side, the synchro client says "413 error Entity too large"
Web page side, I get the "An unknown error has occurred" message.

I checked "/etc/nginx/nginx.conf" for client_max_body_size, and it is set to 10G
How can I fix this problem?

Thanks !

**Comment by alexAubin** [comment]
do you have any idea about something that changed on your setup before the "few weeks" that could have triggered that issue ?

**Comment by klorydryk** [comment]
I can think about some YNH updates, and I tried to use (then uninstalled) the YNH Kresus package.
But I use Kresus on another YNH without any problem...

**Comment by klorydryk** [comment]
I uninstalled then reinstalled nextcloud... and it is the same with this fresh installation.

**Comment by klorydryk** [comment]
Ok,  it was another Yunohost used as proxy that caused this problem. I had to add the _client_max_body_size_ in nginx.conf (and in _mydomain.conf_ but I dunno which one fixed the problem).
Question: why the nextcloud located directly on the proxy was working fine?? And why did the behavior changed suddenly/this option _client_max_body_size_ disappeared?
