### ISSUE TITLE
where is the "flying" yunohost main panel tile ?

### ISSUE THREAD

**Issue by tutle** [YunoHost-Apps/nextcloud_ynh#367]
Since nextcloud 20, no more yunohost tile to go to main sso panel, Am I the only one with this trouble ?

**Comment by tutle** [comment]
No other person having this trouble ?

**Comment by WildScotsmen** [comment]
My tile is also missing. Just installed the app for the first time and was wondering where it was.

**Comment by tituspijean** [comment]
I can replicate the issue. Here are some investigations into it.

The problem can be circumvented by manually adding the following bit of code (normally injected by NGINX) before `</head>` at line 29 of `/var/www/nextcloud/core/templates/layout.user.php`:
```
<script type="text/javascript" src="/ynh_portal.js"></script><link type="text/css" rel="stylesheet"
href="/ynh_overlay.css"></link><script type="text/javascript" src="/ynhtheme/custom_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynhtheme/custom_overlay.css"></link>
```

This bit of code is not present without this hack. So I guess the matter lies in `/etc/nginx/conf.d/yunohost_panel.conf.inc` where NGINX is instructed to insert the code at the place I mentioned above.

**Comment by tutle** [comment]
Hello, after upgrading nextcloud to 20.0.8~ynh1, no more "flying tile" yunohost again and even ading before </head> at line 29 of /var/www/nextcloud/core/templates/layout.user.php don't solve, any idea ?
<script type=“text/javascript” src=“/ynh_portal.js”></script><link type=“text/css” rel=“stylesheet” href=“/ynh_overlay.css”></link><script type=“text/javascript” src=“/ynhtheme/custom_portal.js”></script><link type=“text/css” rel=“stylesheet” href=“/ynhtheme/custom_overlay.css”></link>

**Comment by sebmennetrier** [comment]
Hello @tutle, have you tested the solution proposed in the PR #402 ?

**Comment by sebmennetrier** [comment]
Yes, in the nginx conf file of your nextcloud installation (and under the line `fastcgi_param front_controller_active true;`).

**Comment by sebmennetrier** [comment]
The file should be somewhere like `/etc/nginx/conf.d/your_nextcloud_instance_domain/nextcloud.conf`

**Comment by tutle** [comment]
Found and done, need to reload something ?

**Comment by sebmennetrier** [comment]
Yes, need to reload nginx `sudo systemctl reload nginx`

**Comment by tituspijean** [comment]
Closing, as the issue is stale and hopefully solved. Feel free to reopen if needed.
