### ISSUE TITLE
Unable to install other apps

### ISSUE THREAD

**Issue by tiotrom** [YunoHost-Apps/nextcloud_ynh#369]
It is weird, but I (as admin) am unable to access the library of nextcloud apps except the ones that are pre-installed with nextcloud. I can't find Tasks, Deck, Talk and the others...I've been using Nextcloud for a few years now on my own server and wanted to try the ynh version. Tried it on a personal server and a cloud server. Same issue. Am I doing something wrong?

**Comment by Thovi98** [comment]
Yes, it’s an issue with Nextcloud itself. If you try to go to https://apps.nextcloud.com, it will not work, so your Nextcloud cannot access the apps library either. 
In a few hours/days we can expect that it will be resolved, and you would be able to install your apps again.

**Comment by tiotrom** [comment]
Works now!
