### ISSUE TITLE
Update from Nextcloud 19 to Nextcloud 20 won't work if Polls application is installed

### ISSUE THREAD

**Issue by franc00018** [YunoHost-Apps/nextcloud_ynh#372]
Update from Nextcloud 19 to Nextcloud 20 won't work if Polls application is installed.

Here is my log. There seems to be an issue with a database table

https://paste.yunohost.org/raw/migigagibu

I removed the polls app with occ, then install went successfully

**Comment by 1989gironimo** [comment]
I'd like to add, that OCR/Tesseract/Fulltextsearch results in a similar error.

Maybe it's possible to add some checks against a blacklist (where these apps are in) right before the upgrade process?

**Comment by tituspijean** [comment]
Closing, as the issue is stale and superseded by #590. Feel free to reopen if needed.
