### ISSUE TITLE
Warning of deprecated functions when trying to upgrade from v19 to v20

### ISSUE THREAD

**Issue by 1989gironimo** [YunoHost-Apps/nextcloud_ynh#375]
`/!\ Packagers! This app is still using the skipped/protected/unprotected_uris/regex settings which are now obsolete and deprecated... Instead, you should use the new helpers 'ynh_permission_{create,urls,update,delete}' and the 'visitors' group to initialize the public/private access. Check out the documentation at the bottom of yunohost.org/groups_and_permissions to learn how to use the new permission mechanism.`

AND

`/!\ Packagers! You are probably using a lua regex. You should use a PCRE regex instead.`

**Comment by tituspijean** [comment]
The latest CI jobs https://ci-apps.yunohost.org/ci/job/18584 do not mention these warning any more.
