### ISSUE TITLE
Nextcloud 12 SAMEORIGIN security warning

### ISSUE THREAD

**Issue by Bugsbane** [YunoHost-Apps/nextcloud_ynh#38]
Hey there,
After upgrading Nextcloud to version 12 via Nextcloud's updater, it gives the following security warning:

> The "X-Frame-Options" HTTP header is not configured to equal to "SAMEORIGIN". This is a potential security or privacy risk and we recommend adjusting this setting.

This looks like we may need to modify something in the Nginx config file for the site created by nextcloud_ynh, but I'm not sure exactly what or how.

**Comment by JimboJoe** [comment]
In my understanding, this header is already set in the nginx configuration file: https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/conf/nginx.conf#L18

**Comment by Bugsbane** [comment]
How do you check the header? I'd like to check on my site to see if this is something that I need to change, or if the warning is a bug in Nextcloud...

**Comment by danielcb** [comment]
@Bugsbane either via curl `curl --head https://nextcloud.yourdomain.com` or via chrome:
* go to your nextcloud installation
* ctrl, shift, i in chrome
* go to network tab
* reload the page
* select your page in the left column (e.g. nextcloud.yourdomain.com)
* headers are displayed in the right column

**Comment by danielcb** [comment]
I also have those warnings, am using the default nginx config and can confirm that `SAMEORIGIN` is set. The warnings still do not disappear. The only uncommon thing is the header being set two times, but both times to `SAMEORIGIN`.

**Comment by JimboJoe** [comment]
This problem has been fixed in the current [pending PR](https://github.com/YunoHost-Apps/nextcloud_ynh/pull/37).
Paradoxically, you have to remove the two occurrences of SAMEORIGIN configuration in the nginx configuration file.

**Comment by danielcb** [comment]
I.e. let nextcloud itself handle the setting of SAMEORIGIN etc.?

**Comment by JimboJoe** [comment]
Yes, that's the idea, which is specifically required for the nginx configuration in the Nextcloud 12 [release notes](https://docs.nextcloud.com/server/12/admin_manual/release_notes.html#updates-to-nginx-configuration).

**Comment by JimboJoe** [comment]
Closed by latest release.
