### ISSUE TITLE
how to access nextcloud locally

### ISSUE THREAD

**Issue by MX10-AC2N** [YunoHost-Apps/nextcloud_ynh#380]
Hello,
I am trying to use nextcloud for file transfer, my problem is that I can only connect to nextcloud locally with my domain name and behind a VPN (very slow transfer)..
So is it not possible to access it in LAN (192.168.1.XXX)? Which port is used for this local connection ??
Thank you..

**Comment by Bugsbane** [comment]
I access mine this way, all the time. The only thing I needed to do was to add the domain name to the nextcloud config.php file and to accept the SSL certificate as the domain is then 192.168.1.XXXX instead of your domain.tld name.

**Comment by imacfan** [comment]
I have added the domain name "192.168.1.XXXX " in config.php. Now, where to accept SSL? 
In the browser by visiting 192.168.1.XXXX /nexclould? it doesn't work for me.

**Comment by Bugsbane** [comment]
That's pretty much all I do. What error are you getting?

**Comment by Karnikel** [comment]
Finally I didn't get it working. 
I entered the local ip adress in config.php at "trusted_domains"-array and rebooted my device. Finally if I enter 192.168.1.XXX/nextcloud in my browser I would be redirected to yunohost admin login page. 
Does anyone know what to do, to access nextcloud at yunohost locally?

**Comment by cfreude** [comment]
did anyone find a solution yet?

**Comment by LAfricain** [comment]
I have the same issue. I would like to access nextcloud locally but I'm all the time redirected to the yunohost server.

**Comment by LAfricain** [comment]
I just modify the /etc/hosts adding the IP to NOD

**Comment by Karnikel** [comment]
Hi @LAfricain, sounds plausible! Thanks.
Could you please tell me what you added/changed in /etc/hosts file?

**Comment by LAfricain** [comment]
192.168.x.x myurl.yunohost.me

**Comment by tituspijean** [comment]
This is most likely a hairpinning issue as per YunoHost's documentation.

Your solution with `/etc/hosts` is the correct one. You can also try to set your YunoHost server as your DNS server for your local (Wi-Fi or Ethernet) network, if it works it will spare you from manually changing the hosts file.
