### ISSUE TITLE
change_url with domain change doesn't propagate the change for the skipped_regex for .well-known

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/nextcloud_ynh#381]
c.f. the install script which adds a skipped_regex for domain.tld/.well-known

But today an user came with a story where they changed the install domain using `change_url` ... but the script doesn't has any line to recreate the proper skipped_regex with the new domain ... (then later the new permission system exploded because the old domain did not exist anymore)

**Comment by xeu100** [comment]
I've experienced this, personally, I did just remove the skipped_regex line, even though it's probably important for something. If there's a way to restore it, please let me know.

**Comment by kay0u** [comment]
Should be fixed by https://github.com/YunoHost-Apps/nextcloud_ynh/pull/241
