### ISSUE TITLE
Set fail2ban rules

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/nextcloud_ynh#39]
In order to protect against brute-force attacks, fail2ban rules should ideally be set. There's an example [here](https://www.c-rieger.de/nextcloud-installation-guide/#c103) that can serve as guideline.

**Comment by Rafi594** [comment]
I will do it

**Comment by Rafi594** [comment]
Its done

https://github.com/YunoHost-Apps/nextcloud_ynh/tree/Add_fail2ban
