### ISSUE TITLE
Broken PDF viewer in shared folders

### ISSUE THREAD

**Issue by marjorii** [YunoHost-Apps/nextcloud_ynh#392]
Hello !

I'd like to report the same issue that in this [post](https://forum.yunohost.org/t/erreur-ouverture-pdf-suite-mise-a-jour-nextcloud/14662). This [seems](https://github.com/nextcloud/server/issues/19572#issuecomment-788742734) fixed in 20.0.8. Is it possible to upgrade to this version ?

Thanks!

**Comment by kay0u** [comment]
Should be fixed by: https://github.com/YunoHost-Apps/nextcloud_ynh/pull/393

You can wait, or upgrade to the testing version with:
```
sudo yunohost app upgrade nextcloud -u https://github.com/YunoHost-Apps/nextcloud_ynh/tree/testing --debug
```

**Comment by marjorii** [comment]
Thanks! I upgrade to testing version and it went well, there's no more corrupted PDF issue for shared folders.
I have one question left though: is there anything I need to do to switch back to the stable branch on 20.0.8's release? 
Thank you in advance!

**Comment by kay0u** [comment]
> is there anything I need to do to switch back to the stable branch on 20.0.8's release?

No, absolutely nothing to do on your side. An update will be suggested when the stable version changes from your current test version (For example: nextcloud 21)

**Comment by marjorii** [comment]
Thanks! YunoHost is so damm great!

**Comment by zamentur** [comment]
We are now in 20.0.8
