### ISSUE TITLE
Upgrade from 20.0.4 to 20.0.7 fails (patch issue ?)

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/nextcloud_ynh#398]
I'm referencing here this issue from the forum to give it more visibility and for future record : https://forum.yunohost.org/t/mise-a-jour-nextcloud-20-0-4-20-0-7/15308

Logs included in the forum topic.

**Comment by tituspijean** [comment]
Closing, as the issue is stale and hopefully solved. Feel free to reopen if needed.
