### ISSUE TITLE
nextcloud.conf misses two lines

### ISSUE THREAD

**Issue by matthijsbro** [YunoHost-Apps/nextcloud_ynh#399]
My nginx configuration of Nextcloud was not complete and missed two lines, that seems like a bug. I installed Yunohost on a cloud VPS ('over' Debian 10) and installed Nextcloud in mydomain.com/nextcloud 
It gave an warning error in mydomain.com/nextcloud/settings/admin/overview that .well-known/carddav and .well-known/caldav where not configured correctly. 

I found this helpful documentation https://docs.nextcloud.com/server/20/admin_manual/installation/nginx.html 

However: the Nginx file on my server at /etc/nginx/conf.d/mydomain.com.d/nextcloud.conf is missing two lines. The example as well as my nextcloud.conf say: 
```
location ^~ /.well-known {
        # The following 6 rules are borrowed from `.htaccess`
```
but my nextcloud.conf (put there by yunohost obviously) lacked the last two lines:
```
        location = /.well-known/carddav     { return 301 /remote.php/dav/; }
        location = /.well-known/caldav      { return 301 /remote.php/dav/; }
```
adding them solved my error. 
Also, all lines were commented and I had to uncomment them. Shouldn't they be uncommented by default?

**Comment by tituspijean** [comment]
Closing, as the issue is stale and hopefully solved. Feel free to reopen if needed.
