### ISSUE TITLE
Cannot install getting nextcloud script error

### ISSUE THREAD

**Issue by sharicov** [YunoHost-Apps/nextcloud_ynh#400]
When installing Nextloud getting following error:
Unable to install nextcloud: An error occurred inside the app installation script

Couldn't find any relevant logs to investigate deeper.

Nextcloud was installed, but stopped working at some point. Had to uninstall it. Now cannot install it back.

Running environement:
Nanopi r4s with daily build of Hirsute.
Yunohost running in lxc (all other apps running properly.
Installation log: https://paste.yunohost.org/raw/ucuhacuguk
Thanks in advance

**Comment by alexAubin** [comment]
`DEBUG - Username is invalid because files already exist for this user`

Not sure exactly, but maybe Nextcloud is complaining that there are already file for "this user", the user maybe being admin ... Could it be related to some files in /home/admin maybe ?

**Comment by sharicov** [comment]
Possible, deleted the lxc container and installed nextcloud from scratch, all working now.
Didn't see the message complaining about the username.

**Comment by PetitMote** [comment]
Hello there,
I also get a script error when trying to install Nextcloud. I had a look in my home, it's quite empty...
https://paste.yunohost.org/raw/uborefizeg
