### ISSUE TITLE
login loop

### ISSUE THREAD

**Issue by petitminion** [YunoHost-Apps/nextcloud_ynh#401]
Since today I'm experiencing login loop : xhen i try to login i'm redirected to the login page. This happens on firefox 87, this doesn't happens on chromium. 

In nginx I have a 499 error.

**Comment by kay0u** [comment]
Hi!

Probably a cache problem on your browser. Can you clean it (or open nextcloud in private mode) and retry again?

**Comment by petitminion** [comment]
that was it thx !
