### ISSUE TITLE
Upgrade to 20.0.8~ynh1 drives nextcloud unusable

### ISSUE THREAD

**Issue by sharicov** [YunoHost-Apps/nextcloud_ynh#406]
Upgraded from `20.0.7~ynh1` to `20.0.8~ynh1` several times (both in web and with command line).
No errors, says upgrade is successful, but nextcloud becomes extremely slow, cannot be used. 
Getting timeout error all the time both in web and in android app. (504 Gateway Time-out nginx)
Running yunohost in lxc on top of armbian 64.
HW Nanopi R4S (4GB RAM)

**Comment by ericgaspar** [comment]
There is an issue about Nextcloud getting slow in the forum. Maybe yours is related...
https://forum.yunohost.org/t/nextcloud-extremely-slow-after-upgrade/15685

**Comment by sharicov** [comment]
Thank you very much for quick response, ericgaspar.
You are right, that's exactly the issue.
Is it possible to reflect the issue in the yunohost upgrade screen as a warning?
For me CODE server is critical and I wouldn't to the upgrade if I knew about the consequences, would rather skip this version.

**Comment by tituspijean** [comment]
Issue was solved on the forum. To be generalized to all incompatible plugins with #590?
