### ISSUE TITLE
Remove bug workaround

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost-Apps/nextcloud_ynh#41]
https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/restore#L21-L25

It seens resolved now https://dev.yunohost.org/issues/593

**Comment by Mickael-Martin** [comment]
Can you explain ? Have you this issue again ?

**Comment by JocelynDelalande** [comment]
> Can you explain ? Have you this issue again ?
> 

I wish, but I do not have the context anymore in mind, and the redmine 
seems down :-/.

Self-guess : Maybe ynh_abynh_abot_if_errors is no longer needed 
?ort_if_errors

**Comment by Mickael-Martin** [comment]
No, ynh_abort_if_errors is needed if yuno cannot install the app, it's a sort of rollback.

**Comment by JocelynDelalande** [comment]
OK, well, given that  I do not remenber the meaning of this ticket and the redmine is not helping, let's say this is not an issue :).


One ticket closed for free, yay!
