### ISSUE TITLE
Cannot login in Nextcloud — password marked as wrong even if right

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/nextcloud_ynh#413]
[Related forum thread](https://forum.yunohost.org/t/cannot-login-in-nextcloud-password-marked-as-wrong-even-if-right/16017 'Cannot login in Nextcloud — password marked as wrong even if right')

### My YunoHost server

**Hardware:** Contabo VPS
**YunoHost version:**  4.2.5.2
**I have access to my server :** SSH and browser
**Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?** : no

<br>

### Description of my issue

I managed to login in my Nextcloud instance **only once** after its installation. I changed nothing in Nextcloud (just deleted the default files in the cloud space), but all of the following login attempts fail, even if I am sure that the password is right, since it corresponds to the Yunohost account Nextcloud belongs to.

- The password is exclusively alpha-numeric
- I tried logging in from other browsers/devices/IP addresses
- I tried reinstalling the app from scratch
- This happens both if I log in after clicking on the button from the Yunohost panel of if I type the cloud address directly.

[](https://user-images.githubusercontent.com/42862428/120021037-d7e08480-bfea-11eb-9cd7-f780533952c2.mp4)

### Steps to reproduce

```sh
sudo yunohost app install nextcloud
```
 
 <br>

### Expected behavior

Login correctly, since the password is right.

<br>

### Logs

```
sudo yunohost app install nextcloud
Choose the domain where this app should be installed [matto.club | tommi.nohost.me | assets.tommi.space | cloud.tommi.space | docs.tommi.space | inputs.tommi.space | server.tommi.space | vpn.tommi.space | wallet.tommi.space] (default: server.tommi.space): cloud.tommi.space
Choose the path where this app should be installed (default: /nextcloud): /
Choose an administrator user for this app [tommi] (default: tommi):
Access the users home folder from Nextcloud? [yes | no] (default: no): yes
Info: Installing nextcloud...
Info: [....................] > Validating installation parameters...
Info: [....................] > Storing installation settings...
Info: [+...................] > Installing dependencies...
Warning: Load smb config files from /etc/samba/smb.conf
Warning: Loaded services file OK.
Warning: Server role: ROLE_STANDALONE
Info: [#+..................] > Creating a MySQL database...
Info: [##..................] > Setting up source files...
Info: [##..................] > Configuring system user...
Info: [##++++++++..........] > Configuring PHP-FPM...
Info: [##########+.........] > Configuring NGINX web server...
Info: [###########++++.....] > Installing Nextcloud...
Info: [###############++...] > Configuring Nextcloud...
Info: [#################+..] > Adding multimedia directories...
Info: [##################..] > Configuring log rotation...
Info: [##################+.] > Configuring Fail2Ban...
Info: The service fail2ban has correctly executed the action reload-or-restart.
Info: [###################.] > Configuring SSOwat...
Warning: /!\ Packagers! You are probably using a lua regex. You should use a PCRE regex instead.
Info: [###################.] > Reloading NGINX web server...
Info: [####################] > Installation of nextcloud completed
Success! Installation completed
```

**Comment by Kazfr** [comment]
Exact same thing here after a fresh install

**Comment by xplosionmind** [comment]
I just noticed this issue is still open. I have never had this problem again.
