### ISSUE TITLE
Nextcloud version to be installed is different from the “shipped” one

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/nextcloud_ynh#416]
### Describe the bug

While installing Nextcloud, I notice that the version that will be installed (20.0.8) is different from the one described as “shipped” in the [nextcloud_ynh repository](https://github.com/YunoHost-Apps/nextcloud_ynh), which should be 21.0.2. Why is it so?

<img width="772" alt="Screenshot 2021-06-08 at 12 29 45 PM" src="https://user-images.githubusercontent.com/42862428/121170234-74552300-c844-11eb-9cbb-cedc14472dda.png">

<img width="986" alt="Screenshot 2021-06-08 at 12 31 01 PM" src="https://user-images.githubusercontent.com/42862428/121170357-a070a400-c844-11eb-82c1-620b991d2062.png">

### Context

**Hardware:** Contabo VPS
**YunoHost version:**  4.2.5.3
**I have access to my server :** SSH and browser
**Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?** : no
- Using, or trying to install package version/branch: [Nextcloud](https://github.com/YunoHost-Apps/nextcloud_ynh)
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app install nextcloud
    ```
### Expected behavior

It should be installed Nextcloud 21.0.2

**Comment by ericgaspar** [comment]
Testing branch version -> 21.0.2
Master branch version -> 20.0.8

`sudo yunohost app install nextcloud` installs Master branch.

**Comment by xplosionmind** [comment]
Thanks a lot! Sorry for my ignorance.
