### ISSUE TITLE
Sent email language is english not = to what I set in nextcloud

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/nextcloud_ynh#418]
### Describe the bug

If I do a poll (for example) and send invitation by email, the sent email will be in english like "Poll invitqtion" or "... invited you to take part in th epoll..." even though I have set the language to french and everything within nextcloud is indeed in french.

### Context

- Hardware:  Old laptop or computer
- YunoHost version: 4.1.8
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

- make a poll in nextcloud (but the problem is the same with other apps)
- invite by email
- sent email is in english

### Expected behavior

sent email would be in the same language as set in nextcloud settings

**Comment by tituspijean** [comment]
Closing as stale. Assuming this is an upstream issue, feel free to reopen if needed.
