### ISSUE TITLE
Set simpleSignUpLink.shown to false

### ISSUE THREAD

**Issue by MCMic** [YunoHost-Apps/nextcloud_ynh#421]
### Describe the bug

By default nextcloud will show a link to nextcloud.com on all public shared pages, with the text «Get your own free account»

### Steps to reproduce

- Share a nextcloud folder through a public link
- Open the link
- There is a link to https://nextcloud.com/signup/ labelled «Get your own free account»

### Expected behavior

Only local links

This link has nothing to do there, and is a lie because getting an account on nextcloud.com will not help using the nextcloud hosted on my server.
It appears that to remove this link the file config.php needs to be edited to set simpleSignUpLink.shown to false.
Documentation is at https://docs.nextcloud.com/server/14/admin_manual/configuration_server/config_sample_php_parameters.html#all-other-configuration-options

**Comment by ericgaspar** [comment]
Closing with #458
