### ISSUE TITLE
Release schedule - v22?

### ISSUE THREAD

**Issue by EDavidF** [YunoHost-Apps/nextcloud_ynh#425]
Hello, and thank you(!) to all the developers on here.

I couldn't find anything about release schedules for the app and/or about what the usual time from office NC release to Yuno version. I did see that 'testing' is still not v22, so, I assume, it will be some time before the Yunohost version is brought up to current?

Thank you.

**Comment by lapineige** [comment]
I don't think there is any plan like this: is all dependent on the time available from the volunteers, the amount of work needed to upgrade to that new version (is there any major/breaking change, …), testers, the number of issues that can arise during testing phase, and so on…

Usually, it start with a Pull Request in a dedicated branch, then goes to testing, then to master.
Once the Pull Request is available (and quite complete), users can test it, if they are willing to take the risk. Same for testing, which often comes with a more limited risk (but still no guaranty it will not break anything). Once merged in master, it takes around one day (maximum) to be available for every user via the official upgrade mechanism. 
The time between each steps can vary a lot, from a few days to a whole month or more… depending mainly on the benevolent effort people can offer to the project at that time 🙂

Regarding v22 : https://github.com/YunoHost-Apps/nextcloud_ynh/pull/423

**Comment by lapineige** [comment]
Fixed by #423
