### ISSUE TITLE
Nextcloud version conflict?

### ISSUE THREAD

**Issue by deljones** [YunoHost-Apps/nextcloud_ynh#431]
My YunoHost server
Hardware: VPS bought online / Old laptop or computer / Raspberry Pi at home / Internet Cube with VPN / Other ARM board / …
YunoHost version: 4.2.7
I have access to my server : Through SSH | through the webadmin | direct access via keyboard / screen | …
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : no
If yes, please explain:

Description of my issue
I love my Yunohost and I love my Nextcloud which I use all the time… I’m grateful to all those that make it possible…

I have one observation.

I have just done a system update and Nextcloud was updated to 21.0.3. However, when I run the Nextcloud security checker it shows as version: 19.0.5.2…??

Is there something missing from this version of YNH Nextcloud?

Many thanks all

Dj

**Comment by tituspijean** [comment]
Closing, as the issue is stale and hopefully solved. Feel free to reopen if needed.
