### ISSUE TITLE
Erreur d'install Nextcloud

### ISSUE THREAD

**Issue by madiwas** [YunoHost-Apps/nextcloud_ynh#432]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to the app itself. Refer to its documentation or repository for help.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug

*Suite installation de Nextcloud en SSH, j'ai le message : Error: Unable to install nextcloud: An error occurred inside the app installation script*

### Context

- Hardware: *NUC D54250WYK*
- YunoHost version: 4.2.8 (stable)
- I have access to my server: *Through SSH whit ssh-key*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no / yes*
  - If yes, please explain: /etc/ssh/sshd_config modifié manuellement.
- Using, or trying to install package version/branch:
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

- *Connexion ssh*
    ```
    yunohost app install nextcloud
    ```
- *Message d'erreur:*
   ```
Error: The operation 'Install the 'nextcloud' app' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20210825-153509-app_install-nextcloud' to get help
   ```
### Logs
https://paste.yunohost.org/raw/yojagivafa

**Comment by ericgaspar** [comment]
There is this warning that makes the install fail : `chown: invalid user: ‘francoise’`
