### ISSUE TITLE
Can't change app url

### ISSUE THREAD

**Issue by narduin** [YunoHost-Apps/nextcloud_ynh#448]
Hello!

### Describe the bug

I'm in the process of changing my yunohost domain.
When trying to change nextcloud's url I get the following error: `./change_url: line 120: domain: unbound variable`

### Context

- Hardware: *VPS bought online.*
- YunoHost version: 4.2.8.3
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 22.1.1~ynh1

### Steps to reproduce

Try to change nextcloud's url through CLI or webadmin.

*CLI*
```sh
sudo yunohost app change-url nextcloud -d cloud.domain.tld -p /
```

### Expected behavior

The url should be updated

### Logs

[Here are the full logs.](https://paste.yunohost.org/raw/ecezafavig)

Thanks!

**Comment by centralscrutinizer21** [comment]
Don't know if related but api url dosen't change as well (running 22.2.0~ynh1 version)

**Comment by tituspijean** [comment]
@centralscrutinizer21 do you have more details about this?

**Comment by ericgaspar** [comment]
Closing with #622. Please reopen if needed
