### ISSUE TITLE
Upgrading from 21 to 22 hangs

### ISSUE THREAD

**Issue by MayeulC** [YunoHost-Apps/nextcloud_ynh#449]
### Describe the bug
Upgrading the app from `21.0.3~ynh1` to `22.1.1~ynh1` fails, the upgrade process must be killed to continue.

### Context

- Hardware: x86_64 bare metal
- YunoHost version: 4.2.8.3 (stable)
- I have access to my server: SSH+webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: n/a
- Using, or trying to install package version/branch: 22.1.1~ynh1
- If upgrading, current package version: 21.0.3~ynh1
### Steps to reproduce

1. Perform the upgrade
2. Wait
3. Wait some more (I waited 24 hours)
4. tail the latest log file as yunohost-api is locked
5. See that it has been almost 24 hours since the last line was printed:
  ```2021-09-14 10:37:53,426: DEBUG - Updating <twofactor_backupcodes> ...
2021-09-14 10:37:53,457: DEBUG - Updated <twofactor_backupcodes> to 1.10.1
2021-09-14 10:37:53,458: DEBUG - Updating <viewer> ...
2021-09-14 10:37:53,490: DEBUG - Updated <viewer> to 1.6.0
2021-09-13 10:37:53,491: DEBUG - Checking for update of app accessibility in appstore
```
7. kill the `php occ upgrade` command trough `htop` because that's the only way to unstuck yunohost_api
8. upgrade fails
9. Disable app accessibility
10. Upgrade now fails at app "activity"

### Expected behavior

Upgrade succeeds, skips apps that are not upgradeable

### Logs

https://paste.yunohost.org/raw/ijutuseqem

# Investigation and dirty fix
### Cause
This error had been present for a while, so I finally bit the bullet and print-debugged it.

The issue happens when fetching the app list json:

```php
"./lib/private/App/AppStore/Fetcher/Fetcher.php"
$response = $client->get($this->getEndpoint(), $options);
"./lib/private/Http/Client/Client.php"
$response = $this->client->request('GET', $uri, ....
```

### Dirty fix
Even deleting extra options didn't fix it, so I commented out the handler for the HTTP calls library client **while the upgrade was stuck**:

```php
"/var/www/nextcloud/lib/private/Http/Client/ClientService.php"
                $client = new GuzzleClient();# commented out the argument: ['handler' => $stack]);
```
Then, I manually ran the `occ upgrade command`:

1. Add `apc.enable_cli=1` to `/etc/php/7.3/mods-available/apcu.ini`
2. Run `sudo -u nextcloud bash`
3. `cd /var/www/nextcloud`
4. Run `php7.3 occ upgrade`
5. undo every change from the `apcu.ini` to `ClientService.php`
6. Kill the script [in a way that will return 0](https://serverfault.com/questions/390846/kill-a-process-and-force-it-to-return-0-in-linux) so that yunohost thinks it is successfull: `gdb --batch --eval-command 'call exit(0)' --pid <php7.3 occ upgrade --no-ansi etc from yunohost_api PID>` (I obtained the PID from htop > tree view > search for occ).
7. Let the upgrade finish normally

I have a second nextcloud instance with the same issue, I'll do that dirty fix there as well in a few days if necessary.

**Comment by MayeulC** [comment]
I also note that after the upgrade I re-enabled some apps, then suddenly got an "Internal server error" message from nextcloud on the webpage:

![image](https://user-images.githubusercontent.com/3952726/137947092-aafee1c1-f356-43f2-9c22-3418f0461d41.png)

I used `occ logs:watch` to get the details:

```
Error    index              Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory,  2021-10-19T14:43:36+00:00
                              consider increasing server sort buffer size at .../dbal/src/Driver/API/MySQL/ExceptionConverter.php line 114
```

Increasing the sort buffer size to 256K in `/etc/mysql/my.cnf` then restarting mariadb was not enough, then I increased it to 1M, and everything seems to work normally now.

**Comment by ericgaspar** [comment]
I this still an issue?

**Comment by alexAubin** [comment]
Closing because 3 years old and no feedback
