### ISSUE TITLE
Update 11.0.3 killed my Nextcloud

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/nextcloud_ynh#45]
Hi,
I did try to update to the 11.0.3 from Nextcloud v11.0.2.
It failed because of "unable to write to /tmp/xxx". Then it tried to get the backup back, but it was stuck at :
`Extraction des modèles depuis les paquets : 100%`
Now I try to install the backup by myself and I get the same result:

> sudo yunohost backup restore nextcloud-before-upgrade2
> Attention : --hooks is deprecated and will be removed in thefuture. Please use --system instead.
> Attention : YunoHost est déjà installé
> Voulez-vous vraiment restaurer un système déjà installé ? [y/N] : y
> Attention : « yunohost app checkurl » est déprécié et sera bientôt supprimé
> Extraction des modèles depuis les paquets : 100%

After 2 hours, I got this:

> Attention : cp: impossible d'évaluer « ./www/3rdparty/pimple/src »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/3rdparty/punic/code »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/3rdparty/punic/LICENSE.txt »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/3rdparty/punic/UNICODE-LICENSE.txt »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/3rdparty/phpseclib/LICENSE »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/3rdparty/phpseclib/File »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/3rdparty/phpseclib/System »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/3rdparty/phpseclib/openssl.cnf »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/3rdparty/phpseclib/Crypt »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/3rdparty/phpseclib/bootstrap.php »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/3rdparty/phpseclib/Math »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/3rdparty/phpseclib/Net »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/3rdparty/phpseclib/AUTHORS »: Aucun fichier ou dossier de ce type

One hour more, and:

> Attention : cp: impossible d'évaluer « ./www/3rdparty/swiftmailer/lib »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/lib/composer/installed.json »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/lib/composer/LICENSE »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/lib/composer/autoload_static.php »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/lib/composer/autoload_namespaces.php »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/lib/composer/ClassLoader.php »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/lib/composer/autoload_real.php »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/lib/composer/autoload_classmap.php »: Aucun fichier ou dossier de ce type
> Attention : cp: impossible d'évaluer « ./www/lib/composer/autoload_psr4.php »: Aucun fichier ou dossier de ce type
> Erreur : Impossible de restaurer l'application « nextcloud »
> Attention : ERROR 1008 (HY000) at line 1: Can't drop database 'nextcloud'; database doesn't exist
> Attention : ERROR 1396 (HY000) at line 1: Operation DROP USER failed for 'nextcloud'@'localhost'
> Erreur : Rien n'a été restauré

What is wrong with this installation?
Thanks.

**Comment by zamentur** [comment]
@klorydryk You should untar your backup and check that there is /apps/nexcloud/backup/www/lib and /apps/nexcloud/backup/www/librdparty dir

**Comment by nobrakal** [comment]
Same problem, https://paste.yunohost.org/ucujexuwih

I don't have any backup, but data still on the server (in /home/yunohost.app/nextcloud ) . What can I do to reinstall without losing these data ?

**Comment by juliencognito** [comment]
Hello,
The discussion about the failing update is also [on the forum](https://forum.yunohost.org/t/defaut-de-maj-nextcloud/3143/2).
For me is 1 other case, the new install has retained the files and their indexing.
Beware, however, of third-party apllications!

**Comment by JimboJoe** [comment]
As said on [this forum post](https://forum.yunohost.org/t/defaut-de-maj-nextcloud/3143/6?u=jimbojoe), the fix in on the way, and a workaround the restoration bug is to run:
```
sudo apt-get install archivemount
```
Sorry for the inconvenience!
