### ISSUE TITLE
Upgrade nextcloud from  21.0.2~ynh1 to 22.2.0~ynh1 Failure

### ISSUE THREAD

**Issue by bdelaup** [YunoHost-Apps/nextcloud_ynh#452]
### Describe the bug

Error while trying to upgrade nextcloud from  21.0.2\~ynh1 to 22.2.0\~ynh1 using webadmin

### Context

- Hardware: Raspberry Pi at home 
- YunoHost version: 4.3.2.2
- I have access to my server:  webadmin

### Steps to reproduce

Just click on update in the webadmin :
![Capture d’écran 2021-11-06 210358](https://user-images.githubusercontent.com/64602850/140622412-e4bed32b-e873-4a04-abbb-2d1c8af2ac11.png)

### Expected behavior

Everything goes smoothly !

### Logs

Logs available [here](https://paste.yunohost.org/raw/zivahuvule).

Thanks for the help !

**Comment by bdelaup** [comment]
Hi,I'm still stuck on this issue and have no Idea where to start to fix it. 
Help pleeeeaaase ! 😉

**Comment by Gredin67** [comment]
you can try this #526 as soon as it's merged in testing

**Comment by ericgaspar** [comment]
should be fixed with #555
