### ISSUE TITLE
the documenttype parameter for the config object is invalid

### ISSUE THREAD

**Issue by tutle** [YunoHost-Apps/nextcloud_ynh#461]
Hello
Just update the onlyoffice plugin to 7.2.0 in my 22.2.0 nextcloud instance on yunohost server (with onlyoffice application 6.4.0~ynh2 ).
It was perfectly working before
Any suggestion ?
![onlyoffice error](https://user-images.githubusercontent.com/23037149/144298757-a2311220-ccc1-4b27-bc09-686d5a57f1eb.jpg)

**Comment by tituspijean** [comment]
Closing, as the issue is stale and hopefully solved. Feel free to reopen if needed, with appropriate logs.
