### ISSUE TITLE
Error installing: An error occurred inside the app installation script

### ISSUE THREAD

**Issue by kalak-sudo** [YunoHost-Apps/nextcloud_ynh#467]
### Describe the bug

I a VPS with other apps installed from Yunohost (Calibre, FreshRSS and some wordpress).
I have space on the HD and 16GB of RAM.

Yunohost_version: 4.3.4.2

When I set everything for installing Nextcloud, I get the following error:

Error
An error occurred inside the app installation script
Sub-operations
Update URL related to permission 'nextcloud'
Update accesses for permission 'nextcloud'
Create permission 'nextcloud' 

Yunopaste: 
[https://paste.yunohost.org/raw/cidagefapu](https://paste.yunohost.org/raw/cidagefapu)

---- 

EDIT 1:

After using the command proposed: `sudo rm -R /home/yunohost.app/nextcloud/data` I tried installing again, and got this error:

[https://paste.yunohost.org/raw/ezutumaloy](https://paste.yunohost.org/raw/ezutumaloy)
----

What is happening?? 

Thanks in advanced :)

**Comment by ericgaspar** [comment]
```
 /home/yunohost.app/nextcloud/data
 Username is invalid because files already exist for this user
```
first try to remove this path before reinstalling Nextcloud

`sudo rm -R /home/yunohost.app/nextcloud/data` (that is if you don't have anything important stored on it)

**Comment by kalak-sudo** [comment]
> ```
>  /home/yunohost.app/nextcloud/data
>  Username is invalid because files already exist for this user
> ```
> 
> first try to remove this path before reinstalling Nextcloud
> 
> `sudo rm -R /home/yunohost.app/nextcloud/data` (that is if you don't have anything important stored on it)

I did it, and tried installing again, and got this error:

[https://paste.yunohost.org/raw/ezutumaloy](https://paste.yunohost.org/raw/ezutumaloy)

**Comment by ericgaspar** [comment]
Now you seem to have a memory problem...
```
Memory allocation error: 1038 Out of sort memory, consider
2021-12-11 12:25:29,732: WARNING -    increasing server sort buffer size
```

**Comment by kalak-sudo** [comment]
Thanks for your answer.

Ok, I free up some memory, and after several tries, I continously get errors. Here is:

[https://paste.yunohost.org/raw/egenasivec](https://paste.yunohost.org/raw/egenasivec)

What is happening now?

**Comment by kalak-sudo** [comment]
Ok, is the memory... Thanks @ericgaspar !!!
