### ISSUE TITLE
internal Server Error  (reloded) 

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/nextcloud_ynh#469]
It was working for a while but now i have this internal Server Error again - i can´t login
it is like here:
https://github.com/YunoHost-Apps/nextcloud_ynh/issues/313

/var/log/nginx/cloud.xyz.tld-error.log  shows me:

```
2021/12/14 11:07:42 [error] 7077#7077: *67399 open() "/usr/share/nginx/html/.well-known/caldav" failed (2: No such file or directory), client: 127.0.0.1, server: cloud.xyz.tld, request: "GET /.well-known/caldav HTTP/2.0", host: "cloud.xyz.tld"
2021/12/14 11:07:42 [error] 7077#7077: *67400 open() "/usr/share/nginx/html/.well-known/carddav" failed (2: No such file or directory), client: 127.0.0.1, server: cloud.xyz.tld, request: "GET /.well-known/carddav HTTP/2.0", host: "cloud.xyz.tld"
2021/12/14 11:10:38 [crit] 8006#8006: *67480 stat() "/var/www/nextcloud/index.php" failed (13: Permission denied), client: xx.yy.143.211, server: cloud.xyz.tld, request: "GET /index.php/csrftoken HTTP/2.0", host: "cloud.xyz.tld"
```

/usr/share/nginx/html/.well-known/caldav
and
/usr/share/nginx/html/.well-known/carddav

have be created by me now... but that does not help..

what could I try next?
THANKS for help

**Comment by bjarkan** [comment]
to /etc/nginx/conf.d/domain.dlt.d/nextcloud.conf add at the begining... (Change domain.dlt.d with your domain of course)

`
location ^~ /.well-known {
  # The following 6 rules are borrowed from `.htaccess`

  # The following 2 rules are only needed for the user_webfinger app.
  # Uncomment it if you're planning to use this app.
  #rewrite ^/\.well-known/host-meta\.json  /public.php?service=host-meta-json  last;
  #rewrite ^/\.well-known/host-meta        /public.php?service=host-meta       last;

  location = /.well-known/carddav     { return 301 /remote.php/dav/; }
  location = /.well-known/caldav      { return 301 /remote.php/dav/; }

  location = /.well-known/webfinger     { return 301 /index.php$uri; }
  location = /.well-known/nodeinfo      { return 301 /index.php$uri; }

  try_files $uri $uri/ =404;
}
`
It's a common known recipe... and works

**Comment by tituspijean** [comment]
Closing, as the issue is stale and hopefully solved. Feel free to reopen if needed.
