### ISSUE TITLE
Enforce Nextcloud recommended file rights

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/nextcloud_ynh#47]
according to 

> https://github.com/nextcloud/vm/blob/master/static/setup_secure_permissions_nextcloud.sh

 the permissions could be enforced for more security.

Originally posted [here](https://github.com/YunoHost-Apps/nextcloud_ynh/pull/37#issuecomment-312726444) by @ewilly

**Comment by alexAubin** [comment]
Closing because no update since 2017, it's not clear exactly what could be missing ... I think we have good-enough security for all the major folders like /var/www/nextcloud ...
