### ISSUE TITLE
Warning "Your web server is not properly set up to resolve for "/.well-known/caldav"."

### ISSUE THREAD

**Issue by 4abhinavjain** [YunoHost-Apps/nextcloud_ynh#472]
### Describe the bug

I am still getting caldav and carddav warnings in my system's overview despite the rewrite entries in the nextcloud.conf . I donot have any Caldav/Carddav server like Baikal installed and the nextcloud is installed in the subdirectory (/nextcloud)  

### Context

- Hardware: VPS bought ARM online
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no /
- Using, install package version/branch: Nextcloud 22.2.3

### Steps to reproduce
N.A.
### Expected behavior

Such warning should not be there. Sync contacts with android phone (android 9) via DAVx5 app should work. But nothing happens on sync. I checked the logs and there is no info there. 

I checked and the config is as per highlighted in the solution here -> https://github.com/YunoHost-Apps/nextcloud_ynh/issues/469

**Comment by tituspijean** [comment]
Closing, as the issue is stale and hopefully solved. Feel free to reopen if needed.
Duplicate of #469
