### ISSUE TITLE
Unable to access settings

### ISSUE THREAD

**Issue by Samuel2401** [YunoHost-Apps/nextcloud_ynh#473]
I use YunoHost on a computer at home as a server, after installing Nextcloud, impossible to access the config-panel of the application from the administrator interface. I got an error message regarding: Control panel versions '0.1' are not supported.

YunoHost version is: 4.3.6.2 (stable)
Nextcloud version is: 22.2.3~ynh1

![Capture d’écran (4)](https://user-images.githubusercontent.com/60930768/154573370-52d100e8-4042-4165-8d90-1fd66d82724f.png)

**Comment by tituspijean** [comment]
#464 will fix that. Feel free to test out the testing branch and report any issue if you are feeling adventurous.

**Comment by Samuel2401** [comment]
Thank you
I would like to test the testing branch but I don't know how to do that...
If there is a link that explains the procedure to do that, I am interested, thank you

**Comment by tituspijean** [comment]
Explanations are at the bottom of the README.

**Comment by Samuel2401** [comment]
Thanks you !
