### ISSUE TITLE
'/etc/php/7.3/fpm/pool.d/nextcloud.conf' does not exist, Could not upgrade nextcloud: An error occurred inside the app upgrade script

### ISSUE THREAD

**Issue by anondatura** [YunoHost-Apps/nextcloud_ynh#474]
### Describe the bug

The update crashed and I cannot access to my nextcloud server. 

Upgrading from 20.0.7 ynh1 to 22.2.3 ynh1

### Context

- Hardware: debian virtual machine on a computer
- YunoHost version: 4.3.6.2 (stable)
- I have access to my server: Through SSH (or through the webadmin)
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
 

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. :*
    ```sh
    sudo yunohost app upgrade nextcloud
    ```

### Logs

https://paste.yunohost.org/raw/coneyuyixi

Regards.

**Comment by anondatura** [comment]
Update : The synchronization between my devices is working. Only the web interface of nextcloud is not working.
This situation is fine currently.
I hope the next update will solve this bug.

**Comment by Gredin67** [comment]
might be solved by #452

**Comment by ericgaspar** [comment]
should be fixed with #555
