### ISSUE TITLE
PHP-FPM not giving nextcloud enough resources

### ISSUE THREAD

**Issue by Samuel-BF** [YunoHost-Apps/nextcloud_ynh#475]
### Describe the bug

Nextcloud app is using default PHP-FPM parameters for launching processes 4 processes max, which is too low (think "photos pages", when you have a bunch of concurrent php workers computing thumbnails)

Current configuration (`/etc/php/7.3/fpm/pool.d/nextcloud.conf` shipped by yunhost/nextcloud) :
```
pm = dynamic
pm.max_children = 4
pm.max_requests = 500
request_terminate_timeout = 1d


pm.start_servers = 1
pm.min_spare_servers = 1
pm.max_spare_servers = 2
```

Recommended configuration (not extensively tested yet...)
```
pm = dynamic
pm.max_children = 50
pm.max_requests = 500
request_terminate_timeout = 1d


pm.start_servers = 20
pm.min_spare_servers = 10
pm.max_spare_servers = 40
```

Note that this may represent a high pressure on the machine (RAM...). Is there a way to git these parameters to machine specs ?

### Context

- Hardware: VPS bought online
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: (not relevant)
- Using, or trying to install package version/branch: 22.2.0~ynh1

### Steps to reproduce

- visit https://my-yunohost-instance/nextcloud-path/apps/files/?dir=/Photos
- thumbnails take quite a long time to be computed
- take a look at `/var/log/php7.3-fpm.log`, you should see messages like : `WARNING: [pool nextcloud] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers)`

### Expected behavior

- thumbnails loading faster
- no errors in the logs, PHP-FPM starting as many processes as needed

### Logs
`WARNING: [pool nextcloud] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers)`

**Comment by tituspijean** [comment]
> Recommended configuration (not extensively tested yet...)

Recommended by whom? I find quite different figures there: https://docs.nextcloud.com/server/20/admin_manual/installation/server_tuning.html#tune-php-fpm
Anyways, these settings are highly dependent on each admin's actual usage for Nextcloud and the server's specs (a beast VPS and RPi won't handle these settings the same way).

> Is there a way to git these parameters to machine specs ?

Maybe this can help? https://spot13.com/pmcalculator/

---

Note that you can semi-automatically edit them through Nextcloud's config panel in the webadmin.
I'll close this, as I feel there not much we can do more within the package itself. Feel free to further discuss it here.
