### ISSUE TITLE
Webdav requires no authentication - possible dangerous security issue?

### ISSUE THREAD

**Issue by felysu** [YunoHost-Apps/nextcloud_ynh#476]
### Describe the bug

Hello, I hope everyone's well.
I have what seems like a big issue: when logging onto my Nextcloud instance through the Dolphin file manager (KDE) by using webdav, I don't get asked any password - in fact, the file manager itself warns me about possibly accessing something unsafe.

So from what I can gather, anyone can access my files at the moment as long as they know the username I'm using on my nextcloud instance? Isn't this a big security hole?
I've tried to set a password from Nextcloud itself but it seems like I can't, probably because of its interconnection with Yunohost profiles.

### Context

- Hardware: Slightly old laptop
- YunoHost version: 4.3.6.2 (stable)
- Nextcloud version: 22.2.3~ynh1
- I have access to my server: Through SSH and webadmin, but also direct access if needed.

### Steps to reproduce

- Added a remote Webdav by launching Dolphin, going in the "Network" tab, clicking the "Add Network Folder";
- Filled the usual required fields, such as username, server and folder;
- The file manager connected properly and warned me about the fact that it required no authorization.

### Expected behavior

Webdav browsing should ask me for a password.

**Comment by tituspijean** [comment]
Hello, I cannot replicate your issue on Windows. Could you have, by any chance, your credentials already in your keystore?

**Comment by felysu** [comment]
> Hello, I cannot replicate your issue on Windows. Could you have, by any chance, your credentials already in your system keyring?

Oh gosh, I think this must be it.. Dolphin is a little confusing on the matter as it seems to store the password at least until logout, but doesn't tell you so - the opposite in fact, since it warns me continuously about accessing something without password.
This is resolved. Sorry for the silly issue ;;
