### ISSUE TITLE
Unable to upgrade to latest 22.2.5 version from 22.2.3

### ISSUE THREAD

**Issue by jahway603** [YunoHost-Apps/nextcloud_ynh#479]
### Describe the bug

When in the Nextcloud server, I navigate to the Settings and it displays version 22.2.3 (released November 15 2021). It does not display any method to upgrade the version in this menu as it does on other Nextcloud servers not running on Yunohost.

### Context

- Hardware: Old computer
- YunoHost version: 4.3.6.2 (stable)
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen | and all of the above
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain:
- Using, or trying to install package version/branch: Nextcloud 22.2.5 (released February 16, 2022)
- If upgrading, current package version: yunohost app info nextcloud
description: Online storage, file sharing platform and various other applications
domain_path: my.domain.name.com/nextcloud
name: Nextcloud
version: 22.2.3~ynh1

### Steps to reproduce

When in the Nextcloud server, I navigate to the Settings and it displays version 22.2.3 (released November 15 2021). It does not display any method to upgrade the version in this menu as it does on other Nextcloud servers not running on Yunohost.

### Expected behavior

An upgrade option should appear to upgrade to the latest 22.2.5 release.

### Logs

N/A

**Comment by terrible-solver** [comment]
same here.. trying to update to 22.2.6 via the system admin web app and console

**Comment by Che15ea** [comment]
same here, now it's 22.2.6.

**Comment by zamentur** [comment]
we are now in 22.2.7
