### ISSUE TITLE
Cannot install NextCloud on Raspberry Pi OS 64 bits

### ISSUE THREAD

**Issue by PiOverFour** [YunoHost-Apps/nextcloud_ynh#482]
### Describe the bug

Cannot install NextCloud on Raspberry Pi OS 64 bits.

### Context

- Hardware: Raspberry Pi 3 B at home
- YunoHost version: 4.3.6.3 (stable)
- I have access to my server: through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - I installed the 64 bit version of Raspberry Pi OS, as instructed [here](https://forum.yunohost.org/t/yunhost-en-64bits-sur-raspberry-4/18852/2), and restored the system settings from a previous 32 bit installation.
- Using, or trying to install package version/branch: 22.2.3~ynh1

### Steps to reproduce

```sh
sudo yunohost app install nextcloud
```

### Expected behavior

For the package to be installed :)

### Logs
https://paste.yunohost.org/raw/irevanusiq

**Comment by PiOverFour** [comment]
The log mentioned:
```
2022-04-28 02:02:49,581: WARNING - setfacl: /home/yunohost.multimedia/share/Torrents: No such file or directory
2022-04-28 02:02:49,586: WARNING - setfacl: /home/yunohost.multimedia/share/Torrent to download: No such file or directory
```
and going into the dir in question I got:
```
$ ls -l /home/yunohost.multimedia/share/
total 16
drwxrwxr-x+ 2 root root 4096 Feb  1  2020  eBook/
drwxrwxr-x+ 2 root root 4096 Feb  1  2020  Music/
drwxrwxr-x+ 2 root root 4096 Feb  1  2020  Picture/
lrwxrwxrwx  1 root root   37 Apr 29 00:47  Torrents -> /home/yunohost.transmission/completed/
lrwxrwxrwx  1 root root   35 Apr 29 00:47 'Torrent to download' -> /home/yunohost.transmission/watched/
drwxrwxr-x+ 2 root root 4096 Feb  1  2020  Video/
```
but the links to `home/yunohost.transmission/completed` and `home/yunohost.transmission/watched` were invalid because the dirs didn’t exist. I installed the transmission app and could complete the Nextcloud install.

Does the install script fail to check whether transmission is installed?

**Comment by tituspijean** [comment]
This is an issue with Transmission app, which should delete the symlinks when being uninstalled.
