### ISSUE TITLE
Updating Yunohost firstname/lastname does not update Nextcloud 

### ISSUE THREAD

**Issue by mofoch** [YunoHost-Apps/nextcloud_ynh#49]
**Test:** change yunohost user firstname or lastname. reload nextcloud

**Expectation:** name changes are displayed correctely in nextcloud.

**Result:** old firstname / lastname is still displayed.

**Environment:** nextcloud version 12

**Comment by mofoch** [comment]
I also noticed that when I try to change the full name of a user in `nextcloud/index.php/settings/users` the change does not stick upon reload of the page

**Comment by BCITMike** [comment]
This is annoying. You setup a user with unknown last name or a typo and you can't fix later on.  Looks bad and unprofessional.

**Comment by fflorent** [comment]
I still have the issue despite having the latest 15.0.X release. 

https://github.com/nextcloud/server/issues/6719

https://github.com/nextcloud/server/pull/12054

If by chance you have a good workaround, I would be very grateful :)
Florent

**Comment by alexAubin** [comment]
Closing because pretty much no update in 6 years ... I doubt this is really an issue on YunoHost side ... Nextcloud should just pick the info in the LDAP DB and not copy-paste them idk, maybe it's fixed since then ...
