### ISSUE TITLE
Is login form supposed to be redirected to YNH login page and how ?

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost-Apps/nextcloud_ynh#490]
Troubleshooting a server, it happened than disabling the user_saml NC app fix my issue (login was issuing a 500, the stacktrace was pointing to that NC app).

But now when I have to login on NC, I see the NC login form, not the ynh login form. And for example, that leads me to not having the handy « YunoHost » square badge (I guess because nc is logged in but ynh sso is not).

So I was wondering if that behavior was expected and if user_saml NC app had any role in SSO integration within Yunohost.

(I'm pretty unsure about how did it behave before)

**Comment by dalgwen** [comment]
Hello,

> So I was wondering if that behavior was expected and if user_saml NC app had any role in SSO integration within Yunohost.

I, among others, was investigating some sso related issue and I found your post.
I think I'm too late, but whatever, I think I can answer partially :
https://github.com/YunoHost-Apps/nextcloud_ynh/issues/202#issuecomment-509634352

The yunohost SSO doesn't use the SAML app
SSOwat, as a module inside the reverse proxy nginx, inject basic header authentication (login + password)
Nextcould uses this header for authentication.
AFAIK, the only other login related configuration from yuonhost is to set the disconnection URL
So, if you have the nextcloud login form and not the yunohost one, it it the attended behaviour. (but  not optimal, I concur)
