### ISSUE TITLE
Upgrade to Nextcloud 12.0 fails: "PHP Fatal error: Class '\OC\Memcache\APC' not found in /var/www/nextcloud/lib/private/Memcache/Factory.php on line 116"

### ISSUE THREAD

**Issue by Ezwen** [YunoHost-Apps/nextcloud_ynh#50]
I am trying to upgrade nextcloud to 12.0 using the moulinette, but it seems to fail with the error:
 
~~~
PHP Fatal error:  Class '\OC\Memcache\APC' not found in /var/www/nextcloud/lib/private/Memcache/Factory.php on line 116
~~~
 
Complete log: https://paste.yunohost.org/rewaninole
 
Fortunately the upgrade mechanism is quite robust and it successuly restores a backup :). Really nice job on this part!

I have also opened a ticket here, I wasn't sure where was the best: https://dev.yunohost.org/issues/985

**Comment by JimboJoe** [comment]
I encountered once [the same problem](https://github.com/YunoHost-Apps/nextcloud_ynh/pull/37#issuecomment-306212955).
Try removing the line `"memcache.locking": "\\OC\\Memcache\\APC",` from `/var/www/nextcloud/config/config.php`.

**Comment by Gwend4l** [comment]
Thanks, that solved the problem!

**Comment by Shnoulle** [comment]
Solved too, for information : my Nextcloud come from an old OwnCloud (Maybe 9.??)

**Comment by alexAubin** [comment]
Closing because issue is outdated (or solved idk)
