### ISSUE TITLE
Video previews enabled by default?

### ISSUE THREAD

**Issue by yajo** [YunoHost-Apps/nextcloud_ynh#507]
### Describe the feature

Enable video previews out of the box.

### Context

Using https://play.google.com/store/apps/details?id=com.nkming.nc_photos.paid&referrer=utm_source%3Drepo or official nextcloud app. Seeing video previews is cool!

### Expected behavior

Enabled by default

### How to do it

Just follow [these instructions](https://gitlab.com/nkming2/nc-photos/-/wikis/help/video-previews).

However, this feature request is to enable this to be a default behaviour, out of the box. I think it'd make it more pleasant to use.

**Comment by tituspijean** [comment]
@ericgaspar do you remember why you abandoned the PR? Shall we drop this as "not planned"?

**Comment by ericgaspar** [comment]
must have been something important 😅 Yes, we can drop this I guess
