### ISSUE TITLE
Nexctloud news app doesn't update feeds

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/nextcloud_ynh#510]
### Describe the bug

Nextcloud news app doesn't update feeds.

### Context

- Hardware: Old laptop or computer
- YunoHost version: 11.0.9.13
- I have access to my server: *hrough SSH | through the webadmin | direct access via keyboard / screen | ...

### Steps to reproduce

- Install Nextcloud news app
- add RSS feeds
- it gets an article list from the RSS feed
- it never update this article list.

### Expected behavior

It should fetch list of new articles automatically.

### Other information

Nextcloud News app's FAQ has information about reasons why it doesn't update : https://nextcloud.github.io/news/faq/#system-cron
Something about the system cron, about file permissions of the cron.php, about the oc_jobs table in database has a reserved_at entry...

**Comment by come-nc** [comment]
For me news fails to update feeds because of https://github.com/YunoHost-Apps/nextcloud_ynh/issues/48

Do you have any sql error in the logs? Might be the same thing.

**Comment by Thatoo** [comment]
I don't know, could be but I don't see sql error.
Hopefully one of these PR will help us https://github.com/YunoHost-Apps/nextcloud_ynh/pull/384 or https://github.com/YunoHost-Apps/nextcloud_ynh/pull/125

**Comment by tituspijean** [comment]
@Thatoo did #364 solve the issue?
