### ISSUE TITLE
custom_overlay.css 302 not found

### ISSUE THREAD

**Issue by nin0-0** [YunoHost-Apps/nextcloud_ynh#525]
### the bug

302 not found for custom_overlay.css but in folder ynhtheme ?

### Context
on each page load it looks for this yunohost overlay css 

I symlinked this now:
`ln -s /usr/share/ssowat/portal/assets/themes/vapor/custom_overlay.css /var/www/nextcloud/apps/files/custom_overlay.css`

But it is centered in the middle on the right instead of down. Also I accidentally got it working, because I'd have to put it in ynhtheme folder normally? Maybe it's looking in multiple locations.

**Comment by alexAubin** [comment]
(Closing because 2 years old and not relevant anymore with the new portal)
