### ISSUE TITLE
Problems with shared links access, nextcloud 24.07 and 25.0.2

### ISSUE THREAD

**Issue by tutle** [YunoHost-Apps/nextcloud_ynh#527]
![nextclouderror](https://user-images.githubusercontent.com/23037149/204149505-a33713fd-984b-4da1-9e18-912f3dfd30c0.JPG)
From a short time, I have a very slow web interface (more than 25 seconds to have the page from external shared link and 25 more seconds to see a pdf) and also some alerts "this folder is unreachable, contact administrator" for allready existing sharing links. It's almost at once when connected with my account.
I was with 20.04 and upgrade to 24.07 but stills same problems.
Onlyoffice 7.5.8 in nextcloud
Any Ideas ?
I'm on yunohost 11.0.10.2 and onlyoffice app 7.1.0~ynh1 and fiber internet connection

I [saw this](https://help.nextcloud.com/t/accessing-nextcloud-from-outside-network-is-extremely-slow/114830/6)...

**Comment by tituspijean** [comment]
Can you share the PHP-FPM logs related to Nextcloud, per your screenshot? Per your linked post on Nextcloud's forum, can you share the output of your Nextcloud Overview page?

**Comment by tutle** [comment]
where can I find php-fpm ? here is a [exemple link](https://elemac.fr/nextcloud/s/KKPNMzbCf7qx8XM)

**Comment by tituspijean** [comment]
In the PHP-FPM service log, in the Services page of the webadmin.

Your link opens fine with me. You could also try increasing PHP memory usage with the app's config panel in the webadmin.

What about the warnings in the Overview  page?

**Comment by tutle** [comment]
[php7.4-fpm](https://paste.yunohost.org/qinegepobo) paste

[php8-fpm log](https://paste.yunohost.org/imuzabiroc)

[php8.4-fpm log](https://paste.yunohost.org/nepiyutaqe)

**Comment by tutle** [comment]
When I do

sudo -u nextcloud php7.4 occ files:scan --all

answer is

An unhandled exception has been thrown:

OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)

**Comment by tutle** [comment]
Do I have to reinstall nextcloud to solve this issue ? Seems to have a few problems...
https://paste.yunohost.org/zubikepoko.tex

**Comment by tutle** [comment]
I finally reinstalled nexcloud after a backup, will resend new shared links.
There was one user very strange password error, seems a ldap trouble

**Comment by tutle** [comment]
Problem is back...
Well, after investigations in Nextcloud,
if I’m connected to yunohost or nextcloud on my web browser (Firefox), disconnect and change yunohost or nextcloud user (admin account) and then try to open a shared link, the link doesn’t open and there are many brut force attempts in the nextcloud journalisation (I remove them from database with phpmyadmin).
Only solution I found to fix the problem : remove cookies and cache from the browser. Or trying the link on another web browser (not very user friendly). Maybe the reason of user_ldap Bind failed: 49: Invalid credentials.
The problem seems to come from different users connections on same browser.

I have spip installed on the same domain (subfolder /spip) and spip is based as root access of the domain. Work in progress…

**Comment by tutle** [comment]
I still have brute force attempts and this alert in nextcloud log :
`Configuration Error (prefix ): either no password is given for the user agent or a password is given, but not an LDAP agent.`
no idea how to solve this

**Comment by navanchauhan** [comment]
> When I do
> 
> sudo -u nextcloud php7.4 occ files:scan --all
> 
> answer is
> 
> An unhandled exception has been thrown:
> 
> OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)

```
sudo su -
cd /var/www/nextcloud/
sudo -u nextcloud php8.1 --define apc.enable_cli=1 occ  files:scan --all
```

**Comment by tituspijean** [comment]
Closing, as the issue is stale and hopefully solved. Feel free to reopen if needed.
