### ISSUE TITLE
upgrade from 24.07 to 25.0.2 is not supported anymore in i386

### ISSUE THREAD

**Issue by villadalmine** [YunoHost-Apps/nextcloud_ynh#534]
ERROR ---> https://paste.yunohost.org/raw/uxetalidod

ended_at: 2022-12-12 14:33:17.213787
env:
  BASH_XTRACEFD: '7'
  NO_BACKUP_UPGRADE: '0'
  YNH_APP_ACTION: upgrade
  YNH_APP_BASEDIR: /var/cache/yunohost/app_tmp_work_dirs/app_6l7p_dhj
  YNH_APP_CURRENT_VERSION: 24.0.7~ynh1
  YNH_APP_ID: nextcloud
  YNH_APP_INSTANCE_NAME: nextcloud
  YNH_APP_INSTANCE_NUMBER: '1'
  YNH_APP_MANIFEST_VERSION: 25.0.2~ynh1
  YNH_APP_PACKAGING_FORMAT: '1.0'
  YNH_APP_UPGRADE_TYPE: UPGRADE_APP
  YNH_ARCH: armhf
  YNH_CWD: /var/cache/yunohost/app_tmp_work_dirs/app_6l7p_dhj/scripts
  YNH_INTERFACE: api
  YNH_STDRETURN: /tmp/tmpkyiw4bk1/stdreturn
error: An error occurred inside the app upgrade script
interface: api
operation: app_upgrade
parent: null
related_to:
- - app
  - nextcloud
started_at: 2022-12-12 14:33:13.416883
success: false
yunohost_version: 11.1.0.2

2022-12-12 14:33:16,151: DEBUG - + upgrade_type=UPGRADE_APP
2022-12-12 14:33:16,151: DEBUG - + '[' armhf == i386 ']'
2022-12-12 14:33:16,152: DEBUG - + '[' armhf == armhf ']'
2022-12-12 14:33:16,152: DEBUG - + ynh_die '--message=Sorry, Nextcloud has deprecated 32-bit support'
2022-12-12 14:33:16,206: WARNING - Sorry, Nextcloud has deprecated 32-bit support
2022-12-12 14:33:17,211: ERROR - Could not upgrade nextcloud: An error occurred inside the app upgrade script

**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to the app itself. Refer to its documentation or repository for help.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug

*A clear and concise description of what the bug is.*

### Context

- Hardware: *VPS bought online / Old laptop or computer / Raspberry Pi at home / Internet Cube with VPN / Other ARM board / ...*
- YunoHost version: x.x.x
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no / yes*
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app install the_app
    ```
- *If you used the webadmin, please perform the equivalent command from the CLI first.*
- *If the error occurs in your browser, explain what you did:*
   1. *Go to '...'*
   2. *Click on '...'*
   3. *Scroll down to '...'*
   4. *See error*

### Expected behavior

*A clear and concise description of what you expected to happen. You can remove this section if the command above is enough to understand your intent.*

### Logs

*When an operation fails, YunoHost provides a simple way to share the logs.*
- *In the webadmin, the error message contains a link to the relevant log page. On that page, you will be able to 'Share with Yunopaste'. If you missed it, the logs of previous operations are also available under Tools > Logs.*
- *In command line, the command to share the logs is displayed at the end of the operation and looks like `yunohost log display [log name] --share`. If you missed it, you can find the log ID of a previous operation using `yunohost log list`.*

*After sharing the log, please copypaste directly the link provided by YunoHost (to help readability, no need to copypaste the entire content of the log here, just the link is enough...)*

*If applicable and useful, add screenshots to help explain your problem.*

**Comment by ericgaspar** [comment]
This is not an error it is a Nextcloud limitation. https://help.nextcloud.com/t/32-bit-support-is-no-longer-available-from-nextcloud-what-are-the-takeaways/143879
But apparently support as been extended to version 26: https://help.nextcloud.com/t/deprecation-of-32-bit-support-ends-completely-with-nextcloud-26/150926

**Comment by lapineige** [comment]
There is a fix (we putted an artificial limitation to upgrades by errors) in the testing branch that you can try, or wait for it to be merged.

**Comment by villadalmine** [comment]
is there any way to compile it for 32bit or i always need someone from nextcloud community to get it working
and why i have i386 if i download yunohost for pi

im using 5.15.76-v7l+ for armv7l, am i wrong i guess pi4 is 64bit with armv7l
i am not sure why my yunohost version is 32 bit, it is using rapsbian

**Comment by villadalmine** [comment]
or maybe i download the bad one because it is 32 bit :( 
https://yunohost.org/en/install/hardware:rpi2plus

**Comment by ericgaspar** [comment]
If I'm not mistaken, armv7l is a 32 bit processor.

**Comment by villadalmine** [comment]
ok ,so i used bad image in my pi4 :(
just close the PR, meantime i know support wil be ok until 26, i have time to migrate

**Comment by villadalmine** [comment]
Information was provided , i386 will be supported from mainstream nextcloud until version 26

**Comment by rosbeef** [comment]
Is the current package already corrected in master? I can not upgrade to 25 on odroidhc1 32 bits
