### ISSUE TITLE
The PHP OPcache module is not properly configured

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/nextcloud_ynh#536]
I get this issue for the past many months now on 3 of my servers. I am using the Nextcloud versions from 23 to 25.

```
The PHP OPcache module is not properly configured. See the documentation ↗ for more information.

    The OPcache buffer is nearly full. To assure that all scripts can be hold in cache, it is recommended to apply opcache.memory_consumption to your PHP configuration with a value higher than 2048.
    The OPcache interned strings buffer is nearly full. To assure that repeating strings can be effectively cached, it is recommended to apply opcache.interned_strings_buffer to your PHP configuration with a value higher than 32.
```

I have increased these values in `/etc/php/8.0/fpm/pool.d/nextcloud.conf` several times over. Rebooted the server too. No change. Anyone has any idea? Is it conflicting with other YNH apps that may use PHP OPcache?

**Comment by stepcellwolf** [comment]
Hi,

I'm having this issue now with the latest version, I updated yesterday to 27.1.2. And I also get the following error too:
`Your web server is not properly set up to resolve "/[]/ocm-provider/". This is most likely related to a web server configuration that was not updated to deliver this folder directly. Please compare your configuration against the shipped rewrite rules in ".htaccess" for Apache or the provided one in the documentation for Nginx at it's [documentation page ↗](https://docs.nextcloud.com/server/27/go.php?to=admin-nginx). On Nginx those are typically the lines starting with "location ~" that need an update`.

Does anyone else is having the same issues?

**Comment by ericgaspar** [comment]
There is a fix that need to be tested: https://github.com/YunoHost-Apps/nextcloud_ynh/pull/607

**Comment by tio-trom** [comment]
I have to say that I do not see this issue anymore. I am using the 27.0.2 Nextcloud version. So for myself it is all good. Should I close this?

**Comment by tio-trom** [comment]
Bummer....I see it again... but the fix you have merged may fix it anyway ;) - thanks!
