### ISSUE TITLE
Create an occ script to easely launch occ command

### ISSUE THREAD

**Issue by Mistermasque** [YunoHost-Apps/nextcloud_ynh#540]
# Context

On my Yunohost instance, lauching occ command for nextcloud need a long command line :
```bash
sudo -u nextcloud /usr/bin/php8.0 --define apc.enable_cli=1 /var/www/nextcloud/occ ....
```

To avoid this, I made a small script **/usr/bin/occ** :
```bash
#!/bin/bash
# This script allows you to launch occ command according to Nextcloud configuration with Yunohost.

OCC='/var/www/nextcloud/occ'
PHP='/usr/bin/php8.0'
USER='nextcloud'

if [ $( whoami ) != 'root' ]; then
        echo "You need to be root !" >&2
        exit 1
fi

sudo -u $USER $PHP --define apc.enable_cli=1 $OCC $@
```

Do you think it's a good idea to integrate it with the nextcloud app for Yunohost ?

# Environnement
- Debian 5.10.158-2
- Yunohost 11.0.10.2 (stable)
- Nextcloud Hub 3 (25.0.2)

**Comment by tituspijean** [comment]
It could be interesting to combine this with https://github.com/YunoHost/issues/issues/2041.

**Comment by lapineige** [comment]
I'm not sure it's a good idea to "obfuscate" all of these (important) parameters in a custom script, in particular in one that use a "standard" tool name. I would rather document it in the readme here (and maybe explain the command parameters) so our user could copy-paste to keep it simple, or learn from it and adapt it if needed.

However, if we integrate it, both OCC, PHP and USER parameters should be controlled by the script, upgraded with each version (new php version, …), and so on.

**Comment by Bugsbane** [comment]
How about a patch modifying the original OCC to show a message telling the user the full command needed if it detects an error known to be created by not using that full command? (eg. the wrong user, missing apc.enable_cli=1 etc)

**Comment by Mistermasque** [comment]
It could be possible to print the command line before executing it like this :
```bash
echo "Executing occ command : sudo -u $USER $PHP --define apc.enable_cli=1 $OCC $@"
sudo -u $USER $PHP --define apc.enable_cli=1 $OCC $@
```

**Comment by ericgaspar** [comment]
Shouldn't this script be defined locally as a shortcut?

**Comment by tituspijean** [comment]
Issue addressed by the aforementioned PR, with the use of `yunohost app shell` and proper documentation.

**Comment by ericgaspar** [comment]
Command to use is now displayed in `ADMIN.md` page: https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/doc/ADMIN.md
