### ISSUE TITLE
Nextcloud may support 32bits for >=v26

### ISSUE THREAD

**Issue by Gredin67** [YunoHost-Apps/nextcloud_ynh#546]
There is some effort to keep support for 32bits architecture up to nextcloud 26 included (and maybe longer?).
https://github.com/nextcloud/server/issues/36072

So do not throw you older devices too quickly! Thank them for the planet :ringed_planet:

**Comment by tituspijean** [comment]
We are now on Nextcloud v27, is this still relevant?

**Comment by ericgaspar** [comment]
32bit seems to be supported... closing
