### ISSUE TITLE
Nextcloud 25.0.2 corrupt source

### ISSUE THREAD

**Issue by zamentur** [YunoHost-Apps/nextcloud_ynh#547]
This evening the checksum of 25.0.2.tar.bz2 has changed !

```
Info : DEBUG - ++ wget --tries 3 --no-dns-cache --timeout 900 --no-verbose --output-document=/var/cache/yunohost/download/nextcloud/app.tar.bz2 https://download.nextcloud.com/server/releases/nextcloud-25.0.2.tar.bz2
Info : DEBUG - + out='2023-01-13 00:52:43 URL:https://download.nextcloud.com/server/releases/nextcloud-25.0.2.tar.bz2 [149894878/149894878] -> "/var/cache/yunohost/download/nextcloud/app.tar.bz2" [1]'
Info : DEBUG - + sha256sum --check --status
Info : DEBUG - + ynh_die '--message=Corrupt source'
Info : DEBUG - + ynh_exit_properly
```

Previous checksum d6ab40faa108937bda42395f570ff111f4c97343b55be1420024da3177e37d59
New checksum cd58a0c514e5e9573d2944c515e23824f04a745eb244f7a7e3b87e04b446c3b9

**Comment by alexAubin** [comment]
Wtf o_O

I wonder if there's a diff with https://github.com/nextcloud/server/archive/refs/tags/v25.0.2.tar.gz (which is .gz, not .bz2, but i mean the effective content)

**Comment by ericgaspar** [comment]
For me the shasum hasn't change... o.O

**Comment by MCMic** [comment]
> For me the shasum hasn't change... o.O

Same here I get d6ab40faa108937bda42395f570ff111f4c97343b55be1420024da3177e37d59 which is what is expected.

**Comment by Gredin67** [comment]
Answer on the nextcloud support room: 
does the gpg signature still matches?
the sha512sum matches
at the moment they match
d6ab40faa108937bda42395f570ff111f4c97343b55be1420024da3177e37d59  [nextcloud-25.0.2.tar.bz](http://nextcloud-25.0.2.tar.bz2)

**Comment by zamentur** [comment]
Very strange, we will try again with sans-nuage, but it's quite strange that twice we got the same error...
I downloaded it also via my personnal internet connexion, so it's strange.

**Comment by zamentur** [comment]
SO i checked again, i have the right checksum with a new downloaded archive from my personnal internet connexion.

I think the tar.bz2 has been changed temporarily 2 days ago.

**Comment by zamentur** [comment]
I have checked the content it seems to be a strange corruption of a js file inside photos app

```
apps/photos/js/photos-vendors-node_modules_nextcloud_upload_dist_index_esm_js-node_modules_vue-virtual-grid_dist_vu-6cc681.js
```
I think we could close this issue.

**Comment by alexAubin** [comment]
(I checked on my side right after @zamentur reported the issue and I was able to confirm that the checksum did change on my side)

**Comment by ericgaspar** [comment]
![strats-image-4003479](https://user-images.githubusercontent.com/46165813/212565819-c24ca571-946f-48f0-8fe6-16f0c6db8a69.png)

**Comment by lapineige** [comment]
Well, it's a good thing we have this checksum mechanism 😃
