### ISSUE TITLE
ERROR1064 : SQL syntax error

### ISSUE THREAD

**Issue by glt248** [YunoHost-Apps/nextcloud_ynh#557]
### Describe the bug
*
Nextcloud's installation fail on yunohost fresh installation.

I just install a fresh yunohost on a Debian Stable (Bullseye), everything goes right. I'm trying to install Nextcloud on a subdomain, but the installation fails. I've tried it from the webadmin and with keyboard+screen. The SQL syntax error is explained by running installation from command line*

### Context

- Hardware: *Old laptop or computer*
- YunoHost version: 11.1.6
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: *nextcloud 25.0.3~ynh1*

### Steps to reproduce

    ```sh
    sudo yunohost app install yunohost
    ```

### Logs

https://paste.yunohost.org/raw/hixiyoviho

![image](https://user-images.githubusercontent.com/74414695/217289350-9926235d-543f-4327-8d84-471bd007a4b6.png)

**Comment by tituspijean** [comment]
Closing, as the issue is stale and hopefully solved. Feel free to reopen if needed.
