### ISSUE TITLE
Nextcloud installation fails on Yunohost 2.5

### ISSUE THREAD

**Issue by CharlesAracil** [YunoHost-Apps/nextcloud_ynh#56]
The nextcloud_ynh does not seem to check the version of yunohost, and always use the ynh_replace_string, which is new to yunohost 2.6.

The official image for raspberry pi is still 2.5, so the installation fails.

It can be solve by running on the command line a:

`apt-get update && apt-get dist-upgrade.`

However, it might be relevant to check the version and install accordingly.

Best regards

**Comment by frju365** [comment]
Thanks for having reported this issue ! :)
frju365
