### ISSUE TITLE
Nexcloud install fails: `Username is invalid because files already exist for this user`

### ISSUE THREAD

**Issue by gordonhjs** [YunoHost-Apps/nextcloud_ynh#561]
### Describe the bug

The Nextcloud installation fails with error `Username is invalid because files already exist for this user`.

### Context

- Hardware: *Raspberry Pi 4 at home *
- YunoHost version: 11.1.11.2
- I have access to my server: *Through SSH and through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: Nexcloud

### Steps to reproduce

    ```sh
    sudo yunohost app install nextcloud
    ```

### Expected behavior
Nexcloud installed without issue

### Logs

https://paste.yunohost.org/raw/terumizetu

**Comment by twiguard** [comment]
If you had NC installed in the before, the /home/yunohost.app/nextcloud/ dir can sometimes be left sitting there. You should be ok just removing it and installing again.
