### ISSUE TITLE
Raspberry PI, Debian, Yunohost and Nextcloud : not working?

### ISSUE THREAD

**Issue by genma** [YunoHost-Apps/nextcloud_ynh#60]
If someone can help in this post (in French) https://forum.yunohost.org/t/err-404-sur-une-installation-nexcloud/3401/8 or tell me if there are known troubles with Nextcloud installation on Raspberry. Thank you.

**Comment by maniackcrudelis** [comment]
https://forum.yunohost.org/t/err-404-sur-une-installation-nexcloud/3401/23
