### ISSUE TITLE
Cannot update due to back up fail

### ISSUE THREAD

**Issue by TheTrveAnthony** [YunoHost-Apps/nextcloud_ynh#601]
Hi,

### Describe the bug

When I try to upgrade nextcloud via the cli interface, it fails to back it up and cancels the whole process

### Context

- Hardware: RaspberryPi 4 at home
- YunoHost version: 11.2.4
- I have access to my server: Through SSH and webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- If upgrading, current package version: 26.0.3

### Steps to reproduce

enter `yunohost app upgrade nextcloud`

### Expected behavior

Nextcloud updates

### Logs

 https://paste.yunohost.org/raw/evisolosaf

According to the 4th line from the end, there is already a backup, so I guess I simply need to delete it, but I don't know where it is or how to get its path, does anybody know where it is (Supposing this is what causes the problem)

Thanks

**Comment by Bugsbane** [comment]
You can list what backups exist, either through the webadmin or by CLI (yunohost backup list). From there you can choose the backup to delete, once again through the webadmin or by CLI (yunohost backup delete NAME_FROM_THE _PREVIOUS_LIST ).

Try that and then see if the upgrade works.

**Comment by TheTrveAnthony** [comment]
Sorry for the delayed answer,

That did the trick, thanks a lot !
