### ISSUE TITLE
Can't open public shared links

### ISSUE THREAD

**Issue by retiolus** [YunoHost-Apps/nextcloud_ynh#620]
When trying to open a public shared link, I get an "Internal Server Error":

`OCA\Files_Reader\Listeners\LoadViewerListener::__construct(): Argument #3 ($userId) must be of type string, null given in file '/var/www/nextcloud/apps/files_reader/lib/Listeners/LoadViewerListener.php' line 32`

**Comment by ericgaspar** [comment]
do you have an app called `files_reader`?
