### ISSUE TITLE
YNH Documentation about OnlyOffice could be reordered for clarity

### ISSUE THREAD

**Issue by narFnarF** [YunoHost-Apps/nextcloud_ynh#624]
### Describe the bug

The yunohost documentation on how to install Onlyoffice starts by describing how to install OnlyOffice using the Nextcloud app way, while warning that the performances are poor and lack ARM support, then explains that there's a better way, using the yunohost onlyoffice app.

Why not reorder the sections so that it explains the better way first? Wouldn't it be clearer?

### Steps to reproduce
- Go to https://github.com/YunoHost-Apps/nextcloud_ynh#configure-onlyoffice-integration
- Look at the section "[Configure ONLYOFFICE integration](https://github.com/YunoHost-Apps/nextcloud_ynh#configure-onlyoffice-integration)"

**Comment by narFnarF** [comment]
If someone point me in the right direction, I could make this change myself and do a pull request. Would I only need to change the Readme.md file? Is that what the yunohost admin interfaces uses to display at the bottom of https://example.com/yunohost/admin/#/apps/nextcloud/main ?

**Comment by ericgaspar** [comment]
This is the file to modify [DESCRIPTION.md](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/testing/doc/DESCRIPTION.md)
README.md is generated from it

**Comment by narFnarF** [comment]
I'm not super familiar with Github's pull-requests. I hope I did it properly?

**Comment by lapineige** [comment]
#634 sounds good, I'm not sure about #635 (it not targeting testing, hence there is a lot of patches from the testing branch that you forked). Can you change the target to be testing ?

**Comment by lapineige** [comment]
Should we close ?

**Comment by narFnarF** [comment]
yes
