### ISSUE TITLE
502 Gateway Time-out

### ISSUE THREAD

**Issue by Crashone** [YunoHost-Apps/nextcloud_ynh#625]
### Describe the bug

Each time I navigate through files via the web interface, Nextcloud server is no longer responding and ended with a 502 Gateway Time-out : 

![Screenshot_20231110_150614](https://github.com/YunoHost-Apps/nextcloud_ynh/assets/20670076/e1af2eee-0d22-4afb-95bb-d91fe504578a)

Other applications are not affected, and I can still connect to Yunohost web interface.

### Context

- Hardware: OVH VPS 
- YunoHost version: 11.2.5 (stable)
- I have access to my server: Through SSH and through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: NO

### Logs

/var/log/ngnix/MyNextcloudURL-error.log : 

- 2023/11/10 23:33:51 [error] 1191#1191: *4386 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 2a01:cb14:aa7:6e00:f1a3:48a9:d78b:98f8, server: MyNextcloudURL, request: "GET /index.php/204 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm-nextcloud.sock", host: "MyNextcloudURL"

**Comment by alexAubin** [comment]
Can you check that the service php8.2-fpm is up and running (in Tools > Services)

**Comment by Crashone** [comment]
> Can you check that the service php8.2-fpm is up and running (in Tools > Services)

Yes it is.

**Comment by Crashone** [comment]
Here the full  log : 
https://paste.yunohost.org/vikahiyoxu

**Comment by tio-trom** [comment]
Yes happens to me too. You have to increase some numbers. Go to `/etc/php/8.2/fpm/pool.d` and edit the file nextcloud.conf.
```

pm = static
pm.max_children = 100
pm.max_requests = 500
request_terminate_timeout = 1d
```

I added `pm.max_children = 100` and with my server's resources it works well. Test to see how much you need. Make sure to restart the php-fpm after you do any changes in order for them to take effect.

**Comment by Crashone** [comment]
Thank you for this workaround.

**Comment by alexAubin** [comment]
Closing because the issue appears to be fixed by tweaking the `pm` settings
