### ISSUE TITLE
Upgrade to NextCloud 12.0.3

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/nextcloud_ynh#63]
The new update is [available](https://nextcloud.com/blog/nextcloud-updates-12.0.3-11.0.5-are-here/)!

**Comment by mokas01** [comment]
Perhaps direct update to [NC 13](https://nextcloud.com/blog/nextcloud-13-brings-secure-file-sync-and-collaboration-to-the-next-level/)

**Comment by frju365** [comment]
Yes. Indeed. Better to upgrade directly to NC13
