### ISSUE TITLE
[Solved] Update to 28.0.1 not possible => OCC issue (webadmin + CLI)

### ISSUE THREAD

**Issue by ultrajej** [YunoHost-Apps/nextcloud_ynh#649]
# Update to 28.0.1 not possible => OCC issue (webadmin + CLI)

## Action: Update Nextcloud (nextcloud) from 27.1.4_ynh1 to 28.0.1_ynh1
_I am trying to update the version of NextCloud on my machine but it fail update this app in any way... (webadmin + CLI)_

_After failing to install, it can restore the version 27 without issue..._
## Context

- YunoHost 11.2.9.1 (stable) with components up to date 2024-01-15
- Host: Oracle VM stored on SSD
- Full access to my machine
- All internal applications of Nextcloud are also up to date
```
System:    Host: SOMETHING.ynh.fr Kernel: 5.10.0-27-amd64 x86_64 bits: 64 Console: tty 0
           Distro: Debian GNU/Linux 11 (bullseye)
Machine:   Type: Virtualbox System: innotek product: VirtualBox v: 1.2 serial: <superuser required>
           Mobo: Oracle model: VirtualBox v: 1.2 serial: <superuser required> BIOS: innotek v: VirtualBox date: 12/01/2006
CPU:       Info: Triple Core Intel Core i5-6600K [MCP] speed: 3504 MHz
Graphics:  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.18.0.0
           Display: server: No display server data found. Headless machine? tty: 138x29
           Message: Advanced graphics data unavailable in console. Try -G --display
Network:   Device-1: Advanced Micro Devices [AMD] 79c970 [PCnet32 LANCE] driver: pcnet32
           Device-2: Intel 82371AB/EB/MB PIIX4 ACPI type: network bridge driver: piix4_smbus
           Device-3: Red Hat Virtio network driver: virtio-pci
Drives:    Local Storage: total: 512 GiB used: 73.09 GiB (14.3%)
Info:      Processes: 3 Uptime: 55m Memory: 7.76 GiB used: 4.08 GiB (52.5%) Init: N/A runlevel: 5 Shell: Bash inxi: 3.3.01
```
### CLI
`sudo yunohost tools upgrade apps`
### Webadmin
From the admin screen 

1. Go to Update system

`[Mettre à jour le système](https://192.168.0.101/yunohost/admin/#/update))`

2. Click on either update all apps or update Nextcloud only
## Expected behavior

Nextcloud should be updated to the version 28.0.1

## Logs
```
...
Info : DEBUG - #15 /var/www/nextcloud/occ(11): require_once('...')
Info : DEBUG - #16 {main}+ '[' 1 -eq 3 ']'
Info : DEBUG - + ynh_die '--message=Unable to upgrade Nextcloud'
Info : WARNING -     2/0 [----->----------------------]   0%Unable to upgrade Nextcloud
Info : DEBUG - + ynh_exit_properly
Attention : Upgrade failed ... attempting to restore the safety backup (Yunohost first need to remove the app for this) ...
Info : Suppression de nextcloud...
...
```
### require_once is empty:

`require_once('...')`
A similar case can be found here: https://help.nextcloud.com/t/solved-php-fatal-error-occ-files-scan/132038
Could it be a issue with my PHP version?

On other cases at the same stage require_once is not empty. It is more related to privilege issues

---
Full log available at: https://paste.yunohost.org/raw/ifixokaxej

---
## Solution / Fix
One of my Nextcloud apps was not compatible with Nexcloud 28.0.1: Keeweb
I uninstalled keeweb and was able to update to Nexcloud 28.0.1 with other issue

**Comment by orhtej2** [comment]
It's [keeweb](https://apps.nextcloud.com/apps/keeweb) that's failing the upgrade, can you uninstall this app, upgrade then reinstall it?

**Comment by ultrajej** [comment]
Solved... see **Solution / Fix** above
