### ISSUE TITLE
Add a link to incompatible apps on big upgrades

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/nextcloud_ynh#654]
### Describe the bug

Many people on the forum opened a ticket about the migration 27 -> 28, that failed due to an incompatible app

### Expected behavior

Some tools manage this by deactivating all apps, then upgrade NextCloud, then re-activate.
This way will make the upgrade work BUT could lead to removed apps.

One way to help people know if they can do an upgrade is to give them the " official " NextCloud incompatible list link.
For 28, it is there : https://help.nextcloud.com/t/apps-not-compatible-with-nc-28/176234

I know there can be a message AFTER an upgrade, but is it possible to add one BEFORE, so people can check with their installation ?

The other solution would be to contact the marketplace and check each installed app, but just giving admin a link could be a lot less work.

**Comment by alexAubin** [comment]
cf https://github.com/YunoHost-Apps/nextcloud_ynh/pull/647 which is "almost ready", just need to debug one weird failing upgrade in tests

**Comment by supermamie** [comment]
Then I close my issue, as always : YunoHost’s contributors are the best !
