### ISSUE TITLE
Cant connect over plain http, always tries to redirect to https (android apps require either plain http or valid cert, which I cant get)

### ISSUE THREAD

**Issue by waikaeth** [YunoHost-Apps/nextcloud_ynh#656]
### Describe the bug

I am unsure if this is an issue with nextcloud package in particular or with yunohost configs in general, but Nextcloud forces redirect to https, despite https redirect being disabled in yunohost with `yunohost settings set security.nginx.redirect_to_https -v False` and despite changing the config.php file to say `''overwrite.cli.url' => 'http://nextcloud.local',` rather then what it was set to `'overwrite.cli.url' => 'https://nextcloud.local',`

If I directly enter the url `http://nextcloud.local/login` in the address bar, the page will load in plain http, but it wont let me log in. hitting enter just takes me back to login screen. whether or not the password is correct does not even matter, whether the credentials are correct or not, page just reloads. I suspect this has something to do with the SSO ?

And using `http://nextcloud.local` redirects to https. And since my box has no internet connection, Its a self signed cert. Which the vast majority of android apps will not accept (like flocus). Plain http would be fine. but I cant figure out how to get plain http to work.

### Context

- Hardware: laptop or computer
- YunoHost version: x.x.x
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: no internet. yunohost only reachable via an isolated wifi network 
- Using: 27.1.4~ynh1

### Steps to reproduce

in url bar of fresh browser, type http://nextcloud.local. domain redirects to https. 

### Expected behavior

dont redirect to https. I cant get a valid cert, so I need plain http

**Comment by alexAubin** [comment]
cf https://github.com/YunoHost/issues/issues/2319#issuecomment-1913307869
