### ISSUE TITLE
Add redirects for javascript xmpp ojsxc

### ISSUE THREAD

**Issue by ckiw** [YunoHost-Apps/nextcloud_ynh#66]
Hello,

I'd like to use https://apps.nextcloud.com/apps/ojsxc but the bosh server configuration isn't configured properly for that.

You can see https://forum.yunohost.org/t/solved-configure-xmpp-in-nextcloud-addon-javascript-xmpp-client/2934/3 for a manual solution.

Hope somebody can help with that ;)

**Comment by ckiw** [comment]
Hello, 

For information, I succeed by adding this conf file : 
`/etc/nginx/conf.d/cloud.xxxxx.fr.d/redirect.conf` 

containing that : 

```
location /http-bind {
  proxy_pass        http://127.0.0.1:5290/http-bind;
  proxy_redirect    off;
  proxy_set_header  Host $host;
  proxy_set_header  X-Real-IP $remote_addr;
  proxy_set_header  X-Forwarded-Proto $scheme;
  proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header  X-Forwarded-Host $server_name;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";

  # Include SSOWAT user panel.
  include conf.d/yunohost_panel.conf.inc;
  more_clear_input_headers 'Accept-Encoding';
}
```

And the config in nextcloud admin panel 

![selection_001](https://user-images.githubusercontent.com/3486286/31272671-17d2a79e-aa8c-11e7-8ddb-3cf1979df847.png)

**Comment by alexAubin** [comment]
Closing as wontfix
