### ISSUE TITLE
OCP\HintException: [0]: Memcache OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)

### ISSUE THREAD

**Issue by stepcellwolf** [YunoHost-Apps/nextcloud_ynh#665]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to the app itself. Refer to its documentation or repository for help.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug

I'm unable to execute the `sudo -u www-data php8.2 occ status`
I'm getting the following error message:
```
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?) 
```

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.10
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: I did a server migration from one provider to other
- Using, or trying to install package version/branch: master/main
- Nexloud version: 28.0.2~ynh1
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sudo -u www-data php8.2 occ status
    ```
- APCU nextcloud config
   ```
    'memcache.local' => '\\OC\\Memcache\\APCu',
    ```
- module enable
   ```
    $ php8.2 -i | grep apcu
    /etc/php/8.2/cli/conf.d/20-apcu.ini,
     apcu
    ```

### Expected behavior

To get status report or to be able to perform different nextcloud tasks. APCu is enabled

### Logs

Logs can be provided on request.

**Comment by orhtej2** [comment]
Proper syntax to use is to add `--define apc.enable_cli=1` to `occ` invocation, and use `nextcloud` user (not `www-data`), like so:

`sudo -u nextcloud php8.2 --define apc.enable_cli=1 occ status`
