### ISSUE TITLE
After VPS transfer from Gandi to Infomaniak, restore is KO

### ISSUE THREAD

**Issue by DansLeRuSH** [YunoHost-Apps/nextcloud_ynh#708]
### Describe the bug
Hi team, I transferred my VPS initially from Gandi to a new Infomaniak VPS Lite.

I made a full backup on VPS1, downloaded this backup that I then transferred to VPS2.

On the four applications I use, three went well at restore but not Nextcloud. No anomalies visible during restoration but impossible to access the application.

I don't know if it'll help, but I've kept (for the moment) the original DNS.

Could you help me ?

Thanks in advance.

Best regards,
Franck

PS : I also tried to install Nextcloud directly and I have this > https://paste.yunohost.org/raw/ujiloyunak

### Context

- Hardware : Infomaniak's VPS Lite (1 CPU, 2 Go and 20 Go)
- YunoHost version : 11.2.23 (stable)
- I have access to my server : Through *SSH* and *webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? *no*
- Using, or trying to install package version/branch : 29.0.2-ynh1

### Steps to reproduce

Through the webadmin interface, go into backups and try to restore the Nextcloud application with my data.

### Expected behavior

A functional and accessible application

### Logs

*When I try to launch the app I have :*
>Internal Server Error

>The server encountered an internal error and was unable to complete your request.
>Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
>More details can be found in the server log.

*In Logs I have :*

>Erreur: "500"

>Action: "GET" /yunohost/api/logs?limit=25&with_details&locale=fr

>Retraçage

>Traceback (most recent call last): File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 450, in process ret = >self.actionsmap.process(arguments, timeout=30, route=_route) File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line >574, in process return func(**arguments) File "/usr/lib/python3/dist-packages/yunohost/log.py", line 135, in log_list >_update_log_parent_symlinks() File "/usr/lib/python3/dist-packages/yunohost/log.py", line 90, in _update_log_parent_symlinks logs = >glob.iglob("*" + METADATA_FILE_EXT, root_dir=OPERATIONS_PATH) TypeError: iglob() got an unexpected keyword argument 'root_dir'

**Comment by DansLeRuSH** [comment]
> Can you update yunohost, in order to fix the log error and get the logs from the restore script?
> 
> The error encountered during installation is related to the fact that there is data (probably the rest of the restoration that went wrong) in `/home/yunohost.app/nextcloud/`

OK. First of all, thank you for your answer !

Then I have an updated YunoHost (no other upgrade proposed anyway). I uninstalled Nextcloud, deleted the directory /home/yunohost.app/nextcloud/ and restarted the restoration.

This is the logs I have (and still the same issue at launching the app) > https://paste.yunohost.org/raw/akuhejuqiw

**Comment by kay0u** [comment]
You're welcome!

There is a bug in this package, we are installing `php8.3` packages, but configuring `php8.2-fpm` files.

If you are not afraid, you can move `/etc/php/8.2/fpm/pool.d/nextcloud.conf` to `/etc/php/8.3/fpm/pool.d/nextcloud.conf` restart both `php8.2-fpm` and `php8.3-fpm`

```
sudo systemctl restart php8.2-fpm
sudo systemctl restart php8.3-fpm
```

In file `/etc/nginx/conf.d/domain2.tld.d/nextcloud.conf`, change the line corresponding to https://github.com/YunoHost-Apps/nextcloud_ynh/blob/9a2bda4ab0f196f07fcc3fef34ff2e09b31e5fcd/conf/nginx.conf#L120C5-L120C72

from `php8.2` to `php8.3`, reload nginx

```
sudo systemctl nginx nginx
```

And it should works.

You can also wait for the next release of this package, upgrade your old nextcloud instance, backup it, and restore it to your new VPS.

**Comment by DansLeRuSH** [comment]
I'm a bit of an adventurer (and I no longer have my first VPS) 🥲 So I moved the _nextcloud.conf_ from PHP 8.2 to 8.3, restarted PHP 8.2 and 8.3, modified the NGINX _nexcloud.conf_, reloaded NGINX ... and it works ! 🎆 

I have a last issue when look into the app thru webadmin, I have this message (sorry for the french) :

![Screenshot_20240725-100855_Fennec](https://github.com/user-attachments/assets/7f464fa4-04af-49d0-9e3b-25507d93ea96)

>Une erreur empêche l'affichage du panneau de configuration :

>Échec de la lecture au retour du script /etc/yunohost/apps/nextcloud/scripts/config. Erreur : Fichier YAML corrompu en lecture depuis /tmp/tmpl9ygwgdh/stdreturn (raison : mapping values are not allowed here<br> in "<unicode string>", line 9, column 60:<br> ... s been thrown: OCP\HintException: [0]: Memcache OC\Memcache\APCu ... <br> ^). Contenu brut : fpm_footprint:<br> high<br>fpm_free_footprint:<br> 0<br>fpm_usage: 'medium'<br>maintenance_mode:<br> 1<br>system_addressbook_exposed:<br> An unhandled exception has been thrown: OCP\HintException: [0]: Memcache OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)<br>

>Merci de signaler cette erreur à l'équipe de YunoHost pour qu'elle soit corrigée !

Did I miss something ?

**Comment by kay0u** [comment]
> Did I miss something ?

No you didn't. The problem is that when you try to navigate to the config panel, it will get some value using php, which remains the old 8.2. But your system miss some packages so you get this error.

If you REAAAAALLY wants to fix that, you can modify the file `/etc/yunohost/apps/nextcloud/settings.yml` and change the `phpversion` from `8.2` to `8.3` (if you open it with vim, as the file is in read-only mode, you can force the save with `:w!` instead of `:w`).

**Comment by DansLeRuSH** [comment]
@kay0u A very huge thank you ! I modify the version (but I'm more team nano ;)) and it works well !

I close the issue and have a nice day ! 🖖
