### ISSUE TITLE
Nextcloud optimizations

### ISSUE THREAD

**Issue by Jibec** [YunoHost-Apps/nextcloud_ynh#73]
Hi, bram quoted this link in dev:
https://help.nextcloud.com/t/nextcloud-having-lots-of-trouble-handling-large-amount-of-files/22364

which suggest:
* To enable redis: https://docs.nextcloud.com/server/12/admin_manual/configuration_files/files_locking_transactional.html?highlight=redis
* To optimize database https://github.com/owncloud/core/issues/20967#issuecomment-205474772

**Comment by JimboJoe** [comment]
Hi,
Regarding the redis part, it has already been implemented here https://github.com/YunoHost-Apps/nextcloud_ynh/commit/57c8122f4a441aba5aab6f041157399904d1de9e
For the database part, can the tuning be restricted to the app's database? If not, it would be better to implement in the core, wouldn't it?
