### ISSUE TITLE
Nextcloud text app don't sync well causing data loss, need Nextcloud update for fix

### ISSUE THREAD

**Issue by ImaCrea** [YunoHost-Apps/nextcloud_ynh#731]
Hi there,

I refer to this issue I posted on the nextcloud text official repo: https://github.com/nextcloud/text/issues/6415

It's said it should work better after updating nextcloud. As this issue is causing data loss within a core feature of nextcloud, I thought it'd be helpful to let you know about it here.

Thanks for all the great work you're doing 🤗

**Comment by ImaCrea** [comment]
Thank you @ericgaspar ! I'll try with 29.0.7.

**Comment by ericgaspar** [comment]
29.0.7 is now on master

**Comment by ImaCrea** [comment]
I updated from the testing tree following your advise and it all went well :)
