### ISSUE TITLE
Access forbidden: Nextcloud became inaccessible 

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/nextcloud_ynh#74]
Hi
Suddenly the Nextcloud became Inaccessible with the login page saying **access forbidden**. I am on testing branch.

I had to add `cgi.fix_pathinfo=1` to /etc/php5/conf.d/nextcloud.ini to make it work again. 
What could be the cause of this sudden denial of access ?

**Comment by SuperSandro2000** [comment]
Still happening....

**Comment by alexAubin** [comment]
Closing because this was 5 years ago , a shitload changed since then, can't reproduce
