### ISSUE TITLE
forward email from ldap

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/nextcloud_ynh#749]
Hello,

I discovered that ynh forward email are registered in ldap.
In some cases, users don't use emails from ynh and all use their private email so we have to set their private email in the forward email field in their ynh account.
However, in nextcloud, their ynh email is retrieved from ldap and thus they have to add manually their email (the same as in the forward email firld in their ynh account).

Would it be possible to add an option in nextcloud admin panel to choose if we want nextcloud to retrieve the main email or the forward email from ldap?

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost-Apps/nextcloud_ynh/pull/753 (currently in testing)
