### ISSUE TITLE
Why is the testing branch trying to download version 29?

### ISSUE THREAD

**Issue by wensndev** [YunoHost-Apps/nextcloud_ynh#757]
When I try to install the testing branch, why does it try to download version 29.0.9 and give an error? I want to install version 30.x.x.

**Comment by ericgaspar** [comment]
What version are you trying to upgrade from?
Nextcloud updates incrementally. For example, if you are on Nextcloud 28 and want to update to 30, Nextcloud needs to update to 29 first.
As for why 29.0.9 is broken, there are plenty of explanations on the forum.

**Comment by wensndev** [comment]
> What version are you trying to upgrade from? Nextcloud updates incrementally. For example, if you are on Nextcloud 28 and want to update to 30, Nextcloud needs to update to 29 first. As for why 29.0.9 is broken, there are plenty of explanations on the forum.

I'm trying to install, not upgrade

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost-Apps/nextcloud_ynh/pull/752/commits/f4624019075f92a3b8f03fbae162b7fa77827188
