### ISSUE TITLE
"Le fichier .htaccess ne fonctionne pas"

### ISSUE THREAD

**Issue by ImaCrea** [YunoHost-Apps/nextcloud_ynh#762]
### Describe the bug

Hi there! I just updated to 29.0.10 and I noticed this security warning in the admin panel :

![Capture d’écran 2024-12-11 à 09 57 58](https://github.com/user-attachments/assets/721517be-af04-4dcb-a3f6-1cb65b346108)

Doesn't look good, isn't it? Makes me very worried.

I'm not sure if it's new or was here before but I believe it's new. I never touched the internal files of Nextcloud, always installed and updated through this package. Thanks for all your precious contribution.

### Context

- Hardware: VPS Hetzner
- YunoHost version: 11.3.0.2

**Comment by CypLef** [comment]
same error as #696

**Comment by ericgaspar** [comment]
duplicate https://github.com/YunoHost-Apps/nextcloud_ynh/issues/696
