### ISSUE TITLE
Music App & ampache api

### ISSUE THREAD

**Issue by juliencognito** [YunoHost-Apps/nextcloud_ynh#78]
Hi there,
Since the [music app](https://apps.nextcloud.com/apps/music) support ampache api, i try to use it instead of using [ampache app](https://github.com/YunoHost-Apps/ampache_ynh) (working anyway) but i can't connect my lineage phone using [power ampache](https://fossdroid.com/a/reactiveampache.html) app.
I already learn that the ampache integration require to generate a dedicated password in personal setting/music ([source](https://help.nextcloud.com/t/ampache-login-with-the-music-app/19748))

I assumed it was relating to the SSO so i tried`sudo yunohost app setting nextcloud skipped_uris -v "/index.php/apps/music/ampache" ` and `sudo yunohost app setting nextcloud skipped_uris -v "/index.php/apps/music/ampache/server/xml.server.php"` follow-up to `sudo yunohost app ssowatconf`
([source](https://forum.yunohost.org/t/solved-disabling-ssowat-login-for-some-url-fr-desactiver-la-connexion-avec-ssowat-pour-certaines-url/1412)) but no success!
I don't know where to find logs to debug by myself or, more likely, to submit here.
Thx for attention,
Julien
`

**Comment by tomdereub** [comment]
Hi,
For me it's working well, I'm using power ampache on lineageOS and the music app on Nextcloud too.
To generate the dedicated password, just go to the music app on Nextcloud, "settings", then "Générer un mot de passe de l'API".

**Comment by juliencognito** [comment]
Hello, I have shamefully forgotten this issue. there's been a lot of update since and you're right, it's working now, probably a music app update or the nextcloud package.
Thank you for your reminder. We can close this issue.
