### ISSUE TITLE
Use BACKUP_CORE_ONLY

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/nextcloud_ynh#79]
https://github.com/YunoHost/yunohost/pull/398

**Comment by zamentur** [comment]
Some people was using backup_core_only to avoid to backup their data.
Here a user surprized by the backup_core_only feature...

https://forum.yunohost.org/t/yunohost-backup-create-ko/7688/6

**Comment by zamentur** [comment]
I classify it as bug, because it was working before the refactoring of the backup script.

**Comment by maniackcrudelis** [comment]
This is not a bug...
The way backup_core_only was managed has been changed for a good reason, see my answer, https://forum.yunohost.org/t/yunohost-backup-create-ko/7688/10.

Using the setting can be a problem for every users, to change the setting to a variable as it is now will be a problem only for users that use a custom backup script.
Those users can adapt their scripts.

**Comment by lapineige** [comment]
Fixed :)
