### ISSUE TITLE
fulltext search

### ISSUE THREAD

**Issue by OhioVR** [YunoHost-Apps/nextcloud_ynh#80]
I would really like to have the fulltextsearch app added to the nextcloud app store and the Elasticsearch companion app, if it is feasable. This is supposed to be the replacement to nextant which required solr. fulltextsearch doesn't require it. https://github.com/nextcloud/fulltextsearch/wiki/Switching-from-Nextant

**Comment by maniackcrudelis** [comment]
You should probably have a look [here](https://apps.nextcloud.com/).
This repository is only about nexcloud integration in [YunoHost](https://yunohost.org/). We do not manage the app store of nextcloud here.
