### ISSUE TITLE
Can't log out from Nextcloud !

### ISSUE THREAD

**Issue by croulibri** [YunoHost-Apps/nextcloud_ynh#83]
Hello,

I am on Nextcloud 12.0.4 with my up to date Yunohost.

Bug 1 :
I log in Yunohost through SSO, I click on Nextcloud icon and arrive in the File section of Nextcloud.
I click on log out from the top right menu section of Nextcloud.
Nextcloud reload and I come back to the Files section of Nextcloud.
_It seems the log out option of Nextcloud is broken._

Bug 2 (similar to [Issue 19](https://github.com/YunoHost-Apps/nextcloud_ynh/issues/19)):
I log in Yunohost through SSO, I click on Nextcloud icon and arrive in the File section of Nextcloud.
I go back to the SSO welcome page (page with all apps icons), I click on log out. I am out of Yunohost.
I enter the direct link to Nextcloud (such as www.myyunohost.org/nextcloud) and I am automatically log in Nextcloud.
And now I can log out Nextcloud from  from the top right menu section of Nextcloud (I am not brought back to the file section of Nextcloud, like in Bug 1 situation).
_I seems the SSO log out does not disconnect Nextcloud._

Other situation : If I log in Nextcloud through direct link  (such as www.myyunohost.org/nextcloud), and entering ID /password on the Nextcloud welcome page, then I can log out from the top right menu section of Nextcloud.
Really strange...

Can other people reproduce these situations ?

**Comment by JimboJoe** [comment]
I've just opened a PR to fix that problem, thanks for reporting!
To test it, simply upgrading the YunoHost package won't work, as the patches are only applied when upgrading the upstream app (it will for 12.0.5 for example).
But you can try to apply to two patches by hand if you're brave enough...

**Comment by croulibri** [comment]
Thanks for your quick reaction.

I have seen your two modified files but I am not sure how I can apply manually these patch ? Could you give me some indication (I may try to be brave 😄  ) ?
I don't understand if I have to modify manually a specific files in my Yunohost Nextcloud or if I should download and run a patch ?
If the latter, which file and how to run it ?

Thanks in advance for your advices !

**Comment by Kcchouette** [comment]
I've the same problem as the Bug 1 reported.
