### ISSUE TITLE
Missing YunoHost tile

### ISSUE THREAD

**Issue by Kcchouette** [YunoHost-Apps/nextcloud_ynh#87]
Hello

On Firefox Nightly (60.0a1 - 26-01-2018), I don't see the yunohost tile.
In the developer console, I see a warning and an error:
```
Loading failed for the <script> with source “https://<hostname>/ynhpanel.js”.
files:86
Content Security Policy: The page’s settings blocked the loading of a resource at https://<hostname>/ynhpanel.js (“script-src”).
```

Thank you

**Comment by JimboJoe** [comment]
This problem is most likely caused by the same problem as #83, and should be fixed with https://github.com/YunoHost-Apps/nextcloud_ynh/pull/84.

**Comment by Kcchouette** [comment]
Thank you for the fix. I'm waiting the next version of the application ^^

**Comment by JimboJoe** [comment]
A testing version is on its way... 😉

**Comment by Kcchouette** [comment]
Fixed by: https://github.com/YunoHost-Apps/nextcloud_ynh/pull/81
