### ISSUE TITLE
Create a cron job when installing nextcloud

### ISSUE THREAD

**Issue by Kcchouette** [YunoHost-Apps/nextcloud_ynh#88]
When installing some apps in nextcloud aplication, we can see that some can't work properly (for eg `news`) because of missing cron.

In my admin view of nexcloud (I've launch it 10 hours ago manually):
```
Background jobs
Last job execution ran 10 hours ago. Something seems wrong. 
```
and if I list cron job as written in the [official documentation](https://docs.nextcloud.com/server/12/admin_manual/configuration_server/background_jobs_configuration.html#cron):
```
# crontab -u www-data -l
no crontab for www-data
# crontab -u nextcloud -l
no crontab for nextcloud
```

So we should create it when installing nextcloud.
Thank you!

**Comment by JimboJoe** [comment]
Cron job is normally created during installation (see [here](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/install#L218)).
Do you have the file `/etc/cron.d/nextcloud` (I do on my own server)?

**Comment by Kcchouette** [comment]
I indeed have this file!
But my instance of nextcloud says there is an error as the last job execution ran there is so many times ago… And it's why I opened this issue.

**Comment by JimboJoe** [comment]
Maybe it had much to do and it is still running for a good reason...?
Do you have relevant messages in `/home/yunohost.app/nextcloud/data/nextcloud.log` or `/var/log/syslog` (related to CRON)?

**Comment by Kcchouette** [comment]
`Jan 29 18:37:01 vps cron[1012]: (*system*nextcloud) WRONG FILE OWNER (/etc/cron.d/nextcloud)`

**Comment by Kcchouette** [comment]
in the /var/log/syslog

**Comment by JimboJoe** [comment]
I have this
```
# ll /etc/cron.d/nextcloud
-rw-r--r-- 1 root root 71 déc.  21 12:13 /etc/cron.d/nextcloud
```
Did your cron job start since yesterday?
If not, can you try changing the file ownership?

**Comment by Kcchouette** [comment]
No, it isn't.
I have changed the ownership: `chown root:root nextcloud`.
When has this cron changed the ownership with admin?

**Comment by JimboJoe** [comment]
Maybe it hasn't and maybe it's not related to your problem... We'll see that.

**Comment by Kcchouette** [comment]
The cron is now working because of the changing ownership. Should I close the issue?

**Comment by JimboJoe** [comment]
No, it's a bug, so it needs to be fixed 🙂 
Thanks for reporting it!
