### ISSUE TITLE
Update to 11.0

### ISSUE THREAD

**Issue by MarcusMoeller** [YunoHost-Apps/nextcloud_ynh#9]
It would be great if you could update the package to the rencently released version 11 of nextcloud.

**Comment by polytan02** [comment]
Also, it would be great to know if the community wishes to pursue to owncloud or nextcloud (and avoid having Jerome working on both systems).

Personally I don't mind as long as it is working for file storage and sharing, secure and up to date.

**Comment by Bugsbane** [comment]
> it would be great to know if the community wishes to pursue to owncloud or nextcloud

Personally I've migrated from ownCloud to Nextcloud.

**Comment by xpd259** [comment]
I've also Migrated from owncloud to Next cloud

**Comment by nath5394** [comment]
Hello, I also migrated from Owncloud to Nextcloud due too the dynamism of the Nextcloud team. 
So I am very interested in having the last version in Yunohost.  Thanks 👍

**Comment by maniackcrudelis** [comment]
Hello

I've upgraded the package to 11.0.0 and added an automatic backup before upgrading.
But, I'm not familiar with this package, I only do this upgrade to follow evolution of nextcloud.
So, check if the upgrade has no regression on your nextcloud.

Jerome seems to be less present on Yunohost, so we maintain thoses apps.
Nextcloud must become official and should replace owncloud as soon as possible.

**Comment by nath5394** [comment]
Hello, thanks for this work I'll try it soon, just after finding time to take a snapshot of my server 😃

**Comment by nath5394** [comment]
Works well for me. Thanks a lot !

**Comment by MarcusMoeller** [comment]
When you do a backup before an ugprade, you seem to do a full backup including data. This is not a very good choise, because e.g. I got about 80GB in my nextcloud which are copied on every updgrade of the app.

**Comment by maniackcrudelis** [comment]
Except an error, if you do not have a version more recent than 11.0.1 (The last version), the script do not do a backup.
https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/upgrade#L24

If you have a more recent version (For next upgrade), the backup do not save the data dir.
https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/upgrade#L22
https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/backup#L26
