### ISSUE TITLE
Automatic maintenance message when upgrading ?

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/nextcloud_ynh#92]
Hello,

I'm wondering if it's possible, from the command line, to show a warning to nextcloud's users, as admin can do with notifications.
If yes, would it be possible to implement it in the upgrade script ?
This would warn our users that their current session is probably going to be shutdown, and avoid doing it manually each time.

**Comment by JimboJoe** [comment]
NextCloud upgrade already puts the server into [maintenance mode](https://docs.nextcloud.com/server/9/admin_manual/maintenance/enable_maintenance.html) during upgrade, it thus already displays a warning when then user tries to open a file through the web interface.
Isn't that enough?

**Comment by lapineige** [comment]
It's already fine, but I means all ongoing work is lost. (= it's too late)

I was thinking about something like a warning a few minutes before the upgrade, but now I realise that it's kind of pointless, the upgrade won't wait for a long time "just to warm current users".
Maybe a warning shown in the web UI, as a notification (and not when (re)loading a page while the maintenance started) - so the users could know that they shouldn't quit nor reload during this time. I was especially thinking about Collabora, as everything would be lost once you quit the page if the server is in maintenance mode (you could copy the content in that case).

But it's sounds a bit overkill, isn't it ? Except if you see a simple solution, maybe I should close this issue.

**Comment by JimboJoe** [comment]
It sounds more like a general question about maintenance warnings in YunoHost, and would better suit in [YunoHost bugtracker](https://dev.yunohost.org).
As far as I'm concerned, I use [CachetHQ](https://github.com/YunoHost-Apps/cachet_ynh) (on another server) to warn subscribed user about planned maintenance and errors. It's very flexible and seems to answer to your need :wink:

**Comment by lapineige** [comment]
> As far as I'm concerned, I use CachetHQ (on another server) to warn subscribed user about planned maintenance and errors. It's very flexible and seems to answer to your need 😉

Not exactly, as I would prefer a warning in Nextcloud screen. (and I won't be able to force my users to subscribe to Cachet notifications).

Anyway, I close this :)
