### ISSUE TITLE
Fail to update to 12.0.5

### ISSUE THREAD

**Issue by michaelquist** [YunoHost-Apps/nextcloud_ynh#93]
I tried to install the update today, and it failed. Ultimately, I uninstalled nextcloud, and tried to reinstall which is also failing. I banged my head against this all day, but I don't know if it is my setup, or something wrong with the update. The install output is here:  https://paste.yunohost.org/cedacamuto.bash

**Comment by frju365** [comment]
So, what I see is that the /var/www/nextcloud path already exists.  Can you retry the installation ? if it doesn't work do : `mv /var/www/nextcloud /var/www/nextcloud-old` and try the installation again.

**Comment by michaelquist** [comment]
Hi. I removed /var/www/nextcloud and tried to install again.  It failed again, with similar output:  https://paste.yunohost.org/acequcitek.diff

**Comment by mokas01** [comment]
Hi, 
I got an issue while updating too
https://paste.yunohost.org/ededadiwix.sql

yunohost: 
  repo: stable
  version: 2.7.9
yunohost-admin: 
  repo: stable
  version: 2.7.7
moulinette: 
  repo: stable
  version: 2.7.7
ssowat: 
  repo: stable
  version: 2.7.7

**Comment by michaelquist** [comment]
If I recall correctly, I ended up reinstalling yunohost. Since then, nextcloud upgrades have worked as expected. I don't know what the problem was.
