### ISSUE TITLE
application activation impossible after upgrade

### ISSUE THREAD

**Issue by valog** [YunoHost-Apps/nextcloud_ynh#94]
Last upgrade of nextcloud desactivated applications contact and calendar

When I try to activate it, nextcloud ask me for a password but user password or yunohost admin password don't work.

yunohost    2.7.9 (stable)
yunohost-admin     2.7.7 (stable)
moulinette     2.7.7 (stable)
ssowat     2.7.7 (stable)

**Comment by JimboJoe** [comment]
Hello,
Deactivating applications is part of the normal upgrade workflow of NextCloud.
To re-activate them, you need to do it from the NextCloud admin account, and you'll have to use the corresponding password.
Did you try to activate them with the NextCloud admin account (defined upon installation)?

**Comment by JimboJoe** [comment]
Without answer, I consider you got your problem sorted out with the right password :wink: 
I close this issue; don't hesitate to open it again if needed!

**Comment by valog** [comment]
Hello
Sorry about my long time reponse.
Thanks for your message and your intervention.
I'm leaving github due to MS buying.
I will try your solution later.

Thank's for all your work.
