### ISSUE TITLE
Several fseek error - Multiples erreurs fseek

### ISSUE THREAD

**Issue by Vitriia** [YunoHost-Apps/nextcloud_ynh#97]
Hi, i have enabled External Storage who point on local and smb storages.
And i have those errors very often...

Bonjour, j'ai External Storage activé avec un lien local et un smb. Et j'ai ces erreurs qui reviennent très souvent..

`fseek(): stream does not support seeking at /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php#74`

**Comment by alexAubin** [comment]
Closing because super old issue, not enough info to reproduce
